SDFM
SDFM
Macros
#define SDFM_GET_LOW_THRESHOLD(C) ((uint16_t)(C))
#define SDFM_GET_HIGH_THRESHOLD(C) ((uint16_t)((uint32_t)(C) >> 16U))
#define SDFM_SET_OSR(X) (((X) - 1) << 8U)
#define SDFM_SHIFT_VALUE(X) ((X) << 2U)
#define SDFM_THRESHOLD(H, L) ((((uint32_t)(H)) << 16U) | (L))
#define SDFM_SET_FIFO_LEVEL(X) ((X) << 7U)
#define SDFM_SET_ZERO_CROSS_THRESH_VALUE(X) (0x8000 | (X))
#define SDFM_FILTER_DISABLE 0x0U
#define SDFM_FILTER_ENABLE 0x2U
#define SDFM_MODULATOR_FAILURE_INTERRUPT 0x200U
#define SDFM_LOW_LEVEL_THRESHOLD_INTERRUPT 0x40U
#define SDFM_HIGH_LEVEL_THRESHOLD_INTERRUPT 0x20U
#define SDFM_DATA_FILTER_ACKNOWLEDGE_INTERRUPT 0x1U
#define SDFM_MASTER_INTERRUPT_FLAG 0x80000000U
#define SDFM_FILTER_1_HIGH_THRESHOLD_FLAG 0x1U
#define SDFM_FILTER_1_LOW_THRESHOLD_FLAG 0x2U
#define SDFM_FILTER_2_HIGH_THRESHOLD_FLAG 0x4U
#define SDFM_FILTER_2_LOW_THRESHOLD_FLAG 0x8U
#define SDFM_FILTER_3_HIGH_THRESHOLD_FLAG 0x10U
#define SDFM_FILTER_3_LOW_THRESHOLD_FLAG 0x20U
#define SDFM_FILTER_4_HIGH_THRESHOLD_FLAG 0x40U
#define SDFM_FILTER_4_LOW_THRESHOLD_FLAG 0x80U
#define SDFM_FILTER_1_MOD_FAILED_FLAG 0x100U
#define SDFM_FILTER_2_MOD_FAILED_FLAG 0x200U
#define SDFM_FILTER_3_MOD_FAILED_FLAG 0x400U
#define SDFM_FILTER_4_MOD_FAILED_FLAG 0x800U
#define SDFM_FILTER_1_NEW_DATA_FLAG 0x1000U
#define SDFM_FILTER_2_NEW_DATA_FLAG 0x2000U
#define SDFM_FILTER_3_NEW_DATA_FLAG 0x4000U
#define SDFM_FILTER_4_NEW_DATA_FLAG 0x8000U
Enumerations
enum SDFM_OutputThresholdStatus {
SDFM_OUTPUT_WITHIN_THRESHOLD = 0,
SDFM_OUTPUT_ABOVE_THRESHOLD = 1,
SDFM_OUTPUT_BELOW_THRESHOLD = 2
}
Values that can be returned from SDFM_getThresholdStatus()
enum SDFM_FilterNumber {
SDFM_FILTER_1 = 0,
SDFM_FILTER_2 = 1,
SDFM_FILTER_3 = 2,
SDFM_FILTER_4 = 3
}
enum SDFM_FilterType {
SDFM_FILTER_SINC_FAST = 0x00,
SDFM_FILTER_SINC_1 = 0x10,
SDFM_FILTER_SINC_2 = 0x20,
SDFM_FILTER_SINC_3 = 0x30
}
enum SDFM_ModulatorClockMode {
SDFM_MODULATOR_CLK_EQUAL_DATA_RATE = 0,
SDFM_MODULATOR_CLK_HALF_DATA_RATE = 1,
SDFM_MODULATOR_CLK_OFF = 2,
SDFM_MODULATOR_CLK_DOUBLE_DATA_RATE = 3
}
enum SDFM_OutputDataFormat {
SDFM_DATA_FORMAT_16_BIT = 0,
SDFM_DATA_FORMAT_32_BIT = 1
}
Functions
static void SDFM_enableExternalReset (uint32_t base, SDFM_FilterNumber filterNumber)
static void SDFM_disableExternalReset (uint32_t base, SDFM_FilterNumber filterNumber)
static void SDFM_enableFilter (uint32_t base, SDFM_FilterNumber filterNumber)
static void SDFM_disableFilter (uint32_t base, SDFM_FilterNumber filterNumber)
static void SDFM_setFilterType (uint32_t base, SDFM_FilterNumber filterNumber, SDFM_FilterType filterType)
static void SDFM_setFilterOverSamplingRatio (uint32_t base, SDFM_FilterNumber filterNumber, uint16_t overSamplingRatio)
static void SDFM_setupModulatorClock (uint32_t base, SDFM_FilterNumber filterNumber, SDFM_ModulatorClockMode clockMode)
static void SDFM_setOutputDataFormat (uint32_t base, SDFM_FilterNumber filterNumber, SDFM_OutputDataFormat dataFormat)
static void SDFM_setDataShiftValue (uint32_t base, SDFM_FilterNumber filterNumber, uint16_t shiftValue)
static void SDFM_setCompFilterHighThreshold (uint32_t base, SDFM_FilterNumber filterNumber, uint16_t highThreshold)
static void SDFM_setCompFilterLowThreshold (uint32_t base, SDFM_FilterNumber filterNumber, uint16_t lowThreshold)
static void SDFM_enableInterrupt (uint32_t base, SDFM_FilterNumber filterNumber, uint16_t intFlags)
static void SDFM_disableInterrupt (uint32_t base, SDFM_FilterNumber filterNumber, uint16_t intFlags)
static void SDFM_setComparatorFilterType (uint32_t base, SDFM_FilterNumber filterNumber, SDFM_FilterType filterType)
static void SDFM_setCompFilterOverSamplingRatio (uint32_t base, SDFM_FilterNumber filterNumber, uint16_t overSamplingRatio)
static uint32_t SDFM_getFilterData (uint32_t base, SDFM_FilterNumber filterNumber)
static SDFM_OutputThresholdStatus SDFM_getThresholdStatus (uint32_t base, SDFM_FilterNumber filterNumber)
static bool SDFM_getModulatorStatus (uint32_t base, SDFM_FilterNumber filterNumber)
static bool SDFM_getNewFilterDataStatus (uint32_t base, SDFM_FilterNumber filterNumber)
static bool SDFM_getIsrStatus (uint32_t base)
static void SDFM_clearInterruptFlag (uint32_t base, uint32_t flag)
static void SDFM_enableMasterInterrupt (uint32_t base)
static void SDFM_disableMasterInterrupt (uint32_t base)
static void SDFM_enableMasterFilter (uint32_t base)
static void SDFM_disableMasterFilter (uint32_t base)
void SDFM_configComparator (uint32_t base, uint16_t config1, uint32_t config2)
void SDFM_configDataFilter (uint32_t base, uint16_t config1, uint16_t config2)
Detailed Description
Macro Definition Documentation
#define SDFM_GET_LOW_THRESHOLD (C) ((uint16_t)(C))
Macro to get the low threshold
Referenced by SDFM_configComparator().
#define SDFM_GET_HIGH_THRESHOLD (C) ((uint16_t)((uint32_t)(C) >> 16U))
Macro to get the high threshold
Referenced by SDFM_configComparator().
#define SDFM_SET_OSR (X) (((X) - 1) << 8U)
Macro to convert comparator over sampling ratio to acceptable bit location
#define SDFM_SHIFT_VALUE (X) ((X) << 2U)
Macro to convert the data shift bit values to acceptable bit location
#define SDFM_THRESHOLD (H, L) ((((uint32_t)(H)) << 16U) | (L))
Macro to combine high threshold and low threshold values
#define SDFM_SET_FIFO_LEVEL (X) ((X) << 7U)
Macro to set the FIFO level to acceptable bit location
#define SDFM_SET_ZERO_CROSS_THRESH_VALUE (X) (0x8000 | (X))
Macro to set and enable the zero cross threshold value.
#define SDFM_FILTER_DISABLE 0x0U
Macros to enable or disable filter.
#define SDFM_FILTER_ENABLE 0x2U
Referenced by SDFM_configDataFilter().
#define SDFM_MODULATOR_FAILURE_INTERRUPT 0x200U
Interrupt is generated if Modulator fails.
Referenced by SDFM_disableInterrupt(), and SDFM_enableInterrupt().
#define SDFM_LOW_LEVEL_THRESHOLD_INTERRUPT 0x40U
Interrupt on Comparator low-level threshold.
Referenced by SDFM_disableInterrupt(), and SDFM_enableInterrupt().
#define SDFM_HIGH_LEVEL_THRESHOLD_INTERRUPT 0x20U
Interrupt on Comparator high-level threshold.
Referenced by SDFM_disableInterrupt(), and SDFM_enableInterrupt().
#define SDFM_DATA_FILTER_ACKNOWLEDGE_INTERRUPT 0x1U
Interrupt on Acknowledge flag
Referenced by SDFM_disableInterrupt(), and SDFM_enableInterrupt().
#define SDFM_MASTER_INTERRUPT_FLAG 0x80000000U
Master interrupt flag
#define SDFM_FILTER_1_HIGH_THRESHOLD_FLAG 0x1U
Filter 1 high -level threshold flag
#define SDFM_FILTER_1_LOW_THRESHOLD_FLAG 0x2U
Filter 1 low -level threshold flag
#define SDFM_FILTER_2_HIGH_THRESHOLD_FLAG 0x4U
Filter 2 high -level threshold flag
#define SDFM_FILTER_2_LOW_THRESHOLD_FLAG 0x8U
Filter 2 low -level threshold flag
#define SDFM_FILTER_3_HIGH_THRESHOLD_FLAG 0x10U
Filter 3 high -level threshold flag
#define SDFM_FILTER_3_LOW_THRESHOLD_FLAG 0x20U
Filter 3 low -level threshold flag
#define SDFM_FILTER_4_HIGH_THRESHOLD_FLAG 0x40U
Filter 4 high -level threshold flag
#define SDFM_FILTER_4_LOW_THRESHOLD_FLAG 0x80U
Filter 4 low -level threshold flag
#define SDFM_FILTER_1_MOD_FAILED_FLAG 0x100U
Filter 1 modulator failed flag
#define SDFM_FILTER_2_MOD_FAILED_FLAG 0x200U
Filter 2 modulator failed flag
#define SDFM_FILTER_3_MOD_FAILED_FLAG 0x400U
Filter 3 modulator failed flag
#define SDFM_FILTER_4_MOD_FAILED_FLAG 0x800U
Filter 4 modulator failed flag
#define SDFM_FILTER_1_NEW_DATA_FLAG 0x1000U
Filter 1 new data flag
#define SDFM_FILTER_2_NEW_DATA_FLAG 0x2000U
Filter 2 new data flag
#define SDFM_FILTER_3_NEW_DATA_FLAG 0x4000U
Filter 3 new data flag
#define SDFM_FILTER_4_NEW_DATA_FLAG 0x8000U
Filter 4 new data flag
Enumeration Type Documentation
enum SDFM_OutputThresholdStatus
Values that can be returned from SDFM_getThresholdStatus()
Enumerator
SDFM_OUTPUT_WITHIN_THRESHOLD
SDFM output is within threshold.
SDFM_OUTPUT_ABOVE_THRESHOLD
SDFM output is above threshold.
SDFM_OUTPUT_BELOW_THRESHOLD
SDFM output is below threshold.
enum SDFM_FilterNumber
Values that can be passed to all functions as the filterNumber parameter.
Enumerator
SDFM_FILTER_1
Digital filter 1.
SDFM_FILTER_2
Digital filter 2.
SDFM_FILTER_3
Digital filter 3.
SDFM_FILTER_4
Digital filter 4.
enum SDFM_FilterType
Values that can be passed to SDFM_setFilterType(), SDFM_setComparatorFilterType() as the filterType parameter.
Enumerator
SDFM_FILTER_SINC_FAST
Digital filter with SincFast structure.
SDFM_FILTER_SINC_1
Digital filter with Sinc1 structure.
SDFM_FILTER_SINC_2
Digital filter with Sinc3 structure.
SDFM_FILTER_SINC_3
Digital filter with Sinc4 structure.
enum SDFM_ModulatorClockMode
Values that can be passed to SDFM_setupModulatorClock(),as the clockMode parameter.
Enumerator
SDFM_MODULATOR_CLK_EQUAL_DATA_RATE
Modulator clock is identical to the data rate.
SDFM_MODULATOR_CLK_HALF_DATA_RATE
Modulator clock is half the data rate.
SDFM_MODULATOR_CLK_OFF
Modulator clock is off. Data is Manchester coded.
SDFM_MODULATOR_CLK_DOUBLE_DATA_RATE
Modulator clock is double the data rate.
enum SDFM_OutputDataFormat
Values that can be passed to SDFM_setOutputDataFormat(),as the dataFormat parameter.
Enumerator
SDFM_DATA_FORMAT_16_BIT
Filter output is in 16 bits 2's complement format.
SDFM_DATA_FORMAT_32_BIT
Filter output is in 32 bits 2's complement format.
Function Documentation
static void SDFM_enableExternalReset (uint32_t base, SDFM_FilterNumber filterNumber) inline static
Enable external reset
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
This function enables data filter to be reset by an external source (PWM compare output).
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDDFPARM1, and SDFM_SDDFPARM1_SDSYNCEN.
static void SDFM_disableExternalReset (uint32_t base, SDFM_FilterNumber filterNumber) inline static
Disable external reset
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
This function disables data filter from being reset by an external source (PWM compare output).
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDDFPARM1, and SDFM_SDDFPARM1_SDSYNCEN.
static void SDFM_enableFilter (uint32_t base, SDFM_FilterNumber filterNumber) inline static
Enable filter
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
This function enables the filter specified by the filterNumber variable.
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDDFPARM1, and SDFM_SDDFPARM1_FEN.
Referenced by SDFM_configDataFilter().
static void SDFM_disableFilter (uint32_t base, SDFM_FilterNumber filterNumber) inline static
Disable filter
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
This function disables the filter specified by the filterNumber variable.
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDDFPARM1, and SDFM_SDDFPARM1_FEN.
Referenced by SDFM_configDataFilter().
static void SDFM_setFilterType (uint32_t base, SDFM_FilterNumber filterNumber, SDFM_FilterType filterType) inline static
Set filter type.
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
filterType is the filter type or structure.
This function sets the filter type or structure to be used as specified by filterType for the selected filter number as specified by filterNumber.
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDDFPARM1, and SDFM_SDDFPARM1_SST_M.
Referenced by SDFM_configDataFilter().
static void SDFM_setFilterOverSamplingRatio (uint32_t base, SDFM_FilterNumber filterNumber, uint16_t overSamplingRatio) inline static
Set data filter over sampling ratio.
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
overSamplingRatio is the data filter over sampling ratio.
This function sets the filter oversampling ratio for the filter specified by the filterNumber variable.Valid values for the variable overSamplingRatio are 0 to 255 inclusive. The actual oversampling ratio will be this value plus one.
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDDFPARM1, and SDFM_SDDFPARM1_DOSR_M.
Referenced by SDFM_configDataFilter().
static void SDFM_setupModulatorClock (uint32_t base, SDFM_FilterNumber filterNumber, SDFM_ModulatorClockMode clockMode) inline static
Set modulator clock mode.
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
clockMode is the modulator clock mode.
This function sets the modulator clock mode specified by clockMode for the filter specified by filterNumber.
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDCTLPARM1, and SDFM_SDCTLPARM1_MOD_M.
static void SDFM_setOutputDataFormat (uint32_t base, SDFM_FilterNumber filterNumber, SDFM_OutputDataFormat dataFormat) inline static
Set the output data format
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
dataFormat is the output data format.
This function sets the output data format for the filter specified by filterNumber.
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDDPARM1, and SDFM_SDDPARM1_DR.
Referenced by SDFM_configDataFilter().
static void SDFM_setDataShiftValue (uint32_t base, SDFM_FilterNumber filterNumber, uint16_t shiftValue) inline static
Set data shift value.
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
shiftValue is the data shift value.
This function sets the shift value for the 16 bit 2's complement data format. The valid maximum value for shiftValue is 31.
Note: Use this function with 16 bit 2's complement data format only.
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDDPARM1, SDFM_SDDPARM1_SH_M, and SDFM_SDDPARM1_SH_S.
Referenced by SDFM_configDataFilter().
static void SDFM_setCompFilterHighThreshold (uint32_t base, SDFM_FilterNumber filterNumber, uint16_t highThreshold) inline static
Set Filter output high-level threshold.
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
highThreshold is the high-level threshold.
This function sets the unsigned high-level threshold value for the Comparator filter output. If the output value of the filter exceeds highThreshold and interrupt generation is enabled, an interrupt will be issued.
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDCMPH1, and SDFM_SDCMPH1_HLT_M.
Referenced by SDFM_configComparator().
static void SDFM_setCompFilterLowThreshold (uint32_t base, SDFM_FilterNumber filterNumber, uint16_t lowThreshold) inline static
Set Filter output low-level threshold.
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
lowThreshold is the low-level threshold.
This function sets the unsigned low-level threshold value for the Comparator filter output. If the output value of the filter gets below lowThreshold and interrupt generation is enabled, an interrupt will be issued.
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDCMPL1, and SDFM_SDCMPL1_LLT_M.
Referenced by SDFM_configComparator().
static void SDFM_enableInterrupt (uint32_t base, SDFM_FilterNumber filterNumber, uint16_t intFlags) inline static
Enable SDFM interrupts.
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
intFlags is the interrupt source.
This function enables the low threshold , high threshold or modulator failure interrupt as determined by intFlags for the filter specified by filterNumber. Valid values for intFlags are: SDFM_MODULATOR_FAILURE_INTERRUPT , SDFM_LOW_LEVEL_THRESHOLD_INTERRUPT, SDFM_HIGH_LEVEL_THRESHOLD_INTERRUPT,SDFM_DATA_FILTER_ACKNOWLEDGE_INTERRUPT
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_DATA_FILTER_ACKNOWLEDGE_INTERRUPT, SDFM_HIGH_LEVEL_THRESHOLD_INTERRUPT, SDFM_LOW_LEVEL_THRESHOLD_INTERRUPT, SDFM_MODULATOR_FAILURE_INTERRUPT, SDFM_O_SDCPARM1, SDFM_O_SDDFPARM1, and SDFM_SDDFPARM1_AE.
static void SDFM_disableInterrupt (uint32_t base, SDFM_FilterNumber filterNumber, uint16_t intFlags) inline static
Disable SDFM interrupts.
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
intFlags is the interrupt source.
This function disables the low threshold , high threshold or modulator failure interrupt as determined by intFlags for the filter specified by filterNumber. Valid values for intFlags are: SDFM_MODULATOR_FAILURE_INTERRUPT , SDFM_LOW_LEVEL_THRESHOLD_INTERRUPT, SDFM_HIGH_LEVEL_THRESHOLD_INTERRUPT,SDFM_DATA_FILTER_ACKNOWLEDGE_INTERRUPT
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_DATA_FILTER_ACKNOWLEDGE_INTERRUPT, SDFM_HIGH_LEVEL_THRESHOLD_INTERRUPT, SDFM_LOW_LEVEL_THRESHOLD_INTERRUPT, SDFM_MODULATOR_FAILURE_INTERRUPT, SDFM_O_SDCPARM1, SDFM_O_SDDFPARM1, and SDFM_SDDFPARM1_AE.
static void SDFM_setComparatorFilterType (uint32_t base, SDFM_FilterNumber filterNumber, SDFM_FilterType filterType) inline static
Set the comparator filter type.
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
filterType is the comparator filter type or structure.
This function sets the Comparator filter type or structure to be used as specified by filterType for the selected filter number as specified by filterNumber.
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDCPARM1, and SDFM_SDCPARM1_CS1_CS0_M.
Referenced by SDFM_configComparator().
static void SDFM_setCompFilterOverSamplingRatio (uint32_t base, SDFM_FilterNumber filterNumber, uint16_t overSamplingRatio) inline static
Set Comparator filter over sampling ratio.
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
overSamplingRatio is the comparator filter over sampling ration.
This function sets the comparator filter oversampling ratio for the filter specified by the filterNumber.Valid values for the variable overSamplingRatio are 0 to 31 inclusive. The actual oversampling ratio will be this value plus one.
Returns
None.
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDCPARM1, and SDFM_SDCPARM1_COSR_M.
Referenced by SDFM_configComparator().
static uint32_t SDFM_getFilterData (uint32_t base, SDFM_FilterNumber filterNumber) inline static
Get the filter data output.
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
This function returns the latest data filter output. Depending on the filter data output format selected, the valid value will be the lower 16 bits or the whole 32 bits of the returned value.
Returns
Returns the latest data filter output.
References ASSERT, HWREG, and SDFM_O_SDDATA1.
static SDFM_OutputThresholdStatus SDFM_getThresholdStatus (uint32_t base, SDFM_FilterNumber filterNumber) inline static
Get the Comparator threshold status.
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
This function returns the Comparator output threshold status for the given filterNumber.
Returns
Returns the following status flags.
SDFM_OUTPUT_WITHIN_THRESHOLD if the output is within the specified threshold.
SDFM_OUTPUT_ABOVE_THRESHOLD if the output is above the high threshold
SDFM_OUTPUT_BELOW_THRESHOLD if the output is below the low threshold.
References ASSERT, HWREG, and SDFM_O_SDIFLG.
static bool SDFM_getModulatorStatus (uint32_t base, SDFM_FilterNumber filterNumber) inline static
Get the Modulator status.
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
This function returns the Modulator status.
Returns
Returns true if the Modulator is operating normally Returns false if the Modulator has failed
References ASSERT, HWREG, and SDFM_O_SDIFLG.
static bool SDFM_getNewFilterDataStatus (uint32_t base, SDFM_FilterNumber filterNumber) inline static
Check if new Filter data is available.
Parameters
base is the base address of the SDFM module
filterNumber is the filter number.
This function returns new filter data status.
Returns
Returns true if new filter data is available Returns false if no new filter data is available
References ASSERT, HWREG, and SDFM_O_SDIFLG.
static bool SDFM_getIsrStatus (uint32_t base) inline static
Get pending interrupt.
Parameters
base is the base address of the SDFM module
This function returns any pending interrupt status.
Returns
Returns true if there is a pending interrupt. Returns false if no interrupt is pending.
References ASSERT, HWREG, and SDFM_O_SDIFLG.
static void SDFM_clearInterruptFlag (uint32_t base, uint32_t flag) inline static
Clear pending flags.
Parameters
base is the base address of the SDFM module
flag is the SDFM status
This function clears the specified pending interrupt flag. Valid values are SDFM_MASTER_INTERRUPT_FLAG,SDFM_FILTER_1_NEW_DATA_FLAG, SDFM_FILTER_2_NEW_DATA_FLAG,SDFM_FILTER_3_NEW_DATA_FLAG, SDFM_FILTER_4_NEW_DATA_FLAG,SDFM_FILTER_1_MOD_FAILED_FLAG, SDFM_FILTER_2_MOD_FAILED_FLAG,SDFM_FILTER_3_MOD_FAILED_FLAG, SDFM_FILTER_4_MOD_FAILED_FLAG,SDFM_FILTER_1_HIGH_THRESHOLD_FLAG, SDFM_FILTER_1_LOW_THRESHOLD_FLAG,SDFM_FILTER_2_HIGH_THRESHOLD_FLAG, SDFM_FILTER_2_LOW_THRESHOLD_FLAG,SDFM_FILTER_3_HIGH_THRESHOLD_FLAG, SDFM_FILTER_3_LOW_THRESHOLD_FLAG,SDFM_FILTER_4_HIGH_THRESHOLD_FLAG, SDFM_FILTER_4_LOW_THRESHOLD_FLAG or any combination of the above flags.
Returns
None
References ASSERT, HWREG, and SDFM_O_SDIFLGCLR.
static void SDFM_enableMasterInterrupt (uint32_t base) inline static
Enable master interrupt.
Parameters
base is the base address of the SDFM module
This function enables the master SDFM interrupt.
Returns
None
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDCTL, and SDFM_SDCTL_MIE.
static void SDFM_disableMasterInterrupt (uint32_t base) inline static
Disable master interrupt.
Parameters
base is the base address of the SDFM module
This function disables the master SDFM interrupt.
Returns
None
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDCTL, and SDFM_SDCTL_MIE.
static void SDFM_enableMasterFilter (uint32_t base) inline static
Enable master interrupt.
Parameters
base is the base address of the SDFM module
This function enables master filter.
Returns
None
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDMFILEN, and SDFM_SDMFILEN_MFE.
static void SDFM_disableMasterFilter (uint32_t base) inline static
Disable master filter.
Parameters
base is the base address of the SDFM module
This function disables master filter.
Returns
None
References ASSERT, EALLOW, EDIS, HWREGH, SDFM_O_SDMFILEN, and SDFM_SDMFILEN_MFE.
void SDFM_configComparator (uint32_t base, uint16_t config1, uint32_t config2)
Configure SDFM comparator high and low thresholds
Parameters
base is the base address of the SDFM module
config1 is the filter number, filter type and over sampling ratio.
config2 is high-level and low-level threshold values.
This function configures the comparator filter threshold values based on configurations config1 and config2.
The config1 parameter is the logical OR of the filter number, filter type and oversampling ratio. The bit definitions for config1 are as follow:
config1.[3:0] filter number
config1.[7:4] filter type
config1.[15:8] Over sampling Ratio Valid values for filter number and filter type are defined in SDFM_FilterNumber and SDFM_FilterType enumerations respectively. SDFM_SET_OSR(X) macro can be used to set the value of the oversampling ratio ,which ranges [1,32] inclusive, in the appropriate bit location. For example the value (SDFM_FILTER_1 | SDFM_FILTER_SINC_2 | SDFM_SET_OSR(16)) will select Filter 1, SINC 2 type with an oversampling ratio of 16.
The config2 parameter is the logical OR of the filter high and low threshold values. The bit definitions for config2 are as follow:
config2.[15:0] low threshold
config2.[31:16] high threshold The upper 16 bits define the high threshold and the lower 16 bits define the low threshold. SDFM_THRESHOLD(H,L) can be used to combine the high and low thresholds.
Returns
None.
References SDFM_GET_FILTER_NUMBER, SDFM_GET_FILTER_TYPE, SDFM_GET_HIGH_THRESHOLD, SDFM_GET_LOW_THRESHOLD, SDFM_GET_OSR, SDFM_MAX_COMP_FILTER_OSR, SDFM_setComparatorFilterType(), SDFM_setCompFilterHighThreshold(), SDFM_setCompFilterLowThreshold(), and SDFM_setCompFilterOverSamplingRatio().
void SDFM_configDataFilter (uint32_t base, uint16_t config1, uint16_t config2)
Configure SDFM data filter
Parameters
base is the base address of the SDFM module
config1 is the filter number, filter type and over sampling ratio configuration.
config2 is filter switch, data representation and data shift values configuration.
This function configures the data filter based on configurations config1 and config2.
The config1 parameter is the logical OR of the filter number, filter type and oversampling ratio. The bit definitions for config1 are as follow:
config1.[3:0] Filter number
config1.[7:4] Filter type
config1.[15:8] Over sampling Ratio Valid values for filter number and filter type are defined in SDFM_FilterNumber and SDFM_FilterType enumerations respectively. SDFM_SET_OSR(X) macro can be used to set the value of the oversampling ratio , which ranges [1,256] inclusive , in the appropriate bit location for config1. For example the value (SDFM_FILTER_2 | SDFM_FILTER_SINC_3 | SDFM_SET_OSR(64)) will select Filter 2 , SINC 3 type with an oversampling ratio of 64.
The config2 parameter is the logical OR of data representation, filter switch, and data shift values The bit definitions for config2 are as follow:
config2.[0] Data representation
config2.[1] Filter switch
config2.[15:2] Shift values Valid values for data representation are given in SDFM_OutputDataFormat enumeration. SDFM_FILTER_DISABLE or SDFM_FILTER_ENABLE will define the filter switch values.SDFM_SHIFT_VALUE(X) macro can be used to set the value of the data shift value,which ranges [0,31] inclusive, in the appropriate bit location for config2. The shift value is valid only in SDFM_DATA_FORMAT_16_BIT data representation format.
Returns
None.
References SDFM_DATA_FORMAT_16_BIT, SDFM_disableFilter(), SDFM_enableFilter(), SDFM_FILTER_ENABLE, SDFM_GET_FILTER_NUMBER, SDFM_GET_FILTER_TYPE, SDFM_GET_OSR, SDFM_GET_SHIFT_VALUE, SDFM_MAX_DATA_FILTER_OSR, SDFM_setDataShiftValue(), SDFM_setFilterOverSamplingRatio(), SDFM_setFilterType(), and SDFM_setOutputDataFormat().
Copyright 2018, Texas Instruments Incorporated