DCSM
DCSM
Data Structures
struct DCSM_CSMPasswordKey
Data structures to hold password keys.
Macros
#define DCSM_O_Z1_CSMPSWD0 0x08U
Z1 CSMPSWD0 offset.
#define DCSM_O_Z1_CSMPSWD1 0x0AU
Z1 CSMPSWD1 offset.
#define DCSM_O_Z1_CSMPSWD2 0x0CU
Z1 CSMPSWD2 offset.
#define DCSM_O_Z1_CSMPSWD3 0x0EU
Z1 CSMPSWD3 offset.
#define DCSM_O_Z2_CSMPSWD0 0x08U
Z2 CSMPSWD0 offset.
#define DCSM_O_Z2_CSMPSWD1 0x0AU
Z2 CSMPSWD1 offset.
#define DCSM_O_Z2_CSMPSWD2 0x0CU
Z2 CSMPSWD2 offset.
#define DCSM_O_Z2_CSMPSWD3 0x0EU
Z2 CSMPSWD3 offset.
#define FLSEM_KEY 0xA5U
Zone semaphore key.
#define DCSM_ALLZERO 0x08U
CSM Passwords all zeros.
#define DCSM_ALLONE 0x10U
CSM Passwords all ones.
#define DCSM_UNSECURE 0x20U
Zone is secure/unsecure.
#define DCSM_ARMED 0x40U
CSM is armed.
#define DCSM_FLSEM_ALLACCESS_1 0x00000000
No restriction.
#define DCSM_FLSEM_Z1ACCESS 0x00000001
Zone 1 Access.
#define DCSM_FLSEM_Z2ACCESS 0x00000002
Zone 2 Access.
#define DCSM_FLSEM_ALLACCESS_2 0x00000003
No restriction.
Enumerations
enum DCSM_MemoryStatus {
DCSM_MEMORY_INACCESSIBLE,
DCSM_MEMORY_ZONE1,
DCSM_MEMORY_ZONE2,
DCSM_MEMORY_FULL_ACCESS
}
enum DCSM_SemaphoreZone {
DCSM_FLSEM_ZONE1 = 0x01U,
DCSM_FLSEM_ZONE2 = 0x02U
}
enum DCSM_SecurityStatus {
DCSM_STATUS_SECURE,
DCSM_STATUS_UNSECURE,
DCSM_STATUS_LOCKED
}
enum DCSM_EXEOnlyStatus {
DCSM_PROTECTED,
DCSM_UNPROTECTED,
DCSM_INCORRECT_ZONE
}
enum DCSM_RAMModule {
DCSM_RAMLS0,
DCSM_RAMLS1,
DCSM_RAMLS2,
DCSM_RAMLS3,
DCSM_RAMLS4,
DCSM_RAMLS5,
DCSM_RAMD0,
DCSM_RAMD1,
DCSM_CLA = 14U
}
enum DCSM_Sector {
DCSM_SECTOR_A,
DCSM_SECTOR_B,
DCSM_SECTOR_C,
DCSM_SECTOR_D,
DCSM_SECTOR_E,
DCSM_SECTOR_F,
DCSM_SECTOR_G,
DCSM_SECTOR_H,
DCSM_SECTOR_I,
DCSM_SECTOR_J,
DCSM_SECTOR_K,
DCSM_SECTOR_L,
DCSM_SECTOR_M,
DCSM_SECTOR_N
}
Functions
static void DCSM_secureZone1 (void)
static void DCSM_secureZone2 (void)
static DCSM_SecurityStatus DCSM_getZone1CSMSecurityStatus (void)
static DCSM_SecurityStatus DCSM_getZone2CSMSecurityStatus (void)
static uint16_t DCSM_getZone1ControlStatus (void)
static uint16_t DCSM_getZone2ControlStatus (void)
static DCSM_MemoryStatus DCSM_getRAMZone (DCSM_RAMModule module)
static DCSM_MemoryStatus DCSM_getFlashSectorZone (DCSM_Sector sector)
static uint32_t DCSM_getZone1LinkPointerError (void)
static uint32_t DCSM_getZone2LinkPointerError (void)
void DCSM_unlockZone1CSM (const DCSM_CSMPasswordKey *const psCMDKey)
void DCSM_unlockZone2CSM (const DCSM_CSMPasswordKey *const psCMDKey)
DCSM_EXEOnlyStatus DCSM_getZone1FlashEXEStatus (DCSM_Sector sector)
DCSM_EXEOnlyStatus DCSM_getZone1RAMEXEStatus (DCSM_RAMModule module)
DCSM_EXEOnlyStatus DCSM_getZone2FlashEXEStatus (DCSM_Sector sector)
DCSM_EXEOnlyStatus DCSM_getZone2RAMEXEStatus (DCSM_RAMModule module)
bool DCSM_claimZoneSemaphore (DCSM_SemaphoreZone zone)
bool DCSM_releaseZoneSemaphore (void)
Detailed Description
Macro Definition Documentation
#define DCSM_O_Z1_CSMPSWD0 0x08U
Z1 CSMPSWD0 offset.
Referenced by DCSM_unlockZone1CSM().
#define DCSM_O_Z1_CSMPSWD1 0x0AU
Z1 CSMPSWD1 offset.
Referenced by DCSM_unlockZone1CSM().
#define DCSM_O_Z1_CSMPSWD2 0x0CU
Z1 CSMPSWD2 offset.
Referenced by DCSM_unlockZone1CSM().
#define DCSM_O_Z1_CSMPSWD3 0x0EU
Z1 CSMPSWD3 offset.
Referenced by DCSM_unlockZone1CSM().
#define DCSM_O_Z2_CSMPSWD0 0x08U
Z2 CSMPSWD0 offset.
Referenced by DCSM_unlockZone2CSM().
#define DCSM_O_Z2_CSMPSWD1 0x0AU
Z2 CSMPSWD1 offset.
Referenced by DCSM_unlockZone2CSM().
#define DCSM_O_Z2_CSMPSWD2 0x0CU
Z2 CSMPSWD2 offset.
Referenced by DCSM_unlockZone2CSM().
#define DCSM_O_Z2_CSMPSWD3 0x0EU
Z2 CSMPSWD3 offset.
Referenced by DCSM_unlockZone2CSM().
#define FLSEM_KEY 0xA5U
Zone semaphore key.
Referenced by DCSM_claimZoneSemaphore(), and DCSM_releaseZoneSemaphore().
#define DCSM_ALLZERO 0x08U
CSM Passwords all zeros.
#define DCSM_ALLONE 0x10U
CSM Passwords all ones.
#define DCSM_UNSECURE 0x20U
Zone is secure/unsecure.
#define DCSM_ARMED 0x40U
CSM is armed.
#define DCSM_FLSEM_ALLACCESS_1 0x00000000
No restriction.
#define DCSM_FLSEM_Z1ACCESS 0x00000001
Zone 1 Access.
#define DCSM_FLSEM_Z2ACCESS 0x00000002
Zone 2 Access.
#define DCSM_FLSEM_ALLACCESS_2 0x00000003
No restriction.
Enumeration Type Documentation
enum DCSM_MemoryStatus
Values to distinguish the status of RAM or FLASH sectors. These values describe which zone the memory location belongs too. These values can be returned from DCSM_getRAMZone(), DCSM_getFlashSectorZone().
Enumerator
DCSM_MEMORY_INACCESSIBLE
Inaccessible.
DCSM_MEMORY_ZONE1
Zone 1.
DCSM_MEMORY_ZONE2
Zone 2.
DCSM_MEMORY_FULL_ACCESS
Full access.
enum DCSM_SemaphoreZone
Values to pass to DCSM_claimZoneSemaphore(). These values are used to describe the zone that can write to Flash Wrapper registers.
Enumerator
DCSM_FLSEM_ZONE1
Flash semaphore Zone 1.
DCSM_FLSEM_ZONE2
Flash semaphore Zone 2.
enum DCSM_SecurityStatus
Values to distinguish the security status of the zones. These values can be returned from DCSM_getZone1CSMSecurityStatus(), DCSM_getZone2CSMSecurityStatus().
Enumerator
DCSM_STATUS_SECURE
Secure.
DCSM_STATUS_UNSECURE
Unsecure.
DCSM_STATUS_LOCKED
Locked.
enum DCSM_EXEOnlyStatus
Values to decribe the EXEONLY Status. These values are returned from to DCSM_getZone1RAMEXEStatus(), DCSM_getZone2RAMEXEStatus(), DCSM_getZone1FlashEXEStatus(), DCSM_getZone2FlashEXEStatus().
Enumerator
DCSM_PROTECTED
Protected.
DCSM_UNPROTECTED
Unprotected.
DCSM_INCORRECT_ZONE
Incorrect Zone.
enum DCSM_RAMModule
Values to distinguish RAM Module. These values can be passed to DCSM_getZone1RAMEXEStatus() DCSM_getZone2RAMEXEStatus(), DCSM_getRAMZone().
Enumerator
DCSM_RAMLS0
RAMLS0.
DCSM_RAMLS1
RAMLS1.
DCSM_RAMLS2
RAMLS2.
DCSM_RAMLS3
RAMLS3.
DCSM_RAMLS4
RAMLS4.
DCSM_RAMLS5
RAMLS5.
DCSM_RAMD0
RAMD0.
DCSM_RAMD1
RAMD1.
DCSM_CLA
Offset of CLA field in in RAMSTAT divided by two.
enum DCSM_Sector
Values to distinguish Flash Sector. These values can be passed to DCSM_getZone1FlashEXEStatus() DCSM_getZone2FlashEXEStatus(), DCSM_getFlashSectorZone().
Enumerator
DCSM_SECTOR_A
Sector A.
DCSM_SECTOR_B
Sector B.
DCSM_SECTOR_C
Sector C.
DCSM_SECTOR_D
Sector D.
DCSM_SECTOR_E
Sector E.
DCSM_SECTOR_F
Sector F.
DCSM_SECTOR_G
Sector G.
DCSM_SECTOR_H
Sector H.
DCSM_SECTOR_I
Sector I.
DCSM_SECTOR_J
Sector J.
DCSM_SECTOR_K
Sector K.
DCSM_SECTOR_L
Sector L.
DCSM_SECTOR_M
Sector M.
DCSM_SECTOR_N
Sector N.
Function Documentation
static void DCSM_secureZone1 (void) inline static
Secures zone 1 by setting the FORCESEC bit of Z1_CR register
This function resets the state of the zone. If the zone is unlocked, it will lock(secure) the zone and also reset all the bits in the Control Register.
Returns
None.
References DCSM_O_Z1_CR, DCSM_Z1_BASE, DCSM_Z1_CR_FORCESEC, and HWREGH.
static void DCSM_secureZone2 (void) inline static
Secures zone 2 by setting the FORCESEC bit of Z2_CR register
This function resets the state of the zone. If the zone is unlocked, it will lock(secure) the zone and also reset all the bits in the Control Register.
Returns
None.
References DCSM_O_Z2_CR, DCSM_Z2_BASE, DCSM_Z2_CR_FORCESEC, and HWREGH.
static DCSM_SecurityStatus DCSM_getZone1CSMSecurityStatus (void) inline static
Returns the CSM security status of zone 1
This function returns the security status of zone 1 CSM
Returns
Returns security status as an enumerated type DCSM_SecurityStatus.
References DCSM_O_Z1_CR, DCSM_STATUS_LOCKED, DCSM_STATUS_SECURE, DCSM_STATUS_UNSECURE, DCSM_Z1_BASE, DCSM_Z1_CR_ALLONE, DCSM_Z1_CR_ALLZERO, DCSM_Z1_CR_ARMED, DCSM_Z1_CR_UNSECURE, and HWREGH.
static DCSM_SecurityStatus DCSM_getZone2CSMSecurityStatus (void) inline static
Returns the CSM security status of zone 2
This function returns the security status of zone 2 CSM
Returns
Returns security status as an enumerated type DCSM_SecurityStatus.
References DCSM_O_Z2_CR, DCSM_STATUS_LOCKED, DCSM_STATUS_SECURE, DCSM_STATUS_UNSECURE, DCSM_Z2_BASE, DCSM_Z2_CR_ALLONE, DCSM_Z2_CR_ALLZERO, DCSM_Z2_CR_ARMED, DCSM_Z2_CR_UNSECURE, and HWREGH.
static uint16_t DCSM_getZone1ControlStatus (void) inline static
Returns the Control Status of zone 1
This function returns the Control Status of zone 1 CSM
Returns
Returns the contents of the Control Register which can be used with provided defines.
References DCSM_O_Z1_CR, DCSM_Z1_BASE, and HWREGH.
static uint16_t DCSM_getZone2ControlStatus (void) inline static
Returns the Control Status of zone 2
This function returns the Control Status of zone 2 CSM
Returns
Returns the contents of the Control Register which can be used with the provided defines.
References DCSM_O_Z2_CR, DCSM_Z2_BASE, and HWREGH.
static DCSM_MemoryStatus DCSM_getRAMZone (DCSM_RAMModule module) inline static
Returns the security zone a RAM section belongs to
Parameters
module is the RAM module value. Valid values are type DCSM_RAMModule
DCSM_RAMLS0
DCSM_RAMLS1
DCSM_RAMLS2
DCSM_RAMLS3
DCSM_RAMLS4
DCSM_RAMLS5
DCSM_RAMD0
DCSM_RAMD1
DCSM_CLA
This function returns the security zone a RAM section belongs to.
Returns
Returns DCSM_MEMORY_INACCESSIBLE if the section is inaccessible, DCSM_MEMORY_ZONE1 if the section belongs to zone 1, DCSM_MEMORY_ZONE2 if the section belongs to zone 2 and DCSM_MEMORY_FULL_ACCESS if the section doesn't belong to any zone (or if the section is unsecure).
References DCSM_O_RAMSTAT, DCSMCOMMON_BASE, and HWREG.
Referenced by DCSM_getZone1RAMEXEStatus(), and DCSM_getZone2RAMEXEStatus().
static DCSM_MemoryStatus DCSM_getFlashSectorZone (DCSM_Sector sector) inline static
Returns the security zone a flash sector belongs to
Parameters
sector is the flash sector value. Use DCSM_Sector type.
This function returns the security zone a flash sector belongs to.
Returns
Returns DCSM_MEMORY_INACCESSIBLE if the section is inaccessible , DCSM_MEMORY_ZONE1 if the section belongs to zone 1, DCSM_MEMORY_ZONE2 if the section belongs to zone 2 and DCSM_MEMORY_FULL_ACCESS if the section doesn't belong to any zone (or if the section is unsecure)..
References DCSM_O_SECTSTAT, DCSMCOMMON_BASE, and HWREG.
Referenced by DCSM_getZone1FlashEXEStatus(), and DCSM_getZone2FlashEXEStatus().
static uint32_t DCSM_getZone1LinkPointerError (void) inline static
Read Zone 1 Link Pointer Error
A non-zero value indicates an error on the bit position that is set to 1.
Returns
Returns the value of the Zone 1 Link Pointer error.
References DCSM_O_Z1_LINKPOINTERERR, DCSM_Z1_BASE, and HWREG.
static uint32_t DCSM_getZone2LinkPointerError (void) inline static
Read Zone 2 Link Pointer Error
A non-zero value indicates an error on the bit position that is set to 1.
Returns
Returns the value of the Zone 2 Link Pointer error.
References DCSM_O_Z2_LINKPOINTERERR, DCSM_Z2_BASE, and HWREG.
void DCSM_unlockZone1CSM (const DCSM_CSMPasswordKey *const psCMDKey)
Unlocks Zone 1 CSM.
Parameters
psCMDKey is a pointer to the DCSM_CSMPasswordKey struct that has the CSM password for zone 1.
This function unlocks the CSM password. It first reads the four password locations in the User OTP. If any of the password values is different from 0xFFFFFFFF, it unlocks the device by writing the provided passwords into CSM Key registers
Returns
None.
References DCSM_CSMPasswordKey::csmKey0, DCSM_CSMPasswordKey::csmKey1, DCSM_CSMPasswordKey::csmKey2, DCSM_CSMPasswordKey::csmKey3, DCSM_O_Z1_CSMKEY0, DCSM_O_Z1_CSMKEY1, DCSM_O_Z1_CSMKEY2, DCSM_O_Z1_CSMKEY3, DCSM_O_Z1_CSMPSWD0, DCSM_O_Z1_CSMPSWD1, DCSM_O_Z1_CSMPSWD2, DCSM_O_Z1_CSMPSWD3, DCSM_O_Z1_LINKPOINTER, DCSM_Z1_BASE, DCSM_Z1OTP_BASE, and HWREG.
void DCSM_unlockZone2CSM (const DCSM_CSMPasswordKey *const psCMDKey)
Unlocks Zone 2 CSM.
Parameters
psCMDKey is a pointer to the CSMPSWDKEY that has the CSM password for zone 2.
This function unlocks the CSM password. It first reads the four password locations in the User OTP. If any of the password values is different from 0xFFFFFFFF, it unlocks the device by writing the provided passwords into CSM Key registers
Returns
None.
References DCSM_CSMPasswordKey::csmKey0, DCSM_CSMPasswordKey::csmKey1, DCSM_CSMPasswordKey::csmKey2, DCSM_CSMPasswordKey::csmKey3, DCSM_O_Z2_CSMKEY0, DCSM_O_Z2_CSMKEY1, DCSM_O_Z2_CSMKEY2, DCSM_O_Z2_CSMKEY3, DCSM_O_Z2_CSMPSWD0, DCSM_O_Z2_CSMPSWD1, DCSM_O_Z2_CSMPSWD2, DCSM_O_Z2_CSMPSWD3, DCSM_O_Z2_LINKPOINTER, DCSM_Z2_BASE, DCSM_Z2OTP_BASE, and HWREG.
DCSM_EXEOnlyStatus DCSM_getZone1FlashEXEStatus (DCSM_Sector sector)
Returns the EXE-ONLY status of zone 1 for a flash sector
Parameters
sector is the flash sector value. Use DCSM_Sector type.
This function takes in a valid sector value and returns the status of EXE ONLY security protection for the sector.
Returns
Returns DCSM_PROTECTED if the sector is EXE-ONLY protected, DCSM_UNPROTECTED if the sector is not EXE-ONLY protected, DCSM_INCORRECT_ZONE if sector does not belong to this zone.
References DCSM_getFlashSectorZone(), DCSM_INCORRECT_ZONE, DCSM_MEMORY_ZONE1, DCSM_O_Z1_EXEONLYSECTR, DCSM_Z1_BASE, and HWREGH.
DCSM_EXEOnlyStatus DCSM_getZone1RAMEXEStatus (DCSM_RAMModule module)
Returns the EXE-ONLY status of zone 1 for a RAM module
Parameters
module is the RAM module value. Valid values are type DCSM_RAMModule
DCSM_RAMLS0
DCSM_RAMLS1
DCSM_RAMLS2
DCSM_RAMLS3
DCSM_RAMLS4
DCSM_RAMLS5
DCSM_RAMD0
DCSM_RAMD1
This function takes in a valid module value and returns the status of EXE ONLY security protection for that module. DCSM_CLA is an invalid module value. There is no EXE-ONLY available for DCSM_CLA.
Returns
Returns DCSM_PROTECTED if the module is EXE-ONLY protected, DCSM_UNPROTECTED if the module is not EXE-ONLY protected, DCSM_INCORRECT_ZONE if module does not belong to this zone.
References ASSERT, DCSM_CLA, DCSM_getRAMZone(), DCSM_INCORRECT_ZONE, DCSM_MEMORY_ZONE1, DCSM_O_Z1_EXEONLYRAMR, DCSM_Z1_BASE, and HWREGH.
DCSM_EXEOnlyStatus DCSM_getZone2FlashEXEStatus (DCSM_Sector sector)
Returns the EXE-ONLY status of zone 2 for a flash sector
Parameters
sector is the flash sector value. Use DCSM_Sector type.
This function takes in a valid sector value and returns the status of EXE ONLY security protection for the sector.
Returns
Returns DCSM_PROTECTED if the sector is EXE-ONLY protected, DCSM_UNPROTECTED if the sector is not EXE-ONLY protected, DCSM_INCORRECT_ZONE if sector does not belong to this zone.
References DCSM_getFlashSectorZone(), DCSM_INCORRECT_ZONE, DCSM_MEMORY_ZONE2, DCSM_O_Z2_EXEONLYSECTR, DCSM_Z2_BASE, and HWREGH.
DCSM_EXEOnlyStatus DCSM_getZone2RAMEXEStatus (DCSM_RAMModule module)
Returns the EXE-ONLY status of zone 2 for a RAM module
Parameters
module is the RAM module value. Valid values are type DCSM_RAMModule
DCSM_RAMLS0
DCSM_RAMLS1
DCSM_RAMLS2
DCSM_RAMLS3
DCSM_RAMLS4
DCSM_RAMLS5
DCSM_RAMD0
DCSM_RAMD1
This function takes in a valid module value and returns the status of EXE ONLY security protection for that module. DCSM_CLA is an invalid module value. There is no EXE-ONLY available for DCSM_CLA.
Returns
Returns DCSM_PROTECTED if the module is EXE-ONLY protected, DCSM_UNPROTECTED if the module is not EXE-ONLY protected, DCSM_INCORRECT_ZONE if module does not belong to this zone.
References ASSERT, DCSM_CLA, DCSM_getRAMZone(), DCSM_INCORRECT_ZONE, DCSM_MEMORY_ZONE2, DCSM_O_Z2_EXEONLYRAMR, DCSM_Z2_BASE, and HWREGH.
bool DCSM_claimZoneSemaphore (DCSM_SemaphoreZone zone)
Claims the zone semaphore which allows access to the Flash Wrapper register for that zone.
Parameters
zone is the zone which is trying to claim the semaphore which allows access to the Flash Wrapper registers.
Returns
Returns true for a successful semaphore capture, false if it was unable to capture the semaphore.
References DCSM_FLSEM_KEY_S, DCSM_FLSEM_SEM_M, DCSM_O_FLSEM, DCSMCOMMON_BASE, EALLOW, EDIS, FLSEM_KEY, and HWREGH.
bool DCSM_releaseZoneSemaphore (void)
Releases the zone semaphore.
Returns
Returns true if it was successful in releasing the zone semaphore and false if it was unsuccessful in releasing the zone semaphore.
Note
If the calling function is not in the right zone to be able to access this register, it will return a false.
References DCSM_FLSEM_KEY_S, DCSM_FLSEM_SEM_M, DCSM_O_FLSEM, DCSMCOMMON_BASE, EALLOW, EDIS, FLSEM_KEY, and HWREGH.
Copyright 2018, Texas Instruments Incorporated