McBSP
McBSP
Data Structures
struct McBSP_ClockParams
struct McBSP_TxFsyncParams
struct McBSP_RxFsyncParams
struct McBSP_TxDataParams
struct McBSP_RxDataParams
struct McBSP_RxMultichannelParams
struct McBSP_TxMultichannelParams
struct McBSP_SPIMasterModeParams
struct McBSP_SPISlaveModeParams
Macros
#define MCBSP_XCR1_M
#define MCBSP_RCR1_M
#define MCBSP_XCR2_M
#define MCBSP_RCR2_M
#define MCBSP_RX_NO_ERROR 0x0U
No error.
#define MCBSP_RX_BUFFER_ERROR 0x4U
Buffer Full.
#define MCBSP_RX_FRAME_SYNC_ERROR 0x8U
Frame sync error.
#define MCBSP_RX_BUFFER_FRAME_SYNC_ERROR 0xCU
Buffer and frame sync error.
#define MCBSP_TX_NO_ERROR 0x0U
No error.
#define MCBSP_TX_BUFFER_ERROR 0x4U
Buffer overrun.
#define MCBSP_TX_FRAME_SYNC_ERROR 0x8U
Frame sync error.
#define MCBSP_TX_BUFFER_FRAME_SYNC_ERROR 0xCU
Buffer and frame sync error.
#define MCBSP_ERROR_EXCEEDED_CHANNELS 0x1U
Exceeded number of channels.
#define MCBSP_ERROR_2_PARTITION_A 0x2U
Error in 2 partition A setup.
#define MCBSP_ERROR_2_PARTITION_B 0x4U
Error in 2 partition B setup.
#define MCBSP_ERROR_INVALID_MODE 0x8U
Invalid mode.
Enumerations
enum McBSP_RxSignExtensionMode {
MCBSP_RIGHT_JUSTIFY_FILL_ZERO = 0x0000U,
MCBSP_RIGHT_JUSTIFY_FILL_SIGN = 0x2000U,
MCBSP_LEFT_JUSTIFY_FILL_ZER0 = 0x4000U
}
enum McBSP_ClockStopMode {
MCBSP_CLOCK_MCBSP_MODE = 0x0000U,
MCBSP_CLOCK_SPI_MODE_NO_DELAY = 0x1000U,
MCBSP_CLOCK_SPI_MODE_DELAY = 0x1800U
}
enum McBSP_RxInterruptSource {
MCBSP_RX_ISR_SOURCE_SERIAL_WORD = 0x0000U,
MCBSP_RX_ISR_SOURCE_END_OF_BLOCK = 0x0010U,
MCBSP_RX_ISR_SOURCE_FRAME_SYNC = 0x0020U,
MCBSP_RX_ISR_SOURCE_SYNC_ERROR = 0x0030U
}
enum McBSP_EmulationMode {
MCBSP_EMULATION_IMMEDIATE_STOP = 0x0000U,
MCBSP_EMULATION_SOFT_STOP = 0x0100U,
MCBSP_EMULATION_FREE_RUN = 0x0200U
}
enum McBSP_TxInterruptSource {
MCBSP_TX_ISR_SOURCE_TX_READY = 0x0000U,
MCBSP_TX_ISR_SOURCE_END_OF_BLOCK = 0x0010U,
MCBSP_TX_ISR_SOURCE_FRAME_SYNC = 0x0020U,
MCBSP_TX_ISR_SOURCE_SYNC_ERROR = 0x0030U
}
enum McBSP_DataPhaseFrame {
MCBSP_PHASE_ONE_FRAME = 0x0000U,
MCBSP_PHASE_TWO_FRAME = 0x0001U
}
enum McBSP_DataBitsPerWord {
MCBSP_BITS_PER_WORD_8 = 0x0000U,
MCBSP_BITS_PER_WORD_12 = 0x0020U,
MCBSP_BITS_PER_WORD_16 = 0x0040U,
MCBSP_BITS_PER_WORD_20 = 0x0060U,
MCBSP_BITS_PER_WORD_24 = 0x0080U,
MCBSP_BITS_PER_WORD_32 = 0x00A0U
}
enum McBSP_CompandingMode {
MCBSP_COMPANDING_NONE = 0x0000U,
MCBSP_COMPANDING_NONE_LSB_FIRST = 0x0008U,
MCBSP_COMPANDING_U_LAW_SET = 0x0010U,
MCBSP_COMPANDING_A_LAW_SET = 0x0018U
}
enum McBSP_DataDelayBits {
MCBSP_DATA_DELAY_BIT_0 = 0x0000U,
MCBSP_DATA_DELAY_BIT_1 = 0x0001U,
MCBSP_DATA_DELAY_BIT_2 = 0x0002U
}
enum McBSP_SRGRxClockSource {
MCBSP_SRG_RX_CLOCK_SOURCE_LSPCLK = 0x0001U,
MCBSP_SRG_RX_CLOCK_SOURCE_MCLKX_PIN = 0x0003U
}
enum McBSP_SRGTxClockSource {
MCBSP_SRG_TX_CLOCK_SOURCE_LSPCLK = 0x0001U,
MCBSP_SRG_TX_CLOCK_SOURCE_MCLKR_PIN = 0x0002U
}
enum McBSP_TxInternalFrameSyncSource {
MCBSP_TX_INTERNAL_FRAME_SYNC_DATA = 0x0000U,
MCBSP_TX_INTERNAL_FRAME_SYNC_SRG = 0x1000U
}
enum McBSP_MultichannelPartition {
MCBSP_MULTICHANNEL_TWO_PARTITION = 0x0000U,
MCBSP_MULTICHANNEL_EIGHT_PARTITION = 0x0200U
}
enum McBSP_PartitionBlock {
MCBSP_PARTITION_BLOCK_0 = 0x0000U,
MCBSP_PARTITION_BLOCK_1 = 0x0001U,
MCBSP_PARTITION_BLOCK_2 = 0x0002U,
MCBSP_PARTITION_BLOCK_3 = 0x0003U,
MCBSP_PARTITION_BLOCK_4 = 0x0004U,
MCBSP_PARTITION_BLOCK_5 = 0x0005U,
MCBSP_PARTITION_BLOCK_6 = 0x0006U,
MCBSP_PARTITION_BLOCK_7 = 0x0007U
}
enum McBSP_RxChannelMode {
MCBSP_ALL_RX_CHANNELS_ENABLED = 0x0000U,
MCBSP_RX_CHANNEL_SELECTION_ENABLED = 0x0001U
}
enum McBSP_TxChannelMode {
MCBSP_ALL_TX_CHANNELS_ENABLED = 0x0000U,
MCBSP_TX_CHANNEL_SELECTION_ENABLED = 0x0001U,
MCBSP_ENABLE_MASKED_TX_CHANNEL_SELECTION = 0x0002U,
MCBSP_SYMMERTIC_RX_TX_SELECTION = 0x0003U
}
enum McBSP_TxFrameSyncSource {
MCBSP_TX_EXTERNAL_FRAME_SYNC_SOURCE = 0x0000U,
MCBSP_TX_INTERNAL_FRAME_SYNC_SOURCE = 0x0800U
}
enum McBSP_RxFrameSyncSource {
MCBSP_RX_EXTERNAL_FRAME_SYNC_SOURCE = 0x0000U,
MCBSP_RX_INTERNAL_FRAME_SYNC_SOURCE = 0x0400U
}
enum McBSP_TxClockSource {
MCBSP_EXTERNAL_TX_CLOCK_SOURCE = 0x0000U,
MCBSP_INTERNAL_TX_CLOCK_SOURCE = 0x0200U
}
enum McBSP_RxClockSource {
MCBSP_EXTERNAL_RX_CLOCK_SOURCE = 0x0000U,
MCBSP_INTERNAL_RX_CLOCK_SOURCE = 0x0100U
}
enum McBSP_TxFrameSyncPolarity {
MCBSP_TX_FRAME_SYNC_POLARITY_HIGH = 0x0000U,
MCBSP_TX_FRAME_SYNC_POLARITY_LOW = 0x0008U
}
enum McBSP_RxFrameSyncPolarity {
MCBSP_RX_FRAME_SYNC_POLARITY_HIGH = 0x0000U,
MCBSP_RX_FRAME_SYNC_POLARITY_LOW = 0x0004U
}
enum McBSP_TxClockPolarity {
MCBSP_TX_POLARITY_RISING_EDGE = 0x0000U,
MCBSP_TX_POLARITY_FALLING_EDGE = 0x0002U
}
enum McBSP_RxClockPolarity {
MCBSP_RX_POLARITY_FALLING_EDGE = 0x0000U,
MCBSP_RX_POLARITY_RISING_EDGE = 0x0001U
}
enum McBSP_CompandingType {
MCBSP_COMPANDING_U_LAW = 0x0002U,
MCBSP_COMPANDING_A_LAW = 0x0003U
}
Functions
static void McBSP_disableLoopback (uint32_t base)
static void McBSP_enableLoopback (uint32_t base)
static void McBSP_setRxSignExtension (uint32_t base, const McBSP_RxSignExtensionMode mode)
static void McBSP_setClockStopMode (uint32_t base, const McBSP_ClockStopMode mode)
static void McBSP_disableDxPinDelay (uint32_t base)
static void McBSP_enableDxPinDelay (uint32_t base)
static void McBSP_setRxInterruptSource (uint32_t base, const McBSP_RxInterruptSource interruptSource)
static void McBSP_clearRxFrameSyncError (uint32_t base)
static uint16_t McBSP_getRxErrorStatus (uint32_t base)
static bool McBSP_isRxReady (uint32_t base)
static void McBSP_resetReceiver (uint32_t base)
static void McBSP_enableReceiver (uint32_t base)
static void McBSP_setEmulationMode (uint32_t base, const McBSP_EmulationMode emulationMode)
static void McBSP_resetFrameSyncLogic (uint32_t base)
static void McBSP_enableFrameSyncLogic (uint32_t base)
static void McBSP_resetSampleRateGenerator (uint32_t base)
static void McBSP_enableSampleRateGenerator (uint32_t base)
static void McBSP_setTxInterruptSource (uint32_t base, const McBSP_TxInterruptSource interruptSource)
static uint16_t McBSP_getTxErrorStatus (uint32_t base)
static void McBSP_clearTxFrameSyncError (uint32_t base)
static bool McBSP_isTxReady (uint32_t base)
static void McBSP_resetTransmitter (uint32_t base)
static void McBSP_enableTransmitter (uint32_t base)
static void McBSP_disableTwoPhaseRx (uint32_t base)
static void McBSP_enableTwoPhaseRx (uint32_t base)
static void McBSP_setRxCompandingMode (uint32_t base, const McBSP_CompandingMode compandingMode)
static void McBSP_disableRxFrameSyncErrorDetection (uint32_t base)
static void McBSP_enableRxFrameSyncErrorDetection (uint32_t base)
static void McBSP_setRxDataDelayBits (uint32_t base, const McBSP_DataDelayBits delayBits)
static void McBSP_disableTwoPhaseTx (uint32_t base)
static void McBSP_enableTwoPhaseTx (uint32_t base)
static void McBSP_setTxCompandingMode (uint32_t base, const McBSP_CompandingMode compandingMode)
static void McBSP_disableTxFrameSyncErrorDetection (uint32_t base)
static void McBSP_enableTxFrameSyncErrorDetection (uint32_t base)
static void McBSP_setTxDataDelayBits (uint32_t base, const McBSP_DataDelayBits delayBits)
static void McBSP_setFrameSyncPulsePeriod (uint32_t base, uint16_t frameClockDivider)
static void McBSP_setFrameSyncPulseWidthDivider (uint32_t base, uint16_t pulseWidthDivider)
static void McBSP_setSRGDataClockDivider (uint32_t base, uint16_t dataClockDivider)
static void McBSP_disableSRGSyncFSR (uint32_t base)
static void McBSP_enableSRGSyncFSR (uint32_t base)
static void McBSP_setRxSRGClockSource (uint32_t base, const McBSP_SRGRxClockSource srgClockSource)
static void McBSP_setTxSRGClockSource (uint32_t base, const McBSP_SRGTxClockSource srgClockSource)
static void McBSP_setTxInternalFrameSyncSource (uint32_t base, const McBSP_TxInternalFrameSyncSource syncMode)
static void McBSP_setRxMultichannelPartition (uint32_t base, const McBSP_MultichannelPartition partition)
static void McBSP_setRxTwoPartitionBlock (uint32_t base, const McBSP_PartitionBlock block)
static uint16_t McBSP_getRxActiveBlock (uint32_t base)
static void McBSP_setRxChannelMode (uint32_t base, const McBSP_RxChannelMode channelMode)
static void McBSP_setTxMultichannelPartition (uint32_t base, const McBSP_MultichannelPartition partition)
static void McBSP_setTxTwoPartitionBlock (uint32_t base, const McBSP_PartitionBlock block)
static uint16_t McBSP_getTxActiveBlock (uint32_t base)
static void McBSP_setTxChannelMode (uint32_t base, const McBSP_TxChannelMode channelMode)
static void McBSP_setTxFrameSyncSource (uint32_t base, const McBSP_TxFrameSyncSource syncSource)
static void McBSP_setRxFrameSyncSource (uint32_t base, const McBSP_RxFrameSyncSource syncSource)
static void McBSP_setTxClockSource (uint32_t base, const McBSP_TxClockSource clockSource)
static void McBSP_setRxClockSource (uint32_t base, const McBSP_RxClockSource clockSource)
static void McBSP_setTxFrameSyncPolarity (uint32_t base, const McBSP_TxFrameSyncPolarity syncPolarity)
static void McBSP_setRxFrameSyncPolarity (uint32_t base, const McBSP_RxFrameSyncPolarity syncPolarity)
static void McBSP_setTxClockPolarity (uint32_t base, const McBSP_TxClockPolarity clockPolarity)
static void McBSP_setRxClockPolarity (uint32_t base, const McBSP_RxClockPolarity clockPolarity)
static uint16_t McBSP_read16bitData (uint32_t base)
static uint32_t McBSP_read32bitData (uint32_t base)
static void McBSP_write16bitData (uint32_t base, uint16_t data)
static void McBSP_write32bitData (uint32_t base, uint32_t data)
static uint16_t McBSP_getLeftJustifyData (uint16_t data, const McBSP_CompandingType compandingType)
static void McBSP_enableRxInterrupt (uint32_t base)
static void McBSP_disableRxInterrupt (uint32_t base)
static void McBSP_enableTxInterrupt (uint32_t base)
static void McBSP_disableTxInterrupt (uint32_t base)
void McBSP_transmit16BitDataNonBlocking (uint32_t base, uint16_t data)
void McBSP_transmit16BitDataBlocking (uint32_t base, uint16_t data)
void McBSP_transmit32BitDataNonBlocking (uint32_t base, uint32_t data)
void McBSP_transmit32BitDataBlocking (uint32_t base, uint32_t data)
void McBSP_receive16BitDataNonBlocking (uint32_t base, uint16_t *receiveData)
void McBSP_receive16BitDataBlocking (uint32_t base, uint16_t *receiveData)
void McBSP_receive32BitDataNonBlocking (uint32_t base, uint32_t *receiveData)
void McBSP_receive32BitDataBlocking (uint32_t base, uint32_t *receiveData)
void McBSP_setRxDataSize (uint32_t base, const McBSP_DataPhaseFrame dataFrame, const McBSP_DataBitsPerWord bitsPerWord, uint16_t wordsPerFrame)
void McBSP_setTxDataSize (uint32_t base, const McBSP_DataPhaseFrame dataFrame, const McBSP_DataBitsPerWord bitsPerWord, uint16_t wordsPerFrame)
void McBSP_disableRxChannel (uint32_t base, const McBSP_MultichannelPartition partition, uint16_t channel)
void McBSP_enableRxChannel (uint32_t base, const McBSP_MultichannelPartition partition, uint16_t channel)
void McBSP_disableTxChannel (uint32_t base, const McBSP_MultichannelPartition partition, uint16_t channel)
void McBSP_enableTxChannel (uint32_t base, const McBSP_MultichannelPartition partition, uint16_t channel)
void McBSP_configureTxClock (uint32_t base, const McBSP_ClockParams *ptrClockParams)
void McBSP_configureRxClock (uint32_t base, const McBSP_ClockParams *ptrClockParams)
void McBSP_configureTxFrameSync (uint32_t base, const McBSP_TxFsyncParams *ptrFsyncParams)
void McBSP_configureRxFrameSync (uint32_t base, const McBSP_RxFsyncParams *ptrFsyncParams)
void McBSP_configureTxDataFormat (uint32_t base, const McBSP_TxDataParams *ptrDataParams)
void McBSP_configureRxDataFormat (uint32_t base, const McBSP_RxDataParams *ptrDataParams)
uint16_t McBSP_configureTxMultichannel (uint32_t base, const McBSP_TxMultichannelParams *ptrMchnParams)
uint16_t McBSP_configureRxMultichannel (uint32_t base, const McBSP_RxMultichannelParams *ptrMchnParams)
void McBSP_configureSPIMasterMode (uint32_t base, const McBSP_SPIMasterModeParams *ptrSPIMasterMode)
void McBSP_configureSPISlaveMode (uint32_t base, const McBSP_SPISlaveModeParams *ptrSPISlaveMode)
Detailed Description
Macro Definition Documentation
#define MCBSP_XCR1_M
Value:
(MCBSP_XCR1_XWDLEN1_M |\
                                 MCBSP_XCR1_XFRLEN1_M)
Referenced by McBSP_setTxDataSize().
#define MCBSP_RCR1_M
Value:
(MCBSP_RCR1_RWDLEN1_M |\
                                 MCBSP_RCR1_RFRLEN1_M)
Referenced by McBSP_setRxDataSize().
#define MCBSP_XCR2_M
Value:
(MCBSP_XCR2_XWDLEN2_M |\
                                 MCBSP_XCR2_XFRLEN2_M)
Referenced by McBSP_setTxDataSize().
#define MCBSP_RCR2_M
Value:
(MCBSP_RCR2_RWDLEN2_M |\
                                 MCBSP_RCR2_RFRLEN2_M)
Referenced by McBSP_setRxDataSize().
#define MCBSP_RX_NO_ERROR 0x0U
No error.
#define MCBSP_RX_BUFFER_ERROR 0x4U
Buffer Full.
#define MCBSP_RX_FRAME_SYNC_ERROR 0x8U
Frame sync error.
#define MCBSP_RX_BUFFER_FRAME_SYNC_ERROR 0xCU
Buffer and frame sync error.
#define MCBSP_TX_NO_ERROR 0x0U
No error.
#define MCBSP_TX_BUFFER_ERROR 0x4U
Buffer overrun.
#define MCBSP_TX_FRAME_SYNC_ERROR 0x8U
Frame sync error.
#define MCBSP_TX_BUFFER_FRAME_SYNC_ERROR 0xCU
Buffer and frame sync error.
#define MCBSP_ERROR_EXCEEDED_CHANNELS 0x1U
Exceeded number of channels.
Referenced by McBSP_configureRxMultichannel(), and McBSP_configureTxMultichannel().
#define MCBSP_ERROR_2_PARTITION_A 0x2U
Error in 2 partition A setup.
Referenced by McBSP_configureRxMultichannel(), and McBSP_configureTxMultichannel().
#define MCBSP_ERROR_2_PARTITION_B 0x4U
Error in 2 partition B setup.
Referenced by McBSP_configureRxMultichannel(), and McBSP_configureTxMultichannel().
#define MCBSP_ERROR_INVALID_MODE 0x8U
Invalid mode.
Enumeration Type Documentation
enum McBSP_RxSignExtensionMode
Values that can be passed to McBSP_setRxSignExtension() as the mode parameters.
Enumerator
MCBSP_RIGHT_JUSTIFY_FILL_ZERO
Right justify and zero fill MSB.
MCBSP_RIGHT_JUSTIFY_FILL_SIGN
Right justified sign extended into MSBs.
MCBSP_LEFT_JUSTIFY_FILL_ZER0
Left justifies LBS filled with zero.
enum McBSP_ClockStopMode
Values that can be passed to McBSP_setClockStopMode() as the mode parameter.
Enumerator
MCBSP_CLOCK_MCBSP_MODE
Disables clock stop mode.
MCBSP_CLOCK_SPI_MODE_NO_DELAY
Enables clock stop mode.
MCBSP_CLOCK_SPI_MODE_DELAY
Enables clock stop mode with half cycle delay.
enum McBSP_RxInterruptSource
Values that can be passed to McBSP_setRxInterruptSource() as the interruptSource parameter.
Enumerator
MCBSP_RX_ISR_SOURCE_SERIAL_WORD
Interrupt when Rx is ready.
MCBSP_RX_ISR_SOURCE_END_OF_BLOCK
Interrupt at block end.
MCBSP_RX_ISR_SOURCE_FRAME_SYNC
Interrupt when frame sync occurs.
MCBSP_RX_ISR_SOURCE_SYNC_ERROR
Interrupt on frame sync error.
enum McBSP_EmulationMode
Values that can be passed to McBSP_setEmulationMode() as the emulationMode parameter.
Enumerator
MCBSP_EMULATION_IMMEDIATE_STOP
McBSP TX and RX stop when a breakpoint is reached.
MCBSP_EMULATION_SOFT_STOP
McBSP TX stops after current word transmitted.
MCBSP_EMULATION_FREE_RUN
McBSP TX and RX run ignoring the breakpoint.
enum McBSP_TxInterruptSource
Values that can be passed to McBSP_setTxInterruptSource() as the interruptSource parameter.
Enumerator
MCBSP_TX_ISR_SOURCE_TX_READY
Interrupt when Tx Ready.
MCBSP_TX_ISR_SOURCE_END_OF_BLOCK
Interrupt at block end.
MCBSP_TX_ISR_SOURCE_FRAME_SYNC
Interrupt when frame sync occurs.
MCBSP_TX_ISR_SOURCE_SYNC_ERROR
Interrupt on frame sync error.
enum McBSP_DataPhaseFrame
Values that can be passed to to McBSP_setTxDataSize() and McBSP_setRxDataSize() as the dataFrame parameter.
Enumerator
MCBSP_PHASE_ONE_FRAME
Single Phase.
MCBSP_PHASE_TWO_FRAME
Dual Phase.
enum McBSP_DataBitsPerWord
Values that can be passed as of McBSP_setTxDataSize() and McBSP_setRxDataSize() as the bitsPerWord parameter.
Enumerator
MCBSP_BITS_PER_WORD_8
8 bit word.
MCBSP_BITS_PER_WORD_12
12 bit word.
MCBSP_BITS_PER_WORD_16
16 bit word.
MCBSP_BITS_PER_WORD_20
20 bit word.
MCBSP_BITS_PER_WORD_24
24 bit word.
MCBSP_BITS_PER_WORD_32
32 bit word.
enum McBSP_CompandingMode
Values that can be passed to McBSP_setTxCompandingMode() and McBSP_setRxCompandingMode() as the compandingMode parameter.
Enumerator
MCBSP_COMPANDING_NONE
Disables companding.
MCBSP_COMPANDING_NONE_LSB_FIRST
Disables companding and Enables 8 bit LSB first data reception.
MCBSP_COMPANDING_U_LAW_SET
U-law companding.
MCBSP_COMPANDING_A_LAW_SET
A-law companding.
enum McBSP_DataDelayBits
Values that can be passed to McBSP_setTxDataDelayBits() and McBSP_setRxDataDelayBits() as the delayBits parameter.
Enumerator
MCBSP_DATA_DELAY_BIT_0
O bit delay.
MCBSP_DATA_DELAY_BIT_1
1 bit delay.
MCBSP_DATA_DELAY_BIT_2
2 bit delay.
enum McBSP_SRGRxClockSource
Values that can be passed for SRG for McBSP_setRxSRGClockSource() as the clockSource parameter.
Enumerator
MCBSP_SRG_RX_CLOCK_SOURCE_LSPCLK
LSPCLK is SRG clock source.
MCBSP_SRG_RX_CLOCK_SOURCE_MCLKX_PIN
MCLKx is SRG clock source.
enum McBSP_SRGTxClockSource
Values that can be passed for SRG to McBSP_setTxSRGClockSource() as the clockSource parameter.
Enumerator
MCBSP_SRG_TX_CLOCK_SOURCE_LSPCLK
LSPCLK is SRG clock source.
MCBSP_SRG_TX_CLOCK_SOURCE_MCLKR_PIN
MCLKris SRG clock source.
enum McBSP_TxInternalFrameSyncSource
Values that can be passed to McBSP_setTxInternalFrameSyncSource() as the syncMode parameter.
Enumerator
MCBSP_TX_INTERNAL_FRAME_SYNC_DATA
sync source.
Data is frame
MCBSP_TX_INTERNAL_FRAME_SYNC_SRG
sync source.
SRG is frame
enum McBSP_MultichannelPartition
Values that can be passed to McBSP_setRxMultichannelPartition() and McBSP_setTxMultichannelPartition() as the MultichannelPartition parameter.
Enumerator
MCBSP_MULTICHANNEL_TWO_PARTITION
Two partition.
MCBSP_MULTICHANNEL_EIGHT_PARTITION
Eight partition.
enum McBSP_PartitionBlock
Values that can be passed to McBSP_setRxTwoPartitionBlock() and McBSP_setTxTwoPartitionBlock() as the block parameter.
Enumerator
MCBSP_PARTITION_BLOCK_0
Partition block 0.
MCBSP_PARTITION_BLOCK_1
Partition block 1.
MCBSP_PARTITION_BLOCK_2
Partition block 2.
MCBSP_PARTITION_BLOCK_3
Partition block 3.
MCBSP_PARTITION_BLOCK_4
Partition block 4.
MCBSP_PARTITION_BLOCK_5
Partition block 5.
MCBSP_PARTITION_BLOCK_6
Partition block 6.
MCBSP_PARTITION_BLOCK_7
Partition block 7.
enum McBSP_RxChannelMode
Values that can be passed to McBSP_setRxChannelMode() as the channelMode parameter.
Enumerator
MCBSP_ALL_RX_CHANNELS_ENABLED
All Channels are enabled.
MCBSP_RX_CHANNEL_SELECTION_ENABLED
Selected channels enabled.
enum McBSP_TxChannelMode
Values that can be passed to McBSP_setTxChannelMode() as the channelMode parameter.
Enumerator
MCBSP_ALL_TX_CHANNELS_ENABLED
All Channels Enabled.
MCBSP_TX_CHANNEL_SELECTION_ENABLED
Selection Enabled.
MCBSP_ENABLE_MASKED_TX_CHANNEL_SELECTION
Masked Tx Channel.
MCBSP_SYMMERTIC_RX_TX_SELECTION
Symmetric Selection.
enum McBSP_TxFrameSyncSource
Values that can be passed to McBSP_setTxFrameSyncSource() as the syncSource parameter.
Enumerator
MCBSP_TX_EXTERNAL_FRAME_SYNC_SOURCE
FSR pin supplies frame sync signal.
MCBSP_TX_INTERNAL_FRAME_SYNC_SOURCE
SRG supplies frame sync signal.
enum McBSP_RxFrameSyncSource
Values that can be passed to McBSP_setRxFrameSyncSource() as the syncSource parameter.
Enumerator
MCBSP_RX_EXTERNAL_FRAME_SYNC_SOURCE
FSR pin supplies frame sync signal.
MCBSP_RX_INTERNAL_FRAME_SYNC_SOURCE
SRG supplies frame sync signal.
enum McBSP_TxClockSource
Values that can be passed to McBSP_setTxClockSource() as the Transmitter clockSource parameter.
Enumerator
MCBSP_EXTERNAL_TX_CLOCK_SOURCE
Clock source is external.
MCBSP_INTERNAL_TX_CLOCK_SOURCE
Clock source is internal.
enum McBSP_RxClockSource
Values that can be passed toMcBSP_setRxClockSource() as the Receiver clockSource parameter.
Enumerator
MCBSP_EXTERNAL_RX_CLOCK_SOURCE
Clock source is external.
MCBSP_INTERNAL_RX_CLOCK_SOURCE
Clock source is internal.
enum McBSP_TxFrameSyncPolarity
Values that can be passed to McBSP_setTxFrameSyncPolarity() as the Transmitter syncPolarity parameter.
Enumerator
MCBSP_TX_FRAME_SYNC_POLARITY_HIGH
Pulse active high.
MCBSP_TX_FRAME_SYNC_POLARITY_LOW
Pulse active low.
enum McBSP_RxFrameSyncPolarity
Values that can be passed to McBSP_setRxFrameSyncPolarity() as the Receiver syncPolarity parameter.
Enumerator
MCBSP_RX_FRAME_SYNC_POLARITY_HIGH
Pulse active high.
MCBSP_RX_FRAME_SYNC_POLARITY_LOW
Pulse active low.
enum McBSP_TxClockPolarity
Values that can be passed for Transmitter of McBSP_setTxClockPolarity() as the Transmiiter clockPolarity parameter.
Enumerator
MCBSP_TX_POLARITY_RISING_EDGE
TX data on rising edge.
MCBSP_TX_POLARITY_FALLING_EDGE
TX data on falling edge.
enum McBSP_RxClockPolarity
Values that can be passed for Receiver of McBSP_setRxClockPolarity() as the Receiver clockPolarity parameter.
Enumerator
MCBSP_RX_POLARITY_FALLING_EDGE
RX data sampled falling edge.
MCBSP_RX_POLARITY_RISING_EDGE
RX data sampled rising edge.
enum McBSP_CompandingType
Values that can be passed to McBSP_getLeftJustifyData() as the compandingType parameter.
Enumerator
MCBSP_COMPANDING_U_LAW
U-law companding.
MCBSP_COMPANDING_A_LAW
A-law companding.
Function Documentation
static void McBSP_disableLoopback (uint32_t base) inline static
Disables digital loop back mode.
Parameters
base is the base address of the McBSP module.
This function disables digital loop back mode.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR1, and MCBSP_SPCR1_DLB.
Referenced by McBSP_configureRxDataFormat(), McBSP_configureSPIMasterMode(), McBSP_configureSPISlaveMode(), and McBSP_configureTxDataFormat().
static void McBSP_enableLoopback (uint32_t base) inline static
Enables digital loop back mode.
Parameters
base is the base address of the McBSP module.
This function enables digital loop back mode.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR1, and MCBSP_SPCR1_DLB.
Referenced by McBSP_configureRxDataFormat(), McBSP_configureSPIMasterMode(), McBSP_configureSPISlaveMode(), and McBSP_configureTxDataFormat().
static void McBSP_setRxSignExtension (uint32_t base, const McBSP_RxSignExtensionMode mode) inline static
Configures receiver sign extension mode.
Parameters
base is the base address of the McBSP module.
mode is the sign extension mode.
This function sets the sign extension mode. Valid values for mode are:
MCBSP_RIGHT_JUSTIFY_FILL_ZERO - right justified MSB filled with zero.
MCBSP_RIGHT_JUSTIFY_FILL_SIGN - right justified sign extended in MSBs.
MCBSP_LEFT_JUSTIFY_FILL_ZER0 - left justifies LBS filled with zero.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR1, and MCBSP_SPCR1_RJUST_M.
Referenced by McBSP_configureRxDataFormat().
static void McBSP_setClockStopMode (uint32_t base, const McBSP_ClockStopMode mode) inline static
Configures clock stop mode.
Parameters
base is the base address of the McBSP module.
mode is the clock stop mode.
This function sets the cock stop mode. Valid values for mode are
MCBSP_CLOCK_MCBSP_MODE disables clock stop mode.
MCBSP_CLOCK_SPI_MODE_NO_DELAY enables clock stop mode
MCBSP_CLOCK_SPI_MODE_DELAY enables clock stop mode with delay.
If an invalid value is provided, the function will exit with out altering the register bits involved.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR1, and MCBSP_SPCR1_CLKSTP_M.
Referenced by McBSP_configureRxDataFormat(), McBSP_configureSPIMasterMode(), McBSP_configureSPISlaveMode(), and McBSP_configureTxDataFormat().
static void McBSP_disableDxPinDelay (uint32_t base) inline static
Disables delay at DX pin.
Parameters
base is the base address of the McBSP module.
This function disables delay on pin DX when turning the module on.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR1, and MCBSP_SPCR1_DXENA.
Referenced by McBSP_configureTxDataFormat().
static void McBSP_enableDxPinDelay (uint32_t base) inline static
Enables delay at DX pin.
Parameters
base is the base address of the McBSP module.
This function enables a delay on pin DX when turning the module on. Look at McBSP timing diagrams for details.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR1, and MCBSP_SPCR1_DXENA.
Referenced by McBSP_configureTxDataFormat().
static void McBSP_setRxInterruptSource (uint32_t base, const McBSP_RxInterruptSource interruptSource) inline static
Configures receiver interrupt sources.
Parameters
base is the base address of the McBSP module.
interruptSource is the ISR source.
This function sets the receiver interrupt sources. Valid values for interruptSource are:
MCBSP_RX_ISR_SOURCE_SERIAL_WORD - interrupt at each serial word.
MCBSP_RX_ISR_SOURCE_END_OF_BLOCK - interrupt at the end of block.
MCBSP_RX_ISR_SOURCE_FRAME_SYNC - interrupt when frame sync occurs.
MCBSP_RX_ISR_SOURCE_SYNC_ERROR - interrupt on frame sync error.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR1, and MCBSP_SPCR1_RINTM_M.
Referenced by McBSP_configureRxDataFormat().
static void McBSP_clearRxFrameSyncError (uint32_t base) inline static
Clear the receiver frame sync error.
Parameters
base is the base address of the McBSP module.
This function clears the receive frame sync error.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR1, and MCBSP_SPCR1_RSYNCERR.
static uint16_t McBSP_getRxErrorStatus (uint32_t base) inline static
Return receiver error.
Parameters
base is the base address of the McBSP module.
This function returns McBSP receiver errors.
Returns
Returns the following error codes.
MCBSP_RX_NO_ERROR - if there is no error.
MCBSP_RX_BUFFER_ERROR - if buffergets full.
MCBSP_RX_FRAME_SYNC_ERROR -if unexpected frame sync occurs.
MCBSP_RX_BUFFER_FRAME_SYNC_ERROR - if buffer overrun and frame sync error occurs.
References ASSERT, HWREGH, MCBSP_O_SPCR1, MCBSP_SPCR1_RFULL, and MCBSP_SPCR1_RSYNCERR.
static bool McBSP_isRxReady (uint32_t base) inline static
Check if data is received by the receiver.
Parameters
base is the base address of the McBSP port.
This function returns the status of the receiver buffer , indicating if new data is available.
Returns
true if new data is available or if the current data was never read. false if there is no new data in the receive buffer.
References ASSERT, HWREGH, MCBSP_O_SPCR1, and MCBSP_SPCR1_RRDY.
Referenced by McBSP_receive16BitDataBlocking(), and McBSP_receive32BitDataBlocking().
static void McBSP_resetReceiver (uint32_t base) inline static
Reset McBSP receiver.
Parameters
base is the base address of the McBSP module.
This function resets McBSP receiver.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR1, and MCBSP_SPCR1_RRST.
static void McBSP_enableReceiver (uint32_t base) inline static
Enable McBSP receiver.
Parameters
base is the base address of the McBSP module.
This function enables McBSP receiver.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR1, and MCBSP_SPCR1_RRST.
static void McBSP_setEmulationMode (uint32_t base, const McBSP_EmulationMode emulationMode) inline static
Configures emulation mode.
Parameters
base is the base address of the McBSP module.
emulationMode is the McBSP emulation character.
This function sets the McBSP characters when a breakpoint is encountered in emulation mode. Valid values for emulationMode are:
MCBSP_EMULATION_IMMEDIATE_STOP - transmitter and receiver both stop when a breakpoint is reached.
MCBSP_EMULATION_SOFT_STOP - transmitter stops after current word is transmitted. Receiver is not affected.
MCBSP_EMULATION_FREE_RUN - McBSP runs ignoring the breakpoint.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR2, MCBSP_SPCR2_FREE, and MCBSP_SPCR2_SOFT.
static void McBSP_resetFrameSyncLogic (uint32_t base) inline static
Reset frame sync logic.
Parameters
base is the base address of the McBSP module.
Resets frame sync logic.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR2, and MCBSP_SPCR2_FRST.
static void McBSP_enableFrameSyncLogic (uint32_t base) inline static
Enable frame sync logic.
Parameters
base is the base address of the McBSP module.
Enables frame sync logic.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR2, and MCBSP_SPCR2_FRST.
static void McBSP_resetSampleRateGenerator (uint32_t base) inline static
Reset sample rate generator.
Parameters
base is the base address of the McBSP module.
Resets sample rate generator by clearing GRST bit.
Returns
References ASSERT, HWREGH, MCBSP_O_SPCR2, and MCBSP_SPCR2_GRST.
static void McBSP_enableSampleRateGenerator (uint32_t base) inline static
Enable sample rate generator.
Parameters
base is the base address of the McBSP module.
Enables sample rate generator by setting GRST bit.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR2, and MCBSP_SPCR2_GRST.
static void McBSP_setTxInterruptSource (uint32_t base, const McBSP_TxInterruptSource interruptSource) inline static
Configures transmitter interrupt sources.
Parameters
base is the base address of the McBSP module.
interruptSource is the ISR source.
This function sets the transmitter interrupt sources. Valid values for interruptSource are:
MCBSP_TX_ISR_SOURCE_TX_READY - interrupt when transmitter is ready to accept data.
MCBSP_TX_ISR_SOURCE_END_OF_BLOCK - interrupt at the end of block.
MCBSP_TX_ISR_SOURCE_FRAME_SYNC - interrupt when frame sync occurs.
MCBSP_TX_ISR_SOURCE_SYNC_ERROR - interrupt on frame sync error.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR2, and MCBSP_SPCR2_XINTM_M.
Referenced by McBSP_configureTxDataFormat().
static uint16_t McBSP_getTxErrorStatus (uint32_t base) inline static
Return Transmitter error.
Parameters
base is the base address of the McBSP module.
This function returns McBSP transmitter errors.
Returns
Returns the following error codes.
MCBSP_TX_NO_ERROR - if buffer overrun occurs.
MCBSP_TX_BUFFER_ERROR -if unexpected frame sync occurs.
MCBSP_TX_FRAME_SYNC_ERROR - if there is no error.
MCBSP_TX_BUFFER_FRAME_SYNC_ERROR - if buffer overrun and frame sync error occurs.
References ASSERT, HWREGH, MCBSP_O_SPCR2, MCBSP_SPCR2_XEMPTY, and MCBSP_SPCR2_XSYNCERR.
static void McBSP_clearTxFrameSyncError (uint32_t base) inline static
Clear the Transmitter frame sync error.
Parameters
base is the base address of the McBSP module.
This function clears the transmitter frame sync error.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR2, and MCBSP_SPCR2_XSYNCERR.
static bool McBSP_isTxReady (uint32_t base) inline static
Check if Transmitter is ready.
Parameters
base is the base address of the McBSP port.
This function returns the status of the transmitter ready buffer, indicating if data can be written to the transmitter.
Returns
true if transmitter is ready to accept new data. false if transmitter is not ready to accept new data.
References ASSERT, HWREGH, MCBSP_O_SPCR2, and MCBSP_SPCR2_XRDY.
Referenced by McBSP_transmit16BitDataBlocking(), and McBSP_transmit32BitDataBlocking().
static void McBSP_resetTransmitter (uint32_t base) inline static
Reset McBSP transmitter.
Parameters
base is the base address of the McBSP module.
This functions resets McBSP transmitter.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR2, and MCBSP_SPCR2_XRST.
static void McBSP_enableTransmitter (uint32_t base) inline static
Enable McBSP transmitter.
Parameters
base is the base address of the McBSP module.
This function enables McBSP transmitter.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SPCR2, and MCBSP_SPCR2_XRST.
static void McBSP_disableTwoPhaseRx (uint32_t base) inline static
Disable 2 Phase operation for data reception.
Parameters
base is the base address of the McBSP module.
This function disables 2 phase reception.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_RCR2, and MCBSP_RCR2_RPHASE.
Referenced by McBSP_configureRxDataFormat(), and McBSP_configureRxMultichannel().
static void McBSP_enableTwoPhaseRx (uint32_t base) inline static
Enable 2 Phase operation for data Reception.
Parameters
base is the base address of the McBSP module.
This function enables 2 phase reception.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_RCR2, and MCBSP_RCR2_RPHASE.
Referenced by McBSP_configureRxDataFormat().
static void McBSP_setRxCompandingMode (uint32_t base, const McBSP_CompandingMode compandingMode) inline static
Configure receive data companding.
Parameters
base is the base address of the McBSP module.
compandingMode is the companding mode to be used.
This function configures the receive companding logic. The following are valid compandingMode values:
MCBSP_COMPANDING_NONE disables companding.
MCBSP_COMPANDING_NONE_LSB_FIRST disables companding and enables 8 bit LSB first data reception.
MCBSP_COMPANDING_U_LAW_SET enables U-law companding.
MCBSP_COMPANDING_A_LAW_SET enables A-law companding.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_RCR2, and MCBSP_RCR2_RCOMPAND_M.
Referenced by McBSP_configureRxDataFormat().
static void McBSP_disableRxFrameSyncErrorDetection (uint32_t base) inline static
Disables receiver unexpected frame sync error detection.
Parameters
base is the base address of the McBSP module.
This function disables unexpected frame sync error detection in the receiver.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_RCR2, and MCBSP_RCR2_RFIG.
static void McBSP_enableRxFrameSyncErrorDetection (uint32_t base) inline static
Enable receiver unexpected frame sync error detection.
Parameters
base is the base address of the McBSP module.
This function enables unexpected frame sync error detection in the receiver.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_RCR2, and MCBSP_RCR2_RFIG.
Referenced by McBSP_configureRxFrameSync().
static void McBSP_setRxDataDelayBits (uint32_t base, const McBSP_DataDelayBits delayBits) inline static
Sets the receive bit data delay.
Parameters
base is the base address of the McBSP module.
delayBits is the number of bits to delay.
This functions sets the bit delay after the frame sync pulse as specified by delayBits. Valid delay bits are MCBSP_DATA_DELAY_BIT_0, MCBSP_DATA_DELAY_BIT_1 or MCBSP_DATA_DELAY_BIT_2 corresponding to 0, 1 or 2 bit delay respectively.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_RCR2, and MCBSP_RCR2_RDATDLY_M.
Referenced by McBSP_configureRxDataFormat(), McBSP_configureSPIMasterMode(), and McBSP_configureSPISlaveMode().
static void McBSP_disableTwoPhaseTx (uint32_t base) inline static
Disable 2 Phase operation for data Transmission.
Parameters
base is the base address of the McBSP module.
This function disables 2 phase transmission.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_XCR2, and MCBSP_XCR2_XPHASE.
Referenced by McBSP_configureSPIMasterMode(), McBSP_configureSPISlaveMode(), McBSP_configureTxDataFormat(), and McBSP_configureTxMultichannel().
static void McBSP_enableTwoPhaseTx (uint32_t base) inline static
Enable 2 Phase operation for data Transmission.
Parameters
base is the base address of the McBSP module.
This function enables 2 phase transmission.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_XCR2, and MCBSP_XCR2_XPHASE.
Referenced by McBSP_configureTxDataFormat().
static void McBSP_setTxCompandingMode (uint32_t base, const McBSP_CompandingMode compandingMode) inline static
Configure transmit data companding.
Parameters
base is the base address of the McBSP module.
compandingMode is the companding mode to be used.
This function configures the transmit companding logic. The following are valid compandingMode values:
MCBSP_COMPANDING_NONE disables companding.
MCBSP_COMPANDING_NONE_LSB_FIRST disables companding and enables 8 bit LSB first data reception.
MCBSP_COMPANDING_U_LAW_SET enables U-law companding.
MCBSP_COMPANDING_A_LAW_SET enables A-law companding.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_XCR2, and MCBSP_XCR2_XCOMPAND_M.
Referenced by McBSP_configureTxDataFormat().
static void McBSP_disableTxFrameSyncErrorDetection (uint32_t base) inline static
Disables transmitter unexpected frame sync error detection.
Parameters
base is the base address of the McBSP module.
This function disables unexpected frame sync error detection in the transmitter.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_XCR2, and MCBSP_XCR2_XFIG.
Referenced by McBSP_configureRxFrameSync(), and McBSP_configureTxFrameSync().
static void McBSP_enableTxFrameSyncErrorDetection (uint32_t base) inline static
Enable transmitter unexpected frame sync error detection.
Parameters
base is the base address of the McBSP module.
This function enables unexpected frame sync error detection in the transmitter.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_XCR2, and MCBSP_XCR2_XFIG.
Referenced by McBSP_configureTxFrameSync().
static void McBSP_setTxDataDelayBits (uint32_t base, const McBSP_DataDelayBits delayBits) inline static
Sets the transmit bit delay.
Parameters
base is the base address of the McBSP module.
delayBits is the number of bits to delay.
This function sets the bit delay after the frame sync pulse as specified by delayBits. Valid delay bits are MCBSP_DATA_DELAY_BIT_0, MCBSP_DATA_DELAY_BIT_1 or MCBSP_DATA_DELAY_BIT_2 corresponding to 0, 1 or 2 bit delay respectively.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_XCR2, and MCBSP_XCR2_XDATDLY_M.
Referenced by McBSP_configureSPIMasterMode(), McBSP_configureSPISlaveMode(), and McBSP_configureTxDataFormat().
static void McBSP_setFrameSyncPulsePeriod (uint32_t base, uint16_t frameClockDivider) inline static
Sets the period for frame synchronisation pulse.
Parameters
base is the base address of the McBSP module.
frameClockDivider is the divider count for the sync clock.
This function sets the sample rate generator clock divider for the McBSP frame sync clock(FSG). FSG = CLKG / (frameClockDivider + 1). frameClockDivider determines the period count.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SRGR2, and MCBSP_SRGR2_FPER_M.
Referenced by McBSP_configureRxFrameSync(), and McBSP_configureTxFrameSync().
static void McBSP_setFrameSyncPulseWidthDivider (uint32_t base, uint16_t pulseWidthDivider) inline static
Sets the frame sync pulse width divider value.
Parameters
base is the base address of the McBSP module.
pulseWidthDivider is the divider count for sync clock pulse.
This function sets the pulse width divider bits for the McBSP frame sync clock(FSG). (pulseWidthDivider + 1) is the pulse width in CLKG cycles. pulseWidthDivider determines the pulse width (the on count).
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SRGR1, MCBSP_SRGR1_FWID_M, and MCBSP_SRGR1_FWID_S.
Referenced by McBSP_configureRxFrameSync(), and McBSP_configureTxFrameSync().
static void McBSP_setSRGDataClockDivider (uint32_t base, uint16_t dataClockDivider) inline static
Sets the data clock divider values.
Parameters
base is the base address of the McBSP module.
dataClockDivider is the divider count for the data rate.
This function sets the sample rate generator clock divider for the McBSP data clock(CLKG). CLKG = CLKSRG / (clockDivider + 1). Valid ranges for clockDivider are 0 to 0xFF.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SRGR1, and MCBSP_SRGR1_CLKGDV_M.
Referenced by McBSP_configureRxClock(), McBSP_configureSPIMasterMode(), McBSP_configureSPISlaveMode(), and McBSP_configureTxClock().
static void McBSP_disableSRGSyncFSR (uint32_t base) inline static
Disables external clock sync with sample generator.
Parameters
base is the base address of the McBSP module.
This function disables CLKG and FSG sync with the external pulse on pin FSR.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SRGR2, and MCBSP_SRGR2_GSYNC.
Referenced by McBSP_configureTxClock().
static void McBSP_enableSRGSyncFSR (uint32_t base) inline static
Enables external clock to synch with sample generator.
Parameters
base is the base address of the McBSP module.
This function enables CLKG and FSG to sync with the external pulse on pin FSR.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SRGR2, and MCBSP_SRGR2_GSYNC.
Referenced by McBSP_configureTxClock().
static void McBSP_setRxSRGClockSource (uint32_t base, const McBSP_SRGRxClockSource srgClockSource) inline static
Configures receiver input clock source for sample generator.
Parameters
base is the base address of the McBSP module.
srgClockSource is clock source for the sample generator.
This functions sets the clock source for the sample rate generator. Valid values for clockSource are
MCBSP_SRG_RX_CLOCK_SOURCE_LSPCLK for LSPCLK.
MCBSP_SRG_RX_CLOCK_SOURCE_MCLKX_PIN for external clock at MCLKX pin. MCLKR pin will be an output driven by sample rate generator.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_PCR, MCBSP_O_SRGR2, MCBSP_PCR_SCLKME, and MCBSP_SRGR2_CLKSM.
Referenced by McBSP_configureRxClock(), and McBSP_configureSPISlaveMode().
static void McBSP_setTxSRGClockSource (uint32_t base, const McBSP_SRGTxClockSource srgClockSource) inline static
Configures transmitter input clock source for sample generator.
Parameters
base is the base address of the McBSP module.
srgClockSource is clock source for the sample generator.
This functions sets the clock source for the sample rate generator. Valid values for clockSource are
MCBSP_SRG_TX_CLOCK_SOURCE_LSPCLK for LSPCLK.
MCBSP_SRG_TX_CLOCK_SOURCE_MCLKR_PIN for external clock at MCLKR pin. MCLKX pin will be an output driven by sample rate generator.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_PCR, MCBSP_O_SRGR2, MCBSP_PCR_SCLKME, and MCBSP_SRGR2_CLKSM.
Referenced by McBSP_configureSPIMasterMode(), and McBSP_configureTxClock().
static void McBSP_setTxInternalFrameSyncSource (uint32_t base, const McBSP_TxInternalFrameSyncSource syncMode) inline static
Sets the mode for transmitter internal frame sync signal.
Parameters
base is the base address of the McBSP module.
syncMode is the frame sync mode.
This function sets the frame sync signal generation mode. The signal can be generated based on clock divider as set in McBSP_setFrameSyncPulsePeriod() function or when data is transferred from DXR registers to XSR registers. Valid input for syncMode are:
MCBSP_TX_INTERNAL_FRAME_SYNC_DATA - frame sync signal is generated when data is transferred from DXR registers to XSR registers.
MCBSP_TX_INTERNAL_FRAME_SYNC_SRG - frame sync signal is generated based on the clock counter value as defined in McBSP_setFrameSyncPulsePeriod() function.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_SRGR2, and MCBSP_SRGR2_FSGM.
Referenced by McBSP_configureSPIMasterMode(), and McBSP_configureTxFrameSync().
static void McBSP_setRxMultichannelPartition (uint32_t base, const McBSP_MultichannelPartition partition) inline static
Set Multichannel receiver partitions.
Parameters
base is the base address of the McBSP module.
partition is the number of partitions.
This function sets the partitions for Multichannel receiver. Valid values for partition are MCBSP_MULTICHANNEL_TWO_PARTITION or MCBSP_MULTICHANNEL_EIGHT_PARTITION for 2 and 8 partitions respectively.
Returns
None.
References ASSERT, HWREGH, MCBSP_MCR1_RMCME, and MCBSP_O_MCR1.
Referenced by McBSP_configureRxMultichannel().
static void McBSP_setRxTwoPartitionBlock (uint32_t base, const McBSP_PartitionBlock block) inline static
Sets block to receiver in two partition configuration.
Parameters
base is the base address of the McBSP module.
block is the block to assign to the partition.
This function assigns the block the user provides to the appropriate receiver partition. If user sets the value of block to 0,2,4 or 6 the API will assign the blocks to partition A. If values 1,3,5,or 7 are set to block, then the API assigns the block to partition B.
Note
This function should be used with the two partition configuration only and not with eight partition configuration.
Returns
None.
References ASSERT, HWREGH, MCBSP_MCR1_RPABLK_M, MCBSP_MCR1_RPBBLK_M, and MCBSP_O_MCR1.
Referenced by McBSP_configureRxMultichannel().
static uint16_t McBSP_getRxActiveBlock (uint32_t base) inline static
Returns the current active receiver block number.
Parameters
base is the base address of the McBSP module.
This function returns the current active receiver block involved in McBSP reception.
Returns
Active block in McBSP reception. Returned values range from 0 to 7 representing the respective active block number .
References ASSERT, HWREGH, MCBSP_MCR1_RCBLK_M, MCBSP_MCR1_RCBLK_S, and MCBSP_O_MCR1.
static void McBSP_setRxChannelMode (uint32_t base, const McBSP_RxChannelMode channelMode) inline static
Configure channel selection mode for receiver.
Parameters
base is the base address of the McBSP module.
channelMode is the channel selection mode.
This function configures the channel selection mode. The following are valid values for channelMode:
MCBSP_ALL_RX_CHANNELS_ENABLED - enables all channels.
MCBSP_RX_CHANNEL_SELECTION_ENABLED - lets the user enable desired channels by using McBSP_enableRxChannel().
Returns
None.
References ASSERT, HWREGH, MCBSP_MCR1_RMCM, and MCBSP_O_MCR1.
Referenced by McBSP_configureRxMultichannel().
static void McBSP_setTxMultichannelPartition (uint32_t base, const McBSP_MultichannelPartition partition) inline static
Set Multichannel transmitter partitions.
Parameters
base is the base address of the McBSP module.
partition is the number of partitions.
This function sets the partitions for Multichannel transmitter. Valid values for partition are MCBSP_MULTICHANNEL_TWO_PARTITION or MCBSP_MULTICHANNEL_EIGHT_PARTITION for 2 and 8 partitions respectively.
Returns
None.
References ASSERT, HWREGH, MCBSP_MCR2_XMCME, and MCBSP_O_MCR2.
Referenced by McBSP_configureTxMultichannel().
static void McBSP_setTxTwoPartitionBlock (uint32_t base, const McBSP_PartitionBlock block) inline static
Sets block to transmitter in two partition configuration.
Parameters
base is the base address of the McBSP module.
block is the block to assign to the partition.
This function assigns the block the user provides to the appropriate transmitter partition. If user sets the value of block to 0,2,4 or 6 the API will assign the blocks to partition A. If values 1,3,5,or 7 are set to block, then the API assigns the block to partition B.
Note
This function should be used with the two partition configuration only and not with eight partition configuration.
Returns
None.
References ASSERT, HWREGH, MCBSP_MCR2_XPABLK_M, MCBSP_MCR2_XPBBLK_M, and MCBSP_O_MCR2.
Referenced by McBSP_configureTxMultichannel().
static uint16_t McBSP_getTxActiveBlock (uint32_t base) inline static
Returns the current active transmitter block number.
Parameters
base is the base address of the McBSP module.
This function returns the current active transmitter block involved in McBSP transmission.
Returns
Active block in McBSP transmission. Returned values range from 0 to 7 representing the respective active block number.
References ASSERT, HWREGH, MCBSP_MCR2_XCBLK_M, MCBSP_MCR2_XCBLK_S, and MCBSP_O_MCR2.
static void McBSP_setTxChannelMode (uint32_t base, const McBSP_TxChannelMode channelMode) inline static
Configure channel selection mode for transmitter.
Parameters
base is the base address of the McBSP module.
channelMode is the channel selection mode.
This function configures the channel selection mode. The following are valid values for channelMode:
MCBSP_ALL_TX_CHANNELS_ENABLED - enables and unmasks all channels
MCBSP_TX_CHANNEL_SELECTION_ENABLED - lets the user enable and unmask desired channels by using McBSP_enableTxChannel()
MCBSP_ENABLE_MASKED_TX_CHANNEL_SELECTION - All channels enables but until enabled by McBSP_enableTxChannel()
MCBSP_SYMMERTIC_RX_TX_SELECTION - Symmetric transmission and reception.
Returns
None.
References ASSERT, HWREGH, MCBSP_MCR2_XMCM_M, and MCBSP_O_MCR2.
Referenced by McBSP_configureTxMultichannel().
static void McBSP_setTxFrameSyncSource (uint32_t base, const McBSP_TxFrameSyncSource syncSource) inline static
Select the transmitter frame sync signal source.
Parameters
base is the base address of the McBSP module.
syncSource is the transmitter frame sync source.
This function sets external or internal sync signal source based on the syncSource selection. Valid input for syncSource are:
MCBSP_TX_EXTERNAL_FRAME_SYNC_SOURCE - frame sync signal is supplied externally by pin FSX.
MCBSP_TX_INTERNAL_FRAME_SYNC_SOURCE - frame sync signal is supplied internally.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_PCR, and MCBSP_PCR_FSXM.
Referenced by McBSP_configureSPIMasterMode(), McBSP_configureSPISlaveMode(), and McBSP_configureTxFrameSync().
static void McBSP_setRxFrameSyncSource (uint32_t base, const McBSP_RxFrameSyncSource syncSource) inline static
Select receiver frame sync signal source.
Parameters
base is the base address of the McBSP module.
syncSource is the receiver frame sync source.
This function sets external or internal sync signal source based on the syncSource selection. Valid input for syncSource are:
MCBSP_RX_EXTERNAL_FRAME_SYNC_SOURCE - frame sync signal is supplied externally by pin FSR.
MCBSP_RX_INTERNAL_FRAME_SYNC_SOURCE - frame sync signal is supplied by SRG.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_PCR, and MCBSP_PCR_FSRM.
Referenced by McBSP_configureRxFrameSync().
static void McBSP_setTxClockSource (uint32_t base, const McBSP_TxClockSource clockSource) inline static
Configures the Transmit clock source.
Parameters
base is the base address of the McBSP module.
clockSource is clock source for the transmission pin.
This function configures the clock source for the transmitter. Valid input for rxClockSource are:
MCBSP_INTERNAL_TX_CLOCK_SOURCE - internal clock source. SRG is the source.
MCBSP_EXTERNAL_TX_CLOCK_SOURCE - external clock source.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_PCR, and MCBSP_PCR_CLKXM.
Referenced by McBSP_configureSPIMasterMode(), McBSP_configureSPISlaveMode(), and McBSP_configureTxClock().
static void McBSP_setRxClockSource (uint32_t base, const McBSP_RxClockSource clockSource) inline static
Configures the Receive clock source.
Parameters
base is the base address of the McBSP module.
clockSource is clock source for the reception pin.
This function configures the clock source for the receiver. Valid input for base are:
MCBSP_INTERNAL_RX_CLOCK_SOURCE - internal clock source. Sample Rate Generator will be used.
MCBSP_EXTERNAL_RX_CLOCK_SOURCE - external clock will drive the data.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_PCR, and MCBSP_PCR_CLKRM.
Referenced by McBSP_configureRxClock().
static void McBSP_setTxFrameSyncPolarity (uint32_t base, const McBSP_TxFrameSyncPolarity syncPolarity) inline static
Sets transmitter frame sync polarity.
Parameters
base is the base address of the McBSP module.
syncPolarity is the polarity of frame sync pulse.
This function sets the polarity (rising or falling edge)of the frame sync on FSX pin. Use MCBSP_TX_FRAME_SYNC_POLARITY_LOW for active low frame sync pulse and MCBSP_TX_FRAME_SYNC_POLARITY_HIGH for active high sync pulse.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_PCR, and MCBSP_PCR_FSXP.
Referenced by McBSP_configureSPIMasterMode(), McBSP_configureSPISlaveMode(), and McBSP_configureTxFrameSync().
static void McBSP_setRxFrameSyncPolarity (uint32_t base, const McBSP_RxFrameSyncPolarity syncPolarity) inline static
Sets receiver frame sync polarity.
Parameters
base is the base address of the McBSP module.
syncPolarity is the polarity of frame sync pulse.
This function sets the polarity (rising or falling edge)of the frame sync on FSR pin. Use MCBSP_RX_FRAME_SYNC_POLARITY_LOW for active low frame sync pulse and MCBSP_RX_FRAME_SYNC_POLARITY_HIGH for active high sync pulse.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_PCR, and MCBSP_PCR_FSRP.
Referenced by McBSP_configureRxFrameSync().
static void McBSP_setTxClockPolarity (uint32_t base, const McBSP_TxClockPolarity clockPolarity) inline static
Sets transmitter clock polarity when using external clock source.
Parameters
base is the base address of the McBSP module.
clockPolarity is the polarity of external clock.
This function sets the polarity (rising or falling edge) of the transmitter clock on MCLKX pin. Valid values for clockPolarity are:
MCBSP_TX_POLARITY_RISING_EDGE for rising edge.
MCBSP_TX_POLARITY_FALLING_EDGE for falling edge.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_PCR, and MCBSP_PCR_CLKXP.
Referenced by McBSP_configureRxClock(), McBSP_configureSPIMasterMode(), McBSP_configureSPISlaveMode(), and McBSP_configureTxClock().
static void McBSP_setRxClockPolarity (uint32_t base, const McBSP_RxClockPolarity clockPolarity) inline static
Sets receiver clock polarity when using external clock source.
Parameters
base is the base address of the McBSP module.
clockPolarity is the polarity of external clock.
This function sets the polarity (rising or falling edge) of the receiver clock on MCLKR pin. If external clock is used, the polarity will affect CLKG signal. Valid values for clockPolarity are:
MCBSP_RX_POLARITY_RISING_EDGE for rising edge.
MCBSP_RX_POLARITY_FALLING_EDGE for falling edge.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_PCR, and MCBSP_PCR_CLKRP.
Referenced by McBSP_configureRxClock(), and McBSP_configureTxClock().
static uint16_t McBSP_read16bitData (uint32_t base) inline static
Read 8,12 or 16 bit data word from McBSP data receive registers.
Parameters
base is the base address of the McBSP port.
This function returns the data value in data receive register.
Returns
received data.
References ASSERT, HWREGH, and MCBSP_O_DRR1.
Referenced by McBSP_receive16BitDataBlocking(), and McBSP_receive16BitDataNonBlocking().
static uint32_t McBSP_read32bitData (uint32_t base) inline static
Read 20, 24 or 32 bit data word from McBSP data receive registers.
Parameters
base is the base address of the McBSP port.
This function returns the data values in data receive registers.
Returns
received data.
References ASSERT, HWREGH, MCBSP_O_DRR1, and MCBSP_O_DRR2.
Referenced by McBSP_receive32BitDataBlocking(), and McBSP_receive32BitDataNonBlocking().
static void McBSP_write16bitData (uint32_t base, uint16_t data) inline static
Write 8,12 or 16 bit data word to McBSP data transmit registers.
Parameters
base is the base address of the McBSP port.
data is the data to be written.
This function writes 8,12 or 16 bit data to data transmit register.
Returns
None.
References ASSERT, HWREGH, and MCBSP_O_DXR1.
Referenced by McBSP_transmit16BitDataBlocking(), and McBSP_transmit16BitDataNonBlocking().
static void McBSP_write32bitData (uint32_t base, uint32_t data) inline static
Write 20, 24 or 32 bit data word to McBSP data transmit registers.
Parameters
base is the base address of the McBSP port.
data is the data to be written.
This function writes 20, 24 or 32 bit data to data transmit registers.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_DXR1, and MCBSP_O_DXR2.
Referenced by McBSP_transmit32BitDataBlocking(), and McBSP_transmit32BitDataNonBlocking().
static uint16_t McBSP_getLeftJustifyData (uint16_t data, const McBSP_CompandingType compandingType) inline static
Return left justified for data for U Law or A Law companding.
Parameters
data is the 14 bit word.
compandingType specifies the type comapnding desired.
This functions returns U law or A law adjusted word.
Returns
U law or A law left justified word.
static void McBSP_enableRxInterrupt (uint32_t base) inline static
Enable Recieve Interrupt.
Parameters
base is the base address of the McBSP module.
This function enables Recieve Interrupt on RRDY.
Returns
None.
References ASSERT, HWREGH, MCBSP_MFFINT_RINT, and MCBSP_O_MFFINT.
static void McBSP_disableRxInterrupt (uint32_t base) inline static
Disable Recieve Interrupt.
Parameters
base is the base address of the McBSP module.
This function disables Recieve Interrupt on RRDY.
Returns
None.
References ASSERT, HWREGH, MCBSP_MFFINT_RINT, and MCBSP_O_MFFINT.
static void McBSP_enableTxInterrupt (uint32_t base) inline static
Enable Transmit Interrupt.
Parameters
base is the base address of the McBSP module.
This function enables Transmit Interrupt on XRDY.
Returns
None.
References ASSERT, HWREGH, MCBSP_MFFINT_XINT, and MCBSP_O_MFFINT.
static void McBSP_disableTxInterrupt (uint32_t base) inline static
Disable Transmit Interrupt.
Parameters
base is the base address of the McBSP module.
This function disables Transmit Interrupt on XRDY.
Returns
None.
References ASSERT, HWREGH, MCBSP_MFFINT_XINT, and MCBSP_O_MFFINT.
void McBSP_transmit16BitDataNonBlocking (uint32_t base, uint16_t data)
Write 8,12 or 16 bit data word to McBSP data transmit registers
Parameters
base is the base address of the McBSP port.
data is the data to be written.
This function sends 16 bit or less data to the transmitter buffer.
Returns
None.
None.
References ASSERT, and McBSP_write16bitData().
void McBSP_transmit16BitDataBlocking (uint32_t base, uint16_t data)
Write 8,12 or 16 bit data word to McBSP data transmit registers
Parameters
base is the base address of the McBSP port.
data is the data to be written.
This function sends 16 bit or less data to the transmitter buffer. If transmit buffer is not ready the function will wait until transmit buffer is empty. If the transmitter buffer is empty the data will be written to the data registers.
Returns
None.
References ASSERT, McBSP_isTxReady(), and McBSP_write16bitData().
void McBSP_transmit32BitDataNonBlocking (uint32_t base, uint32_t data)
Write 20 , 24 or 32 bit data word to McBSP data transmit registers
Parameters
base is the base address of the McBSP port.
data is the data to be written.
This function sends 20 , 24 or 32 bit data to the transmitter buffer. If the transmitter buffer is empty the data will be written to the data registers.
Returns
None.
References ASSERT, and McBSP_write32bitData().
void McBSP_transmit32BitDataBlocking (uint32_t base, uint32_t data)
Write 20 , 24 or 32 bit data word to McBSP data transmit registers
Parameters
base is the base address of the McBSP port.
data is the data to be written.
This function sends 20 , 24 or 32 bit data to the transmitter buffer. If transmit buffer is not ready the function will wait until transmit buffer is empty. If the transmitter buffer is empty the data will be written to the data registers.
Returns
None.
References ASSERT, McBSP_isTxReady(), and McBSP_write32bitData().
void McBSP_receive16BitDataNonBlocking (uint32_t base, uint16_t * receiveData)
Read 8,12 or 16 bit data word from McBSP data receive registers
Parameters
base is the base address of the McBSP port.
receiveData is the pointer to the receive data.
This function reads 8,12 or 16 bit data from the receiver buffer. If the receiver buffer has new data, the data will be read.
Returns
None.
References ASSERT, and McBSP_read16bitData().
void McBSP_receive16BitDataBlocking (uint32_t base, uint16_t * receiveData)
Read 8,12 or 16 bit data word from McBSP data receive registers
Parameters
base is the base address of the McBSP port.
receiveData is the pointer to the receive data.
This function reads 8,12 or 16 bit data from the receiver buffer. If receiver buffer is not ready the function will wait until receiver buffer has new data. If the receiver buffer has new data, the data will be read.
Returns
None.
References ASSERT, McBSP_isRxReady(), and McBSP_read16bitData().
void McBSP_receive32BitDataNonBlocking (uint32_t base, uint32_t * receiveData)
Read 20, 24 or 32 bit data word from McBSP data receive registers
Parameters
base is the base address of the McBSP port.
receiveData is the pointer to the receive data.
This function reads 20, 24 or 32 bit data from the receiver buffer. If the receiver buffer has new data, the data will be read.
Returns
None.
References ASSERT, and McBSP_read32bitData().
void McBSP_receive32BitDataBlocking (uint32_t base, uint32_t * receiveData)
Read 20, 24 or 32 bit data word from McBSP data receive registers
Parameters
base is the base address of the McBSP port.
receiveData is the pointer to the receive data.
This function reads 20, 24 or 32 bit data from the receiver buffer. If receiver buffer is not ready the function will wait until receiver buffer has new data. If the receiver buffer has new data, the data will be read.
Returns
None.
References ASSERT, McBSP_isRxReady(), and McBSP_read32bitData().
void McBSP_setRxDataSize (uint32_t base, const McBSP_DataPhaseFrame dataFrame, const McBSP_DataBitsPerWord bitsPerWord, uint16_t wordsPerFrame)
Sets number of words per frame and bits per word for data Reception.
Parameters
base is the base address of the McBSP module.
dataFrame is the data frame phase.
bitsPerWord is the number of bits per word.
wordsPerFrame is the number of words per frame per phase.
This function sets the number of bits per word and the number of words per frame for the given phase. Valid inputs for phase are MCBSP_PHASE_ONE_FRAME or MCBSP_PHASE_TWO_FRAME representing the first or second frame phase respectively. Valid value for bitsPerWord are:
MCBSP_BITS_PER_WORD_8 8 bit word.
MCBSP_BITS_PER_WORD_12 12 bit word.
MCBSP_BITS_PER_WORD_16 16 bit word.
MCBSP_BITS_PER_WORD_20 20 bit word.
MCBSP_BITS_PER_WORD_24 24 bit word.
MCBSP_BITS_PER_WORD_32 32 bit word. The maximum value for wordsPerFrame is 127 (128 - 1)representing 128 words.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_RCR1, MCBSP_O_RCR2, MCBSP_PHASE_ONE_FRAME, MCBSP_RCR1_M, MCBSP_RCR1_RFRLEN1_S, MCBSP_RCR2_M, and MCBSP_RCR2_RFRLEN2_S.
Referenced by McBSP_configureRxDataFormat(), McBSP_configureSPIMasterMode(), and McBSP_configureSPISlaveMode().
void McBSP_setTxDataSize (uint32_t base, const McBSP_DataPhaseFrame dataFrame, const McBSP_DataBitsPerWord bitsPerWord, uint16_t wordsPerFrame)
Sets number of words per frame and bits per word for data Transmission.
Parameters
base is the base address of the McBSP module.
dataFrame is the data frame phase.
bitsPerWord is the number of bits per word.
wordsPerFrame is the number of words per frame per phase.
This function sets the number of bits per word and the number of words per frame for the given phase. Valid inputs for phase are MCBSP_PHASE_ONE_FRAME or MCBSP_PHASE_TWO_FRAME representing single or dual phase respectively. Valid values for bitsPerWord are:
MCBSP_BITS_PER_WORD_8 8 bit word.
MCBSP_BITS_PER_WORD_12 12 bit word.
MCBSP_BITS_PER_WORD_16 16 bit word.
MCBSP_BITS_PER_WORD_20 20 bit word.
MCBSP_BITS_PER_WORD_24 24 bit word.
MCBSP_BITS_PER_WORD_32 32 bit word. The maximum value for wordsPerFrame is 127 (128 - 1)representing 128 words.
Returns
None.
References ASSERT, HWREGH, MCBSP_O_XCR1, MCBSP_O_XCR2, MCBSP_PHASE_ONE_FRAME, MCBSP_XCR1_M, MCBSP_XCR1_XFRLEN1_S, MCBSP_XCR2_M, and MCBSP_XCR2_XFRLEN2_S.
Referenced by McBSP_configureSPIMasterMode(), McBSP_configureSPISlaveMode(), and McBSP_configureTxDataFormat().
void McBSP_disableRxChannel (uint32_t base, const McBSP_MultichannelPartition partition, uint16_t channel)
Disables a channel in an eight partition receiver
Parameters
base is the base address of the McBSP module.
partition is the partition of the channel.
channel is the receiver channel number to be enabled.
This function disables the given receiver channel number for the partition provided. Valid values for partition are MCBSP_MULTICHANNEL_TWO_PARTITION or MCBSP_MULTICHANNEL_EIGHT_PARTITION for 2 or 8 partitions respectively. Valid values for channel range from 0 to 127.
Returns
None.
References ASSERT, HWREGH, MCBSP_MULTICHANNEL_EIGHT_PARTITION, and MCBSP_O_RCERA.
void McBSP_enableRxChannel (uint32_t base, const McBSP_MultichannelPartition partition, uint16_t channel)
Enables a channel for eight partition receiver
Parameters
base is the base address of the McBSP module.
partition is the partition of the channel.
channel is the receiver channel number to be enabled.
This function enables the given receiver channel number for the partition provided. Valid values for partition are MCBSP_MULTICHANNEL_TWO_PARTITION or MCBSP_MULTICHANNEL_EIGHT_PARTITION for 2 or 8 partitions respectively. Valid values for channel range from 0 to 127.
Returns
None.
References ASSERT, HWREGH, MCBSP_MULTICHANNEL_EIGHT_PARTITION, and MCBSP_O_RCERA.
Referenced by McBSP_configureRxMultichannel().
void McBSP_disableTxChannel (uint32_t base, const McBSP_MultichannelPartition partition, uint16_t channel)
Disables a channel in an eight partition transmitter
Parameters
base is the base address of the McBSP module.
partition is the partition of the channel.
channel is the transmitter channel number to be enabled.
This function disables the given transmitter channel number for the partition provided. Valid values for partition are MCBSP_MULTICHANNEL_TWO_PARTITION or MCBSP_MULTICHANNEL_EIGHT_PARTITION for 2 or 8 partitions respectively. Valid values for channel range from 0 to 127.
Returns
None.
References ASSERT, HWREGH, MCBSP_MULTICHANNEL_EIGHT_PARTITION, and MCBSP_O_XCERA.
void McBSP_enableTxChannel (uint32_t base, const McBSP_MultichannelPartition partition, uint16_t channel)
Enables a channel for eight partition transmitter
Parameters
base is the base address of the McBSP module.
partition is the partition of the channel.
channel is the transmitter channel number to be enabled.
This function enables the given transmitter channel number for the partition provided. Valid values for partition are MCBSP_MULTICHANNEL_TWO_PARTITION or MCBSP_MULTICHANNEL_EIGHT_PARTITION for 2 or 8 partitions respectively. Valid values for channel range from 0 to 127.
Returns
None.
References ASSERT, HWREGH, MCBSP_MULTICHANNEL_EIGHT_PARTITION, and MCBSP_O_XCERA.
Referenced by McBSP_configureTxMultichannel().
void McBSP_configureTxClock (uint32_t base, const McBSP_ClockParams * ptrClockParams)
Configures transmitter clock
Parameters
base is the base address of the McBSP module.
ptrClockParams is a pointer to a structure containing clock parameters McBSP_ClockParams. This function sets up the transmitter clock. The following are valid values and ranges for the parameters of the McBSP_TxFsyncParams.
clockSRGSyncFSR - true to sync with signal on FSR pin, false to ignore signal on FSR pin. the pulse on FSR pin.
clockSRGDivider - Maximum valid value is 255.
clockSource - MCBSP_EXTERNAL_TX_CLOCK_SOURCE or MCBSP_INTERNAL_TX_CLOCK_SOURCE
clockTxSRGSource - MCBSP_SRG_TX_CLOCK_SOURCE_LSPCLK or MCBSP_SRG_TX_CLOCK_SOURCE_MCLKR_PIN
clockMCLKXPolarity - Output polarity on MCLKX pin.
MCBSP_TX_POLARITY_RISING_EDGE
MCBSP_TX_POLARITY_FALLING_EDGE
clockMCLKRPolarity - Input polarity on MCLKR pin (if SRG is sourced from MCLKR pin).
MCBSP_RX_POLARITY_FALLING_EDGE
MCBSP_RX_POLARITY_RISING_EDGE
Note
Make sure the clock divider is such that, the McBSP clock is not running faster than 1/2 the speed of the source clock.
Returns
None.
References ASSERT, McBSP_ClockParams::clockMCLKRPolarity, McBSP_ClockParams::clockMCLKXPolarity, McBSP_ClockParams::clockSourceTx, McBSP_ClockParams::clockSRGDivider, McBSP_ClockParams::clockSRGSyncFlag, McBSP_ClockParams::clockTxSRGSource, McBSP_disableSRGSyncFSR(), McBSP_enableSRGSyncFSR(), MCBSP_INTERNAL_TX_CLOCK_SOURCE, McBSP_setRxClockPolarity(), McBSP_setSRGDataClockDivider(), McBSP_setTxClockPolarity(), McBSP_setTxClockSource(), McBSP_setTxSRGClockSource(), and MCBSP_SRG_TX_CLOCK_SOURCE_MCLKR_PIN.
void McBSP_configureRxClock (uint32_t base, const McBSP_ClockParams * ptrClockParams)
Configures receiver clock
Parameters
base is the base address of the McBSP module.
ptrClockParams is a pointer to a structure containing clock parameters McBSP_ClockParams. This function sets up the receiver clock. The following are valid values and ranges for the parameters of the McBSP_TxFsyncParams.
clockSRGSyncFlag - true to sync with signal on FSR pin, false to ignore the pulse on FSR pin.
clockSRGDivider - Maximum valid value is 255.
clockSource - MCBSP_EXTERNAL_RX_CLOCK_SOURCE or MCBSP_INTERNAL_RX_CLOCK_SOURCE
clockRxSRGSource - MCBSP_SRG_RX_CLOCK_SOURCE_LSPCLK or MCBSP_SRG_RX_CLOCK_SOURCE_MCLKX_PIN
clockMCLKRPolarity- output polarity on MCLKR pin.
MCBSP_RX_POLARITY_FALLING_EDGE or
MCBSP_RX_POLARITY_RISING_EDGE
clockMCLKXPolarity- Input polarity on MCLKX pin (if SRG is sourced from MCLKX pin).
MCBSP_TX_POLARITY_RISING_EDGE or
MCBSP_TX_POLARITY_FALLING_EDGE
Note
Make sure the clock divider is such that, the McBSP clock is not running faster than 1/2 the speed of the source clock.
Returns
None.
References ASSERT, McBSP_ClockParams::clockMCLKRPolarity, McBSP_ClockParams::clockMCLKXPolarity, McBSP_ClockParams::clockRxSRGSource, McBSP_ClockParams::clockSourceRx, McBSP_ClockParams::clockSRGDivider, MCBSP_INTERNAL_RX_CLOCK_SOURCE, McBSP_setRxClockPolarity(), McBSP_setRxClockSource(), McBSP_setRxSRGClockSource(), McBSP_setSRGDataClockDivider(), McBSP_setTxClockPolarity(), and MCBSP_SRG_RX_CLOCK_SOURCE_MCLKX_PIN.
void McBSP_configureTxFrameSync (uint32_t base, const McBSP_TxFsyncParams * ptrFsyncParams)
Configures transmitter frame sync.
Parameters
base is the base address of the McBSP module.
ptrFsyncParams is a pointer to a structure containing frame sync parameters McBSPTxFsyncParams. This function sets up the transmitter frame sync. The following are valid values and ranges for the parameters of the McBSPTxFsyncParams.
syncSRGSyncFSRFlag - true to sync with signal on FSR pin, false to ignore the pulse on FSR pin.This value has to be similar to the value of McBSP_ClockParams.clockSRGSyncFlag.
syncErrorDetect - true to enable frame sync error detect. false to disable.
syncClockDivider - Maximum valid value is 4095.
syncPulseDivider - Maximum valid value is 255.
syncSourceTx - MCBSP_TX_INTERNAL_FRAME_SYNC_SOURCE or MCBSP_TX_EXTERNAL_FRAME_SYNC_SOURCE
syncIntSource - MCBSP_TX_INTERNAL_FRAME_SYNC_DATA or MCBSP_TX_INTERNAL_FRAME_SYNC_SRG
syncFSXPolarity - MCBSP_TX_FRAME_SYNC_POLARITY_LOW or MCBSP_TX_FRAME_SYNC_POLARITY_HIGH.
Returns
None.
References ASSERT, McBSP_disableTxFrameSyncErrorDetection(), McBSP_enableTxFrameSyncErrorDetection(), McBSP_setFrameSyncPulsePeriod(), McBSP_setFrameSyncPulseWidthDivider(), McBSP_setTxFrameSyncPolarity(), McBSP_setTxFrameSyncSource(), McBSP_setTxInternalFrameSyncSource(), MCBSP_TX_INTERNAL_FRAME_SYNC_SOURCE, MCBSP_TX_INTERNAL_FRAME_SYNC_SRG, McBSP_TxFsyncParams::syncClockDivider, McBSP_TxFsyncParams::syncErrorDetect, McBSP_TxFsyncParams::syncFSXPolarity, McBSP_TxFsyncParams::syncIntSource, McBSP_TxFsyncParams::syncPulseDivider, McBSP_TxFsyncParams::syncSourceTx, and McBSP_TxFsyncParams::syncSRGSyncFSRFlag.
void McBSP_configureRxFrameSync (uint32_t base, const McBSP_RxFsyncParams * ptrFsyncParams)
Configures receiver frame sync.
Parameters
base is the base address of the McBSP module.
ptrFsyncParams is a pointer to a structure containing frame sync parameters McBSP_RxFsyncParams. This function sets up the receiver frame sync. The following are valid values and ranges for the parameters of the McBSPTxFsyncParams.
syncSRGSyncFSRFlag - true to sync with signal on FSR pin, false to ignore the pulse on FSR pin. This value has to be similar to the value of McBSP_ClockParams.clockSRGSyncFlag.
syncErrorDetect - true to enable frame sync error detect. false to disable.
syncClockDivider - Maximum valid value is 4095.
syncPulseDivider - Maximum valid value is 255.
syncSourceRx - MCBSP_RX_INTERNAL_FRAME_SYNC_SOURCE or MCBSP_RX_EXTERNAL_FRAME_SYNC_SOURCE
syncFSRPolarity - MCBSP_RX_FRAME_SYNC_POLARITY_LOW or MCBSP_RX_FRAME_SYNC_POLARITY_HIGH
Returns
None.
References ASSERT, McBSP_disableTxFrameSyncErrorDetection(), McBSP_enableRxFrameSyncErrorDetection(), MCBSP_RX_INTERNAL_FRAME_SYNC_SOURCE, McBSP_setFrameSyncPulsePeriod(), McBSP_setFrameSyncPulseWidthDivider(), McBSP_setRxFrameSyncPolarity(), McBSP_setRxFrameSyncSource(), McBSP_RxFsyncParams::syncClockDivider, McBSP_RxFsyncParams::syncErrorDetect, McBSP_RxFsyncParams::syncFSRPolarity, McBSP_RxFsyncParams::syncPulseDivider, McBSP_RxFsyncParams::syncSourceRx, and McBSP_RxFsyncParams::syncSRGSyncFSRFlag.
void McBSP_configureTxDataFormat (uint32_t base, const McBSP_TxDataParams * ptrDataParams)
Configures transmitter data format.
Parameters
base is the base address of the McBSP module.
ptrDataParams is a pointer to a structure containing data format parameters McBSPTxDataParams. This function sets up the transmitter data format and properties. The following are valid values and ranges for the parameters of the McBSPTxDataParams.
loopbackModeFlag - true for digital loop-back mode. false for no loop-back mode.
twoPhaseModeFlag - true for two phase mode. false for single phase mode.
pinDelayEnableFlag - true to enable DX pin delay. false to disable DX pin delay.
phase1FrameLength - maximum value of 127.
phase2FrameLength - maximum value of 127.
clockStopMode - MCBSP_CLOCK_SPI_MODE_NO_DELAY or MCBSP_CLOCK_SPI_MODE_DELAY
phase1WordLength - MCBSP_BITS_PER_WORD_x , x = 8,12,16,20,24,32
phase2WordLength - MCBSP_BITS_PER_WORD_x , x = 8,12,16,20,24,32
compandingMode - MCBSP_COMPANDING_NONE, MCBSP_COMPANDING_NONE_LSB_FIRST MCBSP_COMPANDING_U_LAW_SET or MCBSP_COMPANDING_A_LAW_SET.
dataDelayBits - MCBSP_DATA_DELAY_BIT_0, MCBSP_DATA_DELAY_BIT_1 or MCBSP_DATA_DELAY_BIT_2
interruptMode - MCBSP_TX_ISR_SOURCE_TX_READY, MCBSP_TX_ISR_SOURCE_END_OF_BLOCK, MCBSP_TX_ISR_SOURCE_FRAME_SYNC or MCBSP_TX_ISR_SOURCE_SYNC_ERROR
Note - When using companding,phase1WordLength and phase2WordLength must be 8 bits wide.
Returns
None.
References ASSERT, McBSP_TxDataParams::compandingMode, McBSP_TxDataParams::dataDelayBits, McBSP_TxDataParams::interruptMode, McBSP_TxDataParams::loopbackModeFlag, MCBSP_CLOCK_MCBSP_MODE, McBSP_disableDxPinDelay(), McBSP_disableLoopback(), McBSP_disableTwoPhaseTx(), McBSP_enableDxPinDelay(), McBSP_enableLoopback(), McBSP_enableTwoPhaseTx(), MCBSP_PHASE_ONE_FRAME, MCBSP_PHASE_TWO_FRAME, McBSP_setClockStopMode(), McBSP_setTxCompandingMode(), McBSP_setTxDataDelayBits(), McBSP_setTxDataSize(), McBSP_setTxInterruptSource(), McBSP_TxDataParams::phase1FrameLength, McBSP_TxDataParams::phase1WordLength, McBSP_TxDataParams::phase2FrameLength, McBSP_TxDataParams::phase2WordLength, McBSP_TxDataParams::pinDelayEnableFlag, and McBSP_TxDataParams::twoPhaseModeFlag.
void McBSP_configureRxDataFormat (uint32_t base, const McBSP_RxDataParams * ptrDataParams)
Configures receiver data format.
Parameters
base is the base address of the McBSP module.
ptrDataParams is a pointer to a structure containing data format parameters McBSP_RxDataParams. This function sets up the transmitter data format and properties. The following are valid values and ranges for the parameters of the McBSP_RxDataParams.
loopbackModeFlag - true for digital loop-back mode. false for non loop-back mode.
twoPhaseModeFlag - true for two phase mode. false for single phase mode.
phase1FrameLength - maximum value of 127.
phase2FrameLength - maximum value of 127.
phase1WordLength - MCBSP_BITS_PER_WORD_x , x = 8,12,16,20,24,32
phase2WordLength - MCBSP_BITS_PER_WORD_x , x = 8,12,16,20,24,32
compandingMode - MCBSP_COMPANDING_NONE, MCBSP_COMPANDING_NONE_LSB_FIRST MCBSP_COMPANDING_U_LAW_SET or MCBSP_COMPANDING_A_LAW_SET.
dataDelayBits - MCBSP_DATA_DELAY_BIT_0, MCBSP_DATA_DELAY_BIT_1 or MCBSP_DATA_DELAY_BIT_2
signExtMode - MCBSP_RIGHT_JUSTIFY_FILL_ZERO, MCBSP_RIGHT_JUSTIFY_FILL_SIGN or MCBSP_LEFT_JUSTIFY_FILL_ZER0
interruptMode - MCBSP_RX_ISR_SOURCE_SERIAL_WORD, MCBSP_RX_ISR_SOURCE_END_OF_BLOCK, MCBSP_RX_ISR_SOURCE_FRAME_SYNC or MCBSP_RX_ISR_SOURCE_SYNC_ERROR
Note - When using companding,phase1WordLength and phase2WordLength must be 8 bits wide.
Returns
None.
References ASSERT, McBSP_RxDataParams::compandingMode, McBSP_RxDataParams::dataDelayBits, McBSP_RxDataParams::interruptMode, McBSP_RxDataParams::loopbackModeFlag, MCBSP_CLOCK_MCBSP_MODE, McBSP_disableLoopback(), McBSP_disableTwoPhaseRx(), McBSP_enableLoopback(), McBSP_enableTwoPhaseRx(), MCBSP_PHASE_ONE_FRAME, MCBSP_PHASE_TWO_FRAME, McBSP_setClockStopMode(), McBSP_setRxCompandingMode(), McBSP_setRxDataDelayBits(), McBSP_setRxDataSize(), McBSP_setRxInterruptSource(), McBSP_setRxSignExtension(), McBSP_RxDataParams::phase1FrameLength, McBSP_RxDataParams::phase1WordLength, McBSP_RxDataParams::phase2FrameLength, McBSP_RxDataParams::phase2WordLength, McBSP_RxDataParams::signExtMode, and McBSP_RxDataParams::twoPhaseModeFlag.
uint16_t McBSP_configureTxMultichannel (uint32_t base, const McBSP_TxMultichannelParams * ptrMchnParams)
Configures transmitter multichannel.
Parameters
base is the base address of the McBSP module.
ptrMchnParams is a pointer to a structure containing multichannel parameters McBSP_TxMultichannelParams.
This function sets up the transmitter multichannel mode. The following are valid values and ranges for the parameters of the McBSP_TxMultichannelParams.
channelCount - Maximum value of 128 for partition 8 Maximum value of 32 for partition 2
ptrChannelsList - Pointer to an array of size channelCount that has unique channels.
multichannelMode - MCBSP_ALL_TX_CHANNELS_ENABLED, MCBSP_TX_CHANNEL_SELECTION_ENABLED, MCBSP_ENABLE_MASKED_TX_CHANNEL_SELECTION or MCBSP_SYMMERTIC_RX_TX_SELECTION
partition - MCBSP_MULTICHANNEL_TWO_PARTITION or MCBSP_MULTICHANNEL_EIGHT_PARTITION
Note
- In 2 partition mode only channels that belong to a single even or odd block number should be listed. It is valid to have an even and odd channels. For example you can have channels [48 -63] and channels [96 - 111] enables as one belongs to an even block and the other to an odd block or two partitions. But not channels [48 - 63] and channels [112 - 127] since they both are even blocks or similar partitions.
Returns
returns the following error codes.
MCBSP_ERROR_EXCEEDED_CHANNELS - number of channels exceeds 128
MCBSP_ERROR_2_PARTITION_A - invalid channel combination for partition A
MCBSP_ERROR_2_PARTITION_B - invalid channel combination for partition B
MCBSP_ERROR_INVALID_MODE - invalid transmitter channel mode.
Returns the following error codes.
MCBSP_ERROR_EXCEEDED_CHANNELS - Exceeded number of channels.
MCBSP_ERROR_2_PARTITION_A - Error in 2 partition A setup.
MCBSP_ERROR_2_PARTITION_B - Error in 2 partition B setup.
MCBSP_ERROR_INVALID_MODE - Invalid mode.
References ASSERT, McBSP_TxMultichannelParams::channelCountTx, MCBSP_ALL_TX_CHANNELS_ENABLED, McBSP_disableTwoPhaseTx(), McBSP_enableTxChannel(), MCBSP_ERROR_2_PARTITION_A, MCBSP_ERROR_2_PARTITION_B, MCBSP_ERROR_EXCEEDED_CHANNELS, MCBSP_MULTICHANNEL_EIGHT_PARTITION, MCBSP_MULTICHANNEL_TWO_PARTITION, McBSP_setTxChannelMode(), McBSP_setTxMultichannelPartition(), McBSP_setTxTwoPartitionBlock(), McBSP_TxMultichannelParams::multichannelModeTx, McBSP_TxMultichannelParams::partitionTx, and McBSP_TxMultichannelParams::ptrChannelsListTx.
uint16_t McBSP_configureRxMultichannel (uint32_t base, const McBSP_RxMultichannelParams * ptrMchnParams)
Configures receiver multichannel.
Parameters
base is the base address of the McBSP module.
ptrMchnParams is a pointer to a structure containing multichannel parameters McBSP_RxMultiChannelParams.
This function sets up the receiver multichannel mode. The following are valid values and ranges for the parameters of the McBSPMultichannelParams.
channelCount - Maximum value of 128 for partition 8 Maximum value of 32 for partition 2
ptrChannelsList - Pointer to an array of size channelCount that has unique channels.
multichannelMode - MCBSP_ALL_RX_CHANNELS_ENABLED, MCBSP_RX_CHANNEL_SELECTION_ENABLED,
partition - MCBSP_MULTICHANNEL_TWO_PARTITION or MCBSP_MULTICHANNEL_EIGHT_PARTITION
Note
- In 2 partition mode only channels that belong to a single even or odd block number should be listed. It is valid to have an even and odd channels. For example you can have channels [48 - 63] and channels [96 - 111] enables as one belongs to an even block and the other to an odd block or two partitions. But not channels [48 - 63]and channels [112 - 127] since they both are even blocks or similar partitions.
Returns
returns the following error codes.
MCBSP_ERROR_EXCEEDED_CHANNELS - number of channels exceeds 128
MCBSP_ERROR_2_PARTITION_A - invalid channel combination for partition A
MCBSP_ERROR_2_PARTITION_B - invalid channel combination for partition B
MCBSP_ERROR_INVALID_MODE - invalid transmitter channel mode.
Returns the following error codes.
MCBSP_ERROR_EXCEEDED_CHANNELS - Exceeded number of channels.
MCBSP_ERROR_2_PARTITION_A - Error in 2 partition A setup.
MCBSP_ERROR_2_PARTITION_B - Error in 2 partition B setup.
MCBSP_ERROR_INVALID_MODE - Invalid mode.
References ASSERT, McBSP_RxMultichannelParams::channelCountRx, McBSP_disableTwoPhaseRx(), McBSP_enableRxChannel(), MCBSP_ERROR_2_PARTITION_A, MCBSP_ERROR_2_PARTITION_B, MCBSP_ERROR_EXCEEDED_CHANNELS, MCBSP_MULTICHANNEL_EIGHT_PARTITION, MCBSP_MULTICHANNEL_TWO_PARTITION, MCBSP_RX_CHANNEL_SELECTION_ENABLED, McBSP_setRxChannelMode(), McBSP_setRxMultichannelPartition(), McBSP_setRxTwoPartitionBlock(), McBSP_RxMultichannelParams::multichannelModeRx, McBSP_RxMultichannelParams::partitionRx, and McBSP_RxMultichannelParams::ptrChannelsListRx.
void McBSP_configureSPIMasterMode (uint32_t base, const McBSP_SPIMasterModeParams * ptrSPIMasterMode)
Configures McBSP in SPI master mode
Parameters
base is the base address of the McBSP module.
ptrSPIMasterMode is a pointer to a structure containing SPI parameters McBSP_SPIMasterModeParams. This function sets up the McBSP module in SPI master mode.The following are valid values and ranges for the parameters of the McBSP_SPIMasterModeParams.
loopbackModeFlag - true for digital loop-back false for no loop-back
clockStopMode - MCBSP_CLOCK_SPI_MODE_NO_DELAY or MCBSP_CLOCK_SPI_MODE_DELAY
wordLength - MCBSP_BITS_PER_WORD_x , x = 8,12,16,20,24,32
spiMode It represents the clock polarity can take values:
MCBSP_TX_POLARITY_RISING_EDGE or MCBSP_TX_POLARITY_FALLING_EDGE
clockSRGDivider - Maximum valid value is 255.
Note
Make sure the clock divider is such that, the McBSP clock is not running faster than 1/2 the speed of the source clock.
Returns
None.
References McBSP_SPIMasterModeParams::clockSRGDivider, McBSP_SPIMasterModeParams::clockStopMode, McBSP_SPIMasterModeParams::loopbackModeFlag, MCBSP_CLOCK_SPI_MODE_DELAY, MCBSP_CLOCK_SPI_MODE_NO_DELAY, MCBSP_DATA_DELAY_BIT_1, McBSP_disableLoopback(), McBSP_disableTwoPhaseTx(), McBSP_enableLoopback(), MCBSP_INTERNAL_TX_CLOCK_SOURCE, MCBSP_PHASE_ONE_FRAME, McBSP_setClockStopMode(), McBSP_setRxDataDelayBits(), McBSP_setRxDataSize(), McBSP_setSRGDataClockDivider(), McBSP_setTxClockPolarity(), McBSP_setTxClockSource(), McBSP_setTxDataDelayBits(), McBSP_setTxDataSize(), McBSP_setTxFrameSyncPolarity(), McBSP_setTxFrameSyncSource(), McBSP_setTxInternalFrameSyncSource(), McBSP_setTxSRGClockSource(), MCBSP_SRG_TX_CLOCK_SOURCE_LSPCLK, MCBSP_TX_FRAME_SYNC_POLARITY_LOW, MCBSP_TX_INTERNAL_FRAME_SYNC_DATA, MCBSP_TX_INTERNAL_FRAME_SYNC_SOURCE, McBSP_SPIMasterModeParams::spiMode, and McBSP_SPIMasterModeParams::wordLength.
void McBSP_configureSPISlaveMode (uint32_t base, const McBSP_SPISlaveModeParams * ptrSPISlaveMode)
Configures McBSP in SPI slave mode
Parameters
base is the base address of the McBSP module.
ptrSPISlaveMode is a pointer to a structure containing SPI parameters McBSP_SPISlaveModeParams. This function sets up the McBSP module in SPI slave mode.The following are valid values and ranges for the parameters of the McBSP_SPISlaveModeParams.
loopbackModeFlag - true for digital loop-back false for no loop-back
clockStopMode - MCBSP_CLOCK_SPI_MODE_NO_DELAY or MCBSP_CLOCK_SPI_MODE_DELAY
wordLength - MCBSP_BITS_PER_WORD_x , x = 8,12,16,20,24,32
spiMode It represents the clock polarity and can take values:
MCBSP_RX_POLARITY_FALLING_EDGE or MCBSP_RX_POLARITY_RISING_EDGE
Returns
None.
References McBSP_SPISlaveModeParams::clockStopMode, McBSP_SPISlaveModeParams::loopbackModeFlag, MCBSP_CLOCK_SPI_MODE_DELAY, MCBSP_CLOCK_SPI_MODE_NO_DELAY, MCBSP_DATA_DELAY_BIT_0, McBSP_disableLoopback(), McBSP_disableTwoPhaseTx(), McBSP_enableLoopback(), MCBSP_EXTERNAL_TX_CLOCK_SOURCE, MCBSP_PHASE_ONE_FRAME, McBSP_setClockStopMode(), McBSP_setRxDataDelayBits(), McBSP_setRxDataSize(), McBSP_setRxSRGClockSource(), McBSP_setSRGDataClockDivider(), McBSP_setTxClockPolarity(), McBSP_setTxClockSource(), McBSP_setTxDataDelayBits(), McBSP_setTxDataSize(), McBSP_setTxFrameSyncPolarity(), McBSP_setTxFrameSyncSource(), MCBSP_SRG_RX_CLOCK_SOURCE_LSPCLK, MCBSP_TX_EXTERNAL_FRAME_SYNC_SOURCE, MCBSP_TX_FRAME_SYNC_POLARITY_LOW, McBSP_SPISlaveModeParams::spiMode, and McBSP_SPISlaveModeParams::wordLength.
Copyright 2018, Texas Instruments Incorporated