Interrupt
Interrupt
Macros
#define INTERRUPT_CPU_INT1 0x1U
CPU Interrupt Number 1.
#define INTERRUPT_CPU_INT2 0x2U
CPU Interrupt Number 2.
#define INTERRUPT_CPU_INT3 0x4U
CPU Interrupt Number 3.
#define INTERRUPT_CPU_INT4 0x8U
CPU Interrupt Number 4.
#define INTERRUPT_CPU_INT5 0x10U
CPU Interrupt Number 5.
#define INTERRUPT_CPU_INT6 0x20U
CPU Interrupt Number 6.
#define INTERRUPT_CPU_INT7 0x40U
CPU Interrupt Number 7.
#define INTERRUPT_CPU_INT8 0x80U
CPU Interrupt Number 8.
#define INTERRUPT_CPU_INT9 0x100U
CPU Interrupt Number 9.
#define INTERRUPT_CPU_INT10 0x200U
CPU Interrupt Number 10.
#define INTERRUPT_CPU_INT11 0x400U
CPU Interrupt Number 11.
#define INTERRUPT_CPU_INT12 0x800U
CPU Interrupt Number 12.
#define INTERRUPT_CPU_INT13 0x1000U
CPU Interrupt Number 13.
#define INTERRUPT_CPU_INT14 0x2000U
CPU Interrupt Number 14.
#define INTERRUPT_CPU_DLOGINT 0x4000U
CPU Data Log Interrupt.
#define INTERRUPT_CPU_RTOSINT 0x8000U
CPU RTOS Interrupt.
#define INTERRUPT_ACK_GROUP1 0x1U
Acknowledge PIE Interrupt Group 1.
#define INTERRUPT_ACK_GROUP2 0x2U
Acknowledge PIE Interrupt Group 2.
#define INTERRUPT_ACK_GROUP3 0x4U
Acknowledge PIE Interrupt Group 3.
#define INTERRUPT_ACK_GROUP4 0x8U
Acknowledge PIE Interrupt Group 4.
#define INTERRUPT_ACK_GROUP5 0x10U
Acknowledge PIE Interrupt Group 5.
#define INTERRUPT_ACK_GROUP6 0x20U
Acknowledge PIE Interrupt Group 6.
#define INTERRUPT_ACK_GROUP7 0x40U
Acknowledge PIE Interrupt Group 7.
#define INTERRUPT_ACK_GROUP8 0x80U
Acknowledge PIE Interrupt Group 8.
#define INTERRUPT_ACK_GROUP9 0x100U
Acknowledge PIE Interrupt Group 9.
#define INTERRUPT_ACK_GROUP10 0x200U
Acknowledge PIE Interrupt Group 10.
#define INTERRUPT_ACK_GROUP11 0x400U
Acknowledge PIE Interrupt Group 11.
#define INTERRUPT_ACK_GROUP12 0x800U
Acknowledge PIE Interrupt Group 12.
Functions
static void Interrupt_defaultHandler (void)
static void Interrupt_illegalOperationHandler (void)
static void Interrupt_nmiHandler (void)
static bool Interrupt_enableMaster (void)
static bool Interrupt_disableMaster (void)
static void Interrupt_register (uint32_t interruptNumber, void(*handler)(void))
static void Interrupt_unregister (uint32_t interruptNumber)
static void Interrupt_enableInCPU (uint16_t cpuInterrupt)
static void Interrupt_disableInCPU (uint16_t cpuInterrupt)
static void Interrupt_clearACKGroup (uint16_t group)
void Interrupt_initModule (void)
void Interrupt_initVectorTable (void)
void Interrupt_enable (uint32_t interruptNumber)
void Interrupt_disable (uint32_t interruptNumber)
uint16_t __disable_interrupts (void)
uint16_t __enable_interrupts (void)
Detailed Description
Macro Definition Documentation
#define INTERRUPT_CPU_INT1 0x1U
CPU Interrupt Number 1.
#define INTERRUPT_CPU_INT2 0x2U
CPU Interrupt Number 2.
#define INTERRUPT_CPU_INT3 0x4U
CPU Interrupt Number 3.
#define INTERRUPT_CPU_INT4 0x8U
CPU Interrupt Number 4.
#define INTERRUPT_CPU_INT5 0x10U
CPU Interrupt Number 5.
#define INTERRUPT_CPU_INT6 0x20U
CPU Interrupt Number 6.
#define INTERRUPT_CPU_INT7 0x40U
CPU Interrupt Number 7.
#define INTERRUPT_CPU_INT8 0x80U
CPU Interrupt Number 8.
#define INTERRUPT_CPU_INT9 0x100U
CPU Interrupt Number 9.
#define INTERRUPT_CPU_INT10 0x200U
CPU Interrupt Number 10.
#define INTERRUPT_CPU_INT11 0x400U
CPU Interrupt Number 11.
#define INTERRUPT_CPU_INT12 0x800U
CPU Interrupt Number 12.
#define INTERRUPT_CPU_INT13 0x1000U
CPU Interrupt Number 13.
#define INTERRUPT_CPU_INT14 0x2000U
CPU Interrupt Number 14.
#define INTERRUPT_CPU_DLOGINT 0x4000U
CPU Data Log Interrupt.
#define INTERRUPT_CPU_RTOSINT 0x8000U
CPU RTOS Interrupt.
#define INTERRUPT_ACK_GROUP1 0x1U
Acknowledge PIE Interrupt Group 1.
#define INTERRUPT_ACK_GROUP2 0x2U
Acknowledge PIE Interrupt Group 2.
#define INTERRUPT_ACK_GROUP3 0x4U
Acknowledge PIE Interrupt Group 3.
#define INTERRUPT_ACK_GROUP4 0x8U
Acknowledge PIE Interrupt Group 4.
#define INTERRUPT_ACK_GROUP5 0x10U
Acknowledge PIE Interrupt Group 5.
#define INTERRUPT_ACK_GROUP6 0x20U
Acknowledge PIE Interrupt Group 6.
#define INTERRUPT_ACK_GROUP7 0x40U
Acknowledge PIE Interrupt Group 7.
#define INTERRUPT_ACK_GROUP8 0x80U
Acknowledge PIE Interrupt Group 8.
#define INTERRUPT_ACK_GROUP9 0x100U
Acknowledge PIE Interrupt Group 9.
#define INTERRUPT_ACK_GROUP10 0x200U
Acknowledge PIE Interrupt Group 10.
#define INTERRUPT_ACK_GROUP11 0x400U
Acknowledge PIE Interrupt Group 11.
#define INTERRUPT_ACK_GROUP12 0x800U
Acknowledge PIE Interrupt Group 12.
Function Documentation
static void Interrupt_defaultHandler (void) static
References ESTOP0, HWREGH, PIE_O_CTRL, and PIECTRL_BASE.
Referenced by Interrupt_initVectorTable(), and Interrupt_unregister().
static void Interrupt_illegalOperationHandler (void) static
References ESTOP0.
Referenced by Interrupt_initVectorTable().
static void Interrupt_nmiHandler (void) static
References ESTOP0.
Referenced by Interrupt_initVectorTable().
static bool Interrupt_enableMaster (void) inline static
Allows the CPU to process interrupts.
This function clears the global interrupt mask bit (INTM) in the CPU, allowing the processor to respond to interrupts.
Returns
Returns true if interrupts were disabled when the function was called or false if they were initially enabled.
References __enable_interrupts().
Referenced by Interrupt_disable(), and Interrupt_enable().
static bool Interrupt_disableMaster (void) inline static
Stops the CPU from processing interrupts.
This function sets the global interrupt mask bit (INTM) in the CPU, preventing the processor from receiving maskable interrupts.
Returns
Returns true if interrupts were already disabled when the function was called or false if they were initially enabled.
References __disable_interrupts().
Referenced by Interrupt_disable(), Interrupt_enable(), and Interrupt_initModule().
static void Interrupt_register (uint32_t interruptNumber, void(*)(void) handler) inline static
Registers a function to be called when an interrupt occurs.
Parameters
interruptNumber specifies the interrupt in question.
handler is a pointer to the function to be called.
This function is used to specify the handler function to be called when the given interrupt is asserted to the processor. When the interrupt occurs, if it is enabled (via Interrupt_enable()), the handler function will be called in interrupt context. Since the handler function can preempt other code, care must be taken to protect memory or peripherals that are accessed by the handler and other non-handler code.
The available interruptNumber values are supplied in inc/hw_ints.h.
Note
This function assumes that the PIE has been enabled. See Interrupt_initModule().
Returns
None.
References EALLOW, EDIS, HWREG, and PIEVECTTABLE_BASE.
static void Interrupt_unregister (uint32_t interruptNumber) inline static
Unregisters the function to be called when an interrupt occurs.
Parameters
interruptNumber specifies the interrupt in question.
This function is used to indicate that a default handler Interrupt_defaultHandler() should be called when the given interrupt is asserted to the processor. Call Interrupt_disable() to disable the interrupt before calling this function.
The available interruptNumber values are supplied in inc/hw_ints.h.
See Also
Interrupt_register() for important information about registering interrupt handlers.
Returns
None.
References EALLOW, EDIS, HWREG, Interrupt_defaultHandler(), and PIEVECTTABLE_BASE.
static void Interrupt_enableInCPU (uint16_t cpuInterrupt) inline static
Enables CPU interrupt channels
Parameters
cpuInterrupt specifies the CPU interrupts to be enabled.
This function enables the specified interrupts in the CPU. The cpuInterrupt parameter is a logical OR of the values INTERRUPT_CPU_INTx where x is the interrupt number between 1 and 14, INTERRUPT_CPU_DLOGINT, and INTERRUPT_CPU_RTOSINT.
Note
Note that interrupts 1-12 correspond to the PIE groups with those same numbers.
Returns
None.
References IER.
static void Interrupt_disableInCPU (uint16_t cpuInterrupt) inline static
Disables CPU interrupt channels
Parameters
cpuInterrupt specifies the CPU interrupts to be disabled.
This function disables the specified interrupts in the CPU. The cpuInterrupt parameter is a logical OR of the values INTERRUPT_CPU_INTx where x is the interrupt number between 1 and 14, INTERRUPT_CPU_DLOGINT, and INTERRUPT_CPU_RTOSINT.
Note
Note that interrupts 1-12 correspond to the PIE groups with those same numbers.
Returns
None.
References IER.
static void Interrupt_clearACKGroup (uint16_t group) inline static
Acknowledges PIE Interrupt Group
Parameters
group specifies the interrupt group to be acknowledged.
The specified interrupt group is acknowledged and clears any interrupt flag within that respective group.
The group parameter must be a logical OR of the following: INTERRUPT_ACK_GROUP1, INTERRUPT_ACK_GROUP2, INTERRUPT_ACK_GROUP3 INTERRUPT_ACK_GROUP4, INTERRUPT_ACK_GROUP5, INTERRUPT_ACK_GROUP6 INTERRUPT_ACK_GROUP7, INTERRUPT_ACK_GROUP8, INTERRUPT_ACK_GROUP9 INTERRUPT_ACK_GROUP10, INTERRUPT_ACK_GROUP11, INTERRUPT_ACK_GROUP12.
Returns
None.
References HWREGH, PIE_O_ACK, and PIECTRL_BASE.
void Interrupt_initModule (void)
Initializes the PIE control registers by setting them to a known state.
This function initializes the PIE control registers. After globally disabling interrupts and enabling the PIE, it clears all of the PIE interrupt enable bits and interrupt flags.
Returns
None.
References HWREGH, IER, IFR, Interrupt_disableMaster(), PIE_CTRL_ENPIE, PIE_O_CTRL, PIE_O_IER1, PIE_O_IER10, PIE_O_IER11, PIE_O_IER12, PIE_O_IER2, PIE_O_IER3, PIE_O_IER4, PIE_O_IER5, PIE_O_IER6, PIE_O_IER7, PIE_O_IER8, PIE_O_IER9, PIE_O_IFR1, PIE_O_IFR10, PIE_O_IFR11, PIE_O_IFR12, PIE_O_IFR2, PIE_O_IFR3, PIE_O_IFR4, PIE_O_IFR5, PIE_O_IFR6, PIE_O_IFR7, PIE_O_IFR8, PIE_O_IFR9, and PIECTRL_BASE.
void Interrupt_initVectorTable (void)
Initializes the PIE vector table by setting all vectors to a default handler function.
Returns
None.
References EALLOW, EDIS, HWREG, INT_ILLEGAL, INT_NMI, Interrupt_defaultHandler(), Interrupt_illegalOperationHandler(), Interrupt_nmiHandler(), and PIEVECTTABLE_BASE.
void Interrupt_enable (uint32_t interruptNumber)
Enables an interrupt.
Parameters
interruptNumber specifies the interrupt to be enabled.
The specified interrupt is enabled in the interrupt controller. Other enables for the interrupt (such as at the peripheral level) are unaffected by this function.
The available interruptNumber values are supplied in inc/hw_ints.h.
Returns
None.
References HWREGH, IER, Interrupt_disableMaster(), Interrupt_enableMaster(), PIE_O_IER1, and PIECTRL_BASE.
void Interrupt_disable (uint32_t interruptNumber)
Disables an interrupt.
Parameters
interruptNumber specifies the interrupt to be disabled.
The specified interrupt is disabled in the interrupt controller. Other enables for the interrupt (such as at the peripheral level) are unaffected by this function.
The available interruptNumber values are supplied in inc/hw_ints.h.
Returns
None.
References HWREGH, IER, Interrupt_clearIFR(), Interrupt_disableMaster(), Interrupt_enableMaster(), NOP, PIE_O_ACK, PIE_O_IER1, and PIECTRL_BASE.
uint16_t __disable_interrupts (void)
Referenced by Interrupt_disableMaster(), and SysCtl_setClock().
uint16_t __enable_interrupts (void)
Referenced by Interrupt_enableMaster().
Copyright 2018, Texas Instruments Incorporated