Flash
Flash
Macros
#define FLASH_FAIL_0_CLR 0x1
Fail-0 clear.
#define FLASH_FAIL_1_CLR 0x2
Fail-1 clear.
#define FLASH_UNC_ERR_CLR 0x4
Uncorrectable error Clear.
#define FLASH_NO_ERROR 0x0
No error.
#define FLASH_SINGLE_ERROR 0x1
Single bit error.
#define FLASH_UNC_ERROR 0x2
Uncorrectable error.
#define FLASH_DELAY_CONFIG __asm(" RPT #7 || NOP")
#define PUMP_KEY 0x5A5A0000UL
Pump semaphore key.
Enumerations
enum Flash_BankNumber { FLASH_BANK = 0x0 }
Values that can be passed to Flash_setBankPowerMode() as the bank parameter.
enum Flash_PumpOwnership {
FLASH_CPU1_WRAPPER = 0x2,
FLASH_CPU2_WRAPPER = 0x1
}
enum Flash_BankPowerMode {
FLASH_BANK_PWR_SLEEP = 0x0,
FLASH_BANK_PWR_STANDBY = 0x1,
FLASH_BANK_PWR_ACTIVE = 0x3
}
enum Flash_PumpPowerMode {
FLASH_PUMP_PWR_SLEEP = 0x0,
FLASH_PUMP_PWR_ACTIVE = 0x1
}
enum Flash_ErrorStatus {
FLASH_NO_ERR = 0x0,
FLASH_FAIL_0 = 0x1,
FLASH_FAIL_1 = 0x2,
FLASH_UNC_ERR = 0x4
}
enum Flash_ErrorType {
FLASH_DATA_ERR = 0x0,
FLASH_ECC_ERR = 0x1
}
enum Flash_SingleBitErrorIndicator {
FLASH_DATA_BITS = 0x0,
FLASH_CHECK_BITS = 0x1
}
Values that can be returned from Flash_getECCTestSingleBitErrorType().
Functions
static void Flash_setWaitstates (uint32_t ctrlBase, uint16_t waitstates)
static void Flash_setBankPowerMode (uint32_t ctrlBase, Flash_BankNumber bank, Flash_BankPowerMode powerMode)
static void Flash_setPumpPowerMode (uint32_t ctrlBase, Flash_PumpPowerMode powerMode)
static void Flash_enablePrefetch (uint32_t ctrlBase)
static void Flash_disablePrefetch (uint32_t ctrlBase)
static void Flash_enableCache (uint32_t ctrlBase)
static void Flash_disableCache (uint32_t ctrlBase)
static void Flash_enableECC (uint32_t eccBase)
static void Flash_disableECC (uint32_t eccBase)
static void Flash_setBankPowerUpDelay (uint32_t ctrlBase, uint16_t delay)
static void Flash_setPumpWakeupTime (uint32_t ctrlBase, uint16_t sysclkCycles)
static bool Flash_isBankReady (uint32_t ctrlBase, Flash_BankNumber bank)
static bool Flash_isPumpReady (uint32_t ctrlBase)
static uint32_t Flash_getSingleBitErrorAddressLow (uint32_t eccBase)
static uint32_t Flash_getSingleBitErrorAddressHigh (uint32_t eccBase)
static uint32_t Flash_getUncorrectableErrorAddressLow (uint32_t eccBase)
static uint32_t Flash_getUncorrectableErrorAddressHigh (uint32_t eccBase)
static Flash_ErrorStatus Flash_getLowErrorStatus (uint32_t eccBase)
static Flash_ErrorStatus Flash_getHighErrorStatus (uint32_t eccBase)
static uint32_t Flash_getLowErrorPosition (uint32_t eccBase)
static uint32_t Flash_getHighErrorPosition (uint32_t eccBase)
static Flash_ErrorType Flash_getLowErrorType (uint32_t eccBase)
static Flash_ErrorType Flash_getHighErrorType (uint32_t eccBase)
static void Flash_clearLowErrorStatus (uint32_t eccBase, uint16_t errorStatus)
static void Flash_clearHighErrorStatus (uint32_t eccBase, uint16_t errorStatus)
static uint32_t Flash_getErrorCount (uint32_t eccBase)
static void Flash_setErrorThreshold (uint32_t eccBase, uint16_t threshold)
static uint32_t Flash_getInterruptFlag (uint32_t eccBase)
static void Flash_clearSingleErrorInterruptFlag (uint32_t eccBase)
static void Flash_clearUncorrectableInterruptFlag (uint32_t eccBase)
static void Flash_setDataLowECCTest (uint32_t eccBase, uint32_t data)
static void Flash_setDataHighECCTest (uint32_t eccBase, uint32_t data)
static void Flash_setECCTestAddress (uint32_t eccBase, uint32_t address)
static void Flash_setECCTestECCBits (uint32_t eccBase, uint16_t ecc)
static void Flash_enableECCTestMode (uint32_t eccBase)
static void Flash_disableECCTestMode (uint32_t eccBase)
static void Flash_selectLowECCBlock (uint32_t eccBase)
static void Flash_selectHighECCBlock (uint32_t eccBase)
static void Flash_performECCCalculation (uint32_t eccBase)
static uint32_t Flash_getTestDataOutHigh (uint32_t eccBase)
static uint32_t Flash_getTestDataOutLow (uint32_t eccBase)
static uint32_t Flash_getECCTestStatus (uint32_t eccBase)
static uint32_t Flash_getECCTestErrorPosition (uint32_t eccBase)
static
Flash_SingleBitErrorIndicator Flash_getECCTestSingleBitErrorType (uint32_t eccBase)
static void Flash_claimPumpSemaphore (uint32_t pumpSemBase, Flash_PumpOwnership wrapper)
static void Flash_releasePumpSemaphore (uint32_t pumpSemBase)
void Flash_initModule (uint32_t ctrlBase, uint32_t eccBase, uint16_t waitstates)
void Flash_powerDown (uint32_t ctrlBase)
Detailed Description
Macro Definition Documentation
#define FLASH_FAIL_0_CLR 0x1
Fail-0 clear.
#define FLASH_FAIL_1_CLR 0x2
Fail-1 clear.
#define FLASH_UNC_ERR_CLR 0x4
Uncorrectable error Clear.
#define FLASH_NO_ERROR 0x0
No error.
#define FLASH_SINGLE_ERROR 0x1
Single bit error.
#define FLASH_UNC_ERROR 0x2
Uncorrectable error.
#define FLASH_DELAY_CONFIG __asm(" RPT #7 || NOP")
Referenced by Flash_initModule().
#define PUMP_KEY 0x5A5A0000UL
Pump semaphore key.
Referenced by Flash_claimPumpSemaphore(), and Flash_releasePumpSemaphore().
Enumeration Type Documentation
enum Flash_BankNumber
Values that can be passed to Flash_setBankPowerMode() as the bank parameter.
Enumerator
FLASH_BANK
Bank.
enum Flash_PumpOwnership
Values that can be passed to Flash_claimPumpSemaphore() in order to claim the pump semaphore.
Enumerator
FLASH_CPU1_WRAPPER
CPU1 Wrapper.
FLASH_CPU2_WRAPPER
CPU2 Wrapper.
enum Flash_BankPowerMode
Values that can be passed to Flash_setBankPowerMode() as the powerMode parameter.
Enumerator
FLASH_BANK_PWR_SLEEP
Sleep fallback mode.
FLASH_BANK_PWR_STANDBY
Standby fallback mode.
FLASH_BANK_PWR_ACTIVE
Active fallback mode.
enum Flash_PumpPowerMode
Values that can be passed to Flash_setPumpPowerMode() as the powerMode parameter.
Enumerator
FLASH_PUMP_PWR_SLEEP
Sleep fallback mode.
FLASH_PUMP_PWR_ACTIVE
Active fallback mode.
enum Flash_ErrorStatus
Type that correspond to values returned from Flash_getLowErrorStatus() and Flash_getHighErrorStatus() determining the error status code.
Enumerator
FLASH_NO_ERR
No error.
FLASH_FAIL_0
Fail on 0.
FLASH_FAIL_1
Fail on 1.
FLASH_UNC_ERR
Uncorrectable error.
enum Flash_ErrorType
Values that can be returned from Flash_getLowErrorType() and Flash_getHighErrorType() determining the error type.
Enumerator
FLASH_DATA_ERR
Data error.
FLASH_ECC_ERR
ECC error.
enum Flash_SingleBitErrorIndicator
Values that can be returned from Flash_getECCTestSingleBitErrorType().
Enumerator
FLASH_DATA_BITS
Data bits.
FLASH_CHECK_BITS
ECC bits.
Function Documentation
static void Flash_setWaitstates (uint32_t ctrlBase, uint16_t waitstates) inline static
Sets the random read wait state amount.
Parameters
ctrlBase is the base address of the flash wrapper control registers.
waitstates is the wait-state value.
This function sets the number of wait states for a flash read access. The waitstates parameter is a number between 0 and 15. It is important to look at your device's datasheet for information about what the required minimum flash wait-state is for your selected SYSCLK frequency.
By default the wait state amount is configured to the maximum 15.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FRDCNTL_RWAIT_M, FLASH_FRDCNTL_RWAIT_S, FLASH_O_FRDCNTL, and HWREG.
Referenced by Flash_initModule().
static void Flash_setBankPowerMode (uint32_t ctrlBase, Flash_BankNumber bank, Flash_BankPowerMode powerMode) inline static
Sets the fallback power mode of a flash bank.
Parameters
ctrlBase is the base address of the flash wrapper registers.
bank is the flash bank that is being configured.
powerMode is the power mode to be entered.
This function sets the fallback power mode of the flash bank specified by them bank parameter. The power mode is specified by the powerMode parameter with one of the following values:
FLASH_BANK_PWR_SLEEP - Sense amplifiers and sense reference disabled.
FLASH_BANK_PWR_STANDBY - Sense amplifiers disabled but sense reference enabled.
FLASH_BANK_PWR_ACTIVE - Sense amplifiers and sense reference enabled.
Note: There is only one Flash_BankNumber value on this device (FLASH_BANK).
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FBFALLBACK_BNKPWR0_M, FLASH_O_FBFALLBACK, and HWREG.
Referenced by Flash_initModule(), and Flash_powerDown().
static void Flash_setPumpPowerMode (uint32_t ctrlBase, Flash_PumpPowerMode powerMode) inline static
Sets the fallback power mode of the charge pump.
Parameters
ctrlBase is the base address of the flash wrapper control registers.
powerMode is the power mode to be entered.
This function sets the fallback power mode flash charge pump.
FLASH_PUMP_PWR_SLEEP - All circuits disabled.
FLASH_PUMP_PWR_ACTIVE - All pump circuits active.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FPAC1_PMPPWR, FLASH_O_FPAC1, and HWREG.
Referenced by Flash_initModule(), and Flash_powerDown().
static void Flash_enablePrefetch (uint32_t ctrlBase) inline static
Enables prefetch mechanism.
Parameters
ctrlBase is the base address of the flash wrapper control registers.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FRD_INTF_CTRL_PREFETCH_EN, FLASH_O_FRD_INTF_CTRL, and HWREG.
Referenced by Flash_initModule().
static void Flash_disablePrefetch (uint32_t ctrlBase) inline static
Disables prefetch mechanism.
Parameters
ctrlBase is the base address of the flash wrapper control registers.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FRD_INTF_CTRL_PREFETCH_EN, FLASH_O_FRD_INTF_CTRL, and HWREG.
Referenced by Flash_initModule().
static void Flash_enableCache (uint32_t ctrlBase) inline static
Enables data cache.
Parameters
ctrlBase is the base address of the flash wrapper control registers.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FRD_INTF_CTRL_DATA_CACHE_EN, FLASH_O_FRD_INTF_CTRL, and HWREG.
Referenced by Flash_initModule().
static void Flash_disableCache (uint32_t ctrlBase) inline static
Disables data cache.
Parameters
ctrlBase is the base address of the flash wrapper control registers.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FRD_INTF_CTRL_DATA_CACHE_EN, FLASH_O_FRD_INTF_CTRL, and HWREG.
Referenced by Flash_initModule().
static void Flash_enableECC (uint32_t eccBase) inline static
Enables flash error correction code (ECC) protection.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_ECC_ENABLE_ENABLE_M, FLASH_O_ECC_ENABLE, and HWREG.
Referenced by Flash_initModule().
static void Flash_disableECC (uint32_t eccBase) inline static
Disables flash error correction code (ECC) protection.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_ECC_ENABLE_ENABLE_M, FLASH_O_ECC_ENABLE, and HWREG.
static void Flash_setBankPowerUpDelay (uint32_t ctrlBase, uint16_t delay) inline static
Sets the bank power up delay.
Parameters
ctrlBase is the base address of the flash wrapper control registers.
delay is the number of HCLK cycles.
This function sets the VREADST delay to ensure that the requisite delay is introduced for the flash pump/bank to come out of low-power mode, so that the flash/OTP is ready for CPU access.
Note: Refer to TRM before configuring VREADST.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FBAC_VREADST_M, FLASH_O_FBAC, and HWREG.
Referenced by Flash_initModule(), and Flash_powerDown().
static void Flash_setPumpWakeupTime (uint32_t ctrlBase, uint16_t sysclkCycles) inline static
Sets the pump wake up time.
Parameters
ctrlBase is the base address of the flash wrapper control registers.
sysclkCycles is the number of SYSCLK cycles it takes for the pump to wakeup.
This function sets the wakeup time with sysclkCycles parameter. The sysclkCycles is a value between 0 and 8190. When the charge pump exits sleep power mode, it will take sysclkCycles to wakeup.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FPAC1_PSLEEP_M, FLASH_FPAC1_PSLEEP_S, FLASH_O_FPAC1, and HWREG.
static bool Flash_isBankReady (uint32_t ctrlBase, Flash_BankNumber bank) inline static
Reads the bank active power state.
Parameters
ctrlBase is the base address of the flash wrapper control registers.
bank is the flash bank that is being used.
Returns
Returns true if the Bank is in Active power state and false otherwise.
References ASSERT, FLASH_FBPRDY_BANKRDY, FLASH_O_FBPRDY, and HWREG.
static bool Flash_isPumpReady (uint32_t ctrlBase) inline static
Reads the pump active power state.
Parameters
ctrlBase is the base address of the flash wrapper control registers.
Returns
Returns true if the Pump is in Active power state and false otherwise.
References ASSERT, FLASH_FBPRDY_PUMPRDY, FLASH_O_FBPRDY, and HWREG.
static uint32_t Flash_getSingleBitErrorAddressLow (uint32_t eccBase) inline static
Gets the single error address low.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
This function returns the 32-bit address of the single bit error that occurred in the lower 64-bits of a 128-bit memory-aligned data. The returned address is to that 64-bit aligned data.
Returns
Returns the 32 bits of a 64-bit aligned address where a single bit error occurred.
References ASSERT, FLASH_O_SINGLE_ERR_ADDR_LOW, and HWREG.
static uint32_t Flash_getSingleBitErrorAddressHigh (uint32_t eccBase) inline static
Gets the single error address high.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
This function returns the 32-bit address of the single bit error that occurred in the upper 64-bits of a 128-bit memory-aligned data. The returned address is to that 64-bit aligned data.
Returns
Returns the 32 bits of a 64-bit aligned address where a single bit error occurred.
References ASSERT, FLASH_O_SINGLE_ERR_ADDR_HIGH, and HWREG.
static uint32_t Flash_getUncorrectableErrorAddressLow (uint32_t eccBase) inline static
Gets the uncorrectable error address low.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
This function returns the 32-bit address of the uncorrectable error that occurred in the lower 64-bits of a 128-bit memory-aligned data. The returned address is to that 64-bit aligned data.
Returns
Returns the 32 bits of a 64-bit aligned address where an uncorrectable error occurred.
References ASSERT, FLASH_O_UNC_ERR_ADDR_LOW, and HWREG.
static uint32_t Flash_getUncorrectableErrorAddressHigh (uint32_t eccBase) inline static
Gets the uncorrectable error address high.
Parameters
eccBase is the base address of the flash wrapper ECC base.
This function returns the 32-bit address of the uncorrectable error that occurred in the upper 64-bits of a 128-bit memory-aligned data. The returned address is to that 64-bit aligned data.
Returns
Returns the 32 bits of a 64-bit aligned address where an uncorrectable error occurred.
References ASSERT, FLASH_O_UNC_ERR_ADDR_HIGH, and HWREG.
static Flash_ErrorStatus Flash_getLowErrorStatus (uint32_t eccBase) inline static
Gets the error status of the Lower 64-bits.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
This function returns the error status of the lower 64-bits of a 128-bit aligned address.
Returns
Returns value of the low error status bits which can be used with Flash_ErrorStatus type.
References ASSERT, FLASH_O_ERR_STATUS, and HWREG.
static Flash_ErrorStatus Flash_getHighErrorStatus (uint32_t eccBase) inline static
Gets the error status of the Upper 64-bits.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
This function returns the error status of the upper 64-bits of a 128-bit aligned address.
Returns
Returns value of the high error status bits which can be used with Flash_ErrorStatus type.
References ASSERT, FLASH_O_ERR_STATUS, and HWREG.
static uint32_t Flash_getLowErrorPosition (uint32_t eccBase) inline static
Gets the error position of the lower 64-bits for a single bit error.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
This function returns the error position of the lower 64-bits. If the error type is FLASH_ECC_ERR, the position ranges from 0-7 else it ranges from 0-63 for FLASH_DATA_ERR.
Returns
Returns the position of the lower error bit.
References ASSERT, FLASH_ERR_POS_ERR_POS_L_M, FLASH_ERR_POS_ERR_POS_L_S, FLASH_O_ERR_POS, and HWREG.
static uint32_t Flash_getHighErrorPosition (uint32_t eccBase) inline static
Gets the error position of the upper 64-bits for a single bit error.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
This function returns the error position of the upper 64-bits. If the error type is FLASH_ECC_ERR, the position ranges from 0-7 else it ranges from 0-63 for FLASH_DATA_ERR.
Returns
Returns the position of the upper error bit.
References ASSERT, FLASH_ERR_POS_ERR_POS_H_M, FLASH_ERR_POS_ERR_POS_H_S, FLASH_O_ERR_POS, and HWREG.
static Flash_ErrorType Flash_getLowErrorType (uint32_t eccBase) inline static
Gets the error type of the lower 64-bits.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
This function returns the error type of the lower 64-bits. The error type can be FLASH_ECC_ERR or FLASH_DATA_ERR.
Returns
Returns the type of the lower 64-bit error.
References ASSERT, FLASH_ERR_POS_ERR_TYPE_L, FLASH_O_ERR_POS, and HWREG.
static Flash_ErrorType Flash_getHighErrorType (uint32_t eccBase) inline static
Gets the error type of the upper 64-bits.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
This function returns the error type of the upper 64-bits. The error type can be FLASH_ECC_ERR or FLASH_DATA_ERR.
Returns
Returns the type of the upper 64-bit error.
References ASSERT, FLASH_ERR_POS_ERR_TYPE_H, FLASH_O_ERR_POS, and HWREG.
static void Flash_clearLowErrorStatus (uint32_t eccBase, uint16_t errorStatus) inline static
Clears the errors status of the lower 64-bits.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
errorStatus is the error status to clear. errorStatus is a uint16_t. errorStatus is a bitwise OR of the following value:
FLASH_FAIL_0_CLR
FLASH_FAIL_1_CLR
FLASH_UNC_ERR_CLR
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_O_ERR_STATUS_CLR, and HWREG.
static void Flash_clearHighErrorStatus (uint32_t eccBase, uint16_t errorStatus) inline static
Clears the errors status of the upper 64-bits.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
errorStatus is the error status to clear. errorStatus is a uint16_t. errorStatus is a bitwise OR of the following value:
FLASH_FAIL_0_CLR
FLASH_FAIL_1_CLR
FLASH_UNC_ERR_CLR
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_O_ERR_STATUS_CLR, and HWREG.
static uint32_t Flash_getErrorCount (uint32_t eccBase) inline static
Gets the single bit error count.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
Returns
Returns the single bit error count.
References ASSERT, FLASH_ERR_CNT_ERR_CNT_M, FLASH_O_ERR_CNT, and HWREG.
static void Flash_setErrorThreshold (uint32_t eccBase, uint16_t threshold) inline static
Sets the single bit error threshold.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
threshold is the single bit error threshold. Valid ranges are from 0-65535.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_ERR_THRESHOLD_ERR_THRESHOLD_M, FLASH_O_ERR_THRESHOLD, and HWREG.
static uint32_t Flash_getInterruptFlag (uint32_t eccBase) inline static
Gets the error interrupt.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
This function returns the type of error interrupt that occurred. The values can be used with
FLASH_NO_ERROR
FLASH_SINGLE_ERROR
FLASH_UNC_ERROR
Returns
Returns the interrupt flag.
References ASSERT, FLASH_O_ERR_INTFLG, and HWREG.
static void Flash_clearSingleErrorInterruptFlag (uint32_t eccBase) inline static
Clears the single error interrupt flag.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_ERR_INTCLR_SINGLE_ERR_INTCLR, FLASH_O_ERR_INTCLR, and HWREG.
static void Flash_clearUncorrectableInterruptFlag (uint32_t eccBase) inline static
Clears the uncorrectable error interrupt flag.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_ERR_INTCLR_UNC_ERR_INTCLR, FLASH_O_ERR_INTCLR, and HWREG.
static void Flash_setDataLowECCTest (uint32_t eccBase, uint32_t data) inline static
Sets the Data Low Test register for ECC testing.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
data is a 32-bit value that is the low double word of selected 64-bit data
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_O_FDATAL_TEST, and HWREG.
static void Flash_setDataHighECCTest (uint32_t eccBase, uint32_t data) inline static
Sets the Data High Test register for ECC testing.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
data is a 32-bit value that is the high double word of selected 64-bit data
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_O_FDATAH_TEST, and HWREG.
static void Flash_setECCTestAddress (uint32_t eccBase, uint32_t address) inline static
Sets the test address register for ECC testing.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
address is a 32-bit value containing an address. Bits 21-3 will be used as the flash word (128-bit) address.
This function left shifts the address 1 bit to convert it to a byte address.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_O_FADDR_TEST, and HWREG.
static void Flash_setECCTestECCBits (uint32_t eccBase, uint16_t ecc) inline static
Sets the ECC test bits for ECC testing.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
ecc is a 32-bit value. The least significant 8 bits are used as the ECC Control Bits in the ECC Test.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FECC_TEST_ECC_M, FLASH_O_FECC_TEST, and HWREG.
static void Flash_enableECCTestMode (uint32_t eccBase) inline static
Enables ECC Test mode.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FECC_CTRL_ECC_TEST_EN, FLASH_O_FECC_CTRL, and HWREG.
static void Flash_disableECCTestMode (uint32_t eccBase) inline static
Disables ECC Test mode.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FECC_CTRL_ECC_TEST_EN, FLASH_O_FECC_CTRL, and HWREG.
static void Flash_selectLowECCBlock (uint32_t eccBase) inline static
Selects the ECC block on bits [63:0] of bank data.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FECC_CTRL_ECC_SELECT, FLASH_O_FECC_CTRL, and HWREG.
static void Flash_selectHighECCBlock (uint32_t eccBase) inline static
Selects the ECC block on bits [127:64] of bank data.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FECC_CTRL_ECC_SELECT, FLASH_O_FECC_CTRL, and HWREG.
static void Flash_performECCCalculation (uint32_t eccBase) inline static
Performs the ECC calculation on the test block.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_FECC_CTRL_DO_ECC_CALC, FLASH_O_FECC_CTRL, and HWREG.
static uint32_t Flash_getTestDataOutHigh (uint32_t eccBase) inline static
Gets the ECC Test data out high 63:32 bits.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
Returns
Returns the ECC TEst data out High.
References ASSERT, FLASH_O_FOUTH_TEST, and HWREG.
static uint32_t Flash_getTestDataOutLow (uint32_t eccBase) inline static
Gets the ECC Test data out low 31:0 bits.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
Returns
Returns the ECC Test data out Low.
References ASSERT, FLASH_O_FOUTL_TEST, and HWREG.
static uint32_t Flash_getECCTestStatus (uint32_t eccBase) inline static
Gets the ECC Test status.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
This function returns the ECC test status. The values can be used with
FLASH_NO_ERROR
FLASH_SINGLE_ERROR
FLASH_UNC_ERROR
Returns
Returns the ECC test status.
References ASSERT, FLASH_O_FECC_STATUS, and HWREG.
static uint32_t Flash_getECCTestErrorPosition (uint32_t eccBase) inline static
Gets the ECC Test single bit error position.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
Returns
Returns the ECC Test single bit error position. If the error type is check bits than the position can range from 0 to 7. If the error type is data bits than the position can range from 0 to 63.
References ASSERT, FLASH_FECC_STATUS_DATA_ERR_POS_M, FLASH_FECC_STATUS_DATA_ERR_POS_S, FLASH_O_FECC_STATUS, and HWREG.
static Flash_SingleBitErrorIndicator Flash_getECCTestSingleBitErrorType (uint32_t eccBase) inline static
Gets the single bit error type.
Parameters
eccBase is the base address of the flash wrapper ECC registers.
Returns
Returns the single bit error type as a Flash_SingleBitErrorIndicator. FLASH_DATA_BITS and FLASH_CHECK_BITS indicate where the single bit error occurred.
References ASSERT, FLASH_FECC_STATUS_ERR_TYPE, FLASH_O_FECC_STATUS, and HWREG.
static void Flash_claimPumpSemaphore (uint32_t pumpSemBase, Flash_PumpOwnership wrapper) inline static
Claim the flash pump semaphore.
Parameters
pumpSemBase is the base address of the flash pump semaphore.
wrapper is the Flash_PumpOwnership wrapper claiming the pump semaphore.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_O_PUMPREQUEST, FLASH_PUMPREQUEST_PUMP_OWNERSHIP_M, HWREG, and PUMP_KEY.
static void Flash_releasePumpSemaphore (uint32_t pumpSemBase) inline static
Release the flash pump semaphore.
Parameters
pumpSemBase is the base address of the flash pump semaphore.
Returns
None.
References ASSERT, EALLOW, EDIS, FLASH_O_PUMPREQUEST, HWREG, and PUMP_KEY.
void Flash_initModule (uint32_t ctrlBase, uint32_t eccBase, uint16_t waitstates)
Initializes the flash control registers.
Parameters
ctrlBase is the base address of the flash wrapper control registers.
eccBase is the base address of the flash wrapper ECC registers.
waitstates is the wait-state value.
This function initializes the flash control registers. At reset bank and pump are in sleep. A flash access will power up the bank and pump automatically. After a flash access, bank and pump go to low power mode (configurable in FBFALLBACK/FPAC1 registers) if there is no further access to flash. This function will power up Flash bank and pump and set the fallback mode of flash and pump as active.
This function also sets the number of wait-states for a flash access (see Flash_setWaitstates() for more details), and enables cache, the prefetch mechanism, and ECC.
Returns
None.
References ASSERT, FLASH_BANK, FLASH_BANK_PWR_ACTIVE, FLASH_DELAY_CONFIG, Flash_disableCache(), Flash_disablePrefetch(), Flash_enableCache(), Flash_enableECC(), Flash_enablePrefetch(), FLASH_PUMP_PWR_ACTIVE, Flash_setBankPowerMode(), Flash_setBankPowerUpDelay(), Flash_setPumpPowerMode(), and Flash_setWaitstates().
void Flash_powerDown (uint32_t ctrlBase)
Powers down the flash.
Parameters
ctrlBase is the base address of the flash wrapper control registers.
This function powers down the flash bank(s) and the flash pump.
Note: For this device, you must claim the flash pump semaphore before calling this function and powering down the pump. Afterwards, you may want to relinquish the flash pump.
Returns
None.
References ASSERT, FLASH_BANK, FLASH_BANK_PWR_SLEEP, FLASH_PUMP_PWR_SLEEP, Flash_setBankPowerMode(), Flash_setBankPowerUpDelay(), and Flash_setPumpPowerMode().
Copyright 2018, Texas Instruments Incorporated