SCI
SCI
Macros
#define SCI_INT_RXERR 0x01U
RXERR interrupt.
#define SCI_INT_RXRDY_BRKDT 0x02U
RXRDY interrupt.
#define SCI_INT_TXRDY 0x04U
TXRDY interrupt.
#define SCI_INT_TXFF 0x08U
TX FIFO level interrupt.
#define SCI_INT_RXFF 0x10U
RX FIFO level interrupt.
#define SCI_INT_FE 0x20U
Frame Error.
#define SCI_INT_OE 0x40U
Overrun Error.
#define SCI_INT_PE 0x80U
Parity Error.
#define SCI_CONFIG_WLEN_MASK 0x0007U
Mask for extracting word length.
#define SCI_CONFIG_WLEN_8 0x0007U
8 bit data
#define SCI_CONFIG_WLEN_7 0x0006U
7 bit data
#define SCI_CONFIG_WLEN_6 0x0005U
6 bit data
#define SCI_CONFIG_WLEN_5 0x0004U
5 bit data
#define SCI_CONFIG_WLEN_4 0x0003U
4 bit data
#define SCI_CONFIG_WLEN_3 0x0002U
3 bit data
#define SCI_CONFIG_WLEN_2 0x0001U
2 bit data
#define SCI_CONFIG_WLEN_1 0x0000U
1 bit data
#define SCI_CONFIG_STOP_MASK 0x0080U
Mask for extracting stop bits.
#define SCI_CONFIG_STOP_ONE 0x0000U
One stop bit.
#define SCI_CONFIG_STOP_TWO 0x0080U
Two stop bits.
#define SCI_CONFIG_PAR_MASK 0x0060U
Parity Mask.
#define SCI_RXSTATUS_WAKE 0x0002U
Receiver wake up detect.
#define SCI_RXSTATUS_PARITY 0x0004U
Parity error.
#define SCI_RXSTATUS_OVERRUN 0x0008U
Overrun error.
#define SCI_RXSTATUS_FRAMING 0x0010U
Framing error.
#define SCI_RXSTATUS_BREAK 0x0020U
Break detect.
#define SCI_RXSTATUS_READY 0x0040U
Receiver ready.
#define SCI_RXSTATUS_ERROR 0x0080U
Receiver error.
Enumerations
enum SCI_ParityType {
SCI_CONFIG_PAR_NONE = 0x0000U,
SCI_CONFIG_PAR_EVEN = 0x0060U,
SCI_CONFIG_PAR_ODD = 0x0020U
}
enum SCI_TxFIFOLevel {
SCI_FIFO_TX0 = 0x0000U,
SCI_FIFO_TX1 = 0x0001U,
SCI_FIFO_TX2 = 0x0002U,
SCI_FIFO_TX3 = 0x0003U,
SCI_FIFO_TX4 = 0x0004U,
SCI_FIFO_TX5 = 0x0005U,
SCI_FIFO_TX6 = 0x0006U,
SCI_FIFO_TX7 = 0x0007U,
SCI_FIFO_TX8 = 0x0008U,
SCI_FIFO_TX9 = 0x0009U,
SCI_FIFO_TX10 = 0x000AU,
SCI_FIFO_TX11 = 0x000BU,
SCI_FIFO_TX12 = 0x000CU,
SCI_FIFO_TX13 = 0x000DU,
SCI_FIFO_TX14 = 0x000EU,
SCI_FIFO_TX15 = 0x000FU,
SCI_FIFO_TX16 = 0x0010U
}
enum SCI_RxFIFOLevel {
SCI_FIFO_RX0 = 0x0000U,
SCI_FIFO_RX1 = 0x0001U,
SCI_FIFO_RX2 = 0x0002U,
SCI_FIFO_RX3 = 0x0003U,
SCI_FIFO_RX4 = 0x0004U,
SCI_FIFO_RX5 = 0x0005U,
SCI_FIFO_RX6 = 0x0006U,
SCI_FIFO_RX7 = 0x0007U,
SCI_FIFO_RX8 = 0x0008U,
SCI_FIFO_RX9 = 0x0009U,
SCI_FIFO_RX10 = 0x000AU,
SCI_FIFO_RX11 = 0x000BU,
SCI_FIFO_RX12 = 0x000CU,
SCI_FIFO_RX13 = 0x000DU,
SCI_FIFO_RX14 = 0x000EU,
SCI_FIFO_RX15 = 0x000FU,
SCI_FIFO_RX16 = 0x0010U
}
Functions
static void SCI_setParityMode (uint32_t base, SCI_ParityType parity)
static SCI_ParityType SCI_getParityMode (uint32_t base)
static void SCI_lockAutobaud (uint32_t base)
static void SCI_setFIFOInterruptLevel (uint32_t base, SCI_TxFIFOLevel txLevel, SCI_RxFIFOLevel rxLevel)
static void SCI_getFIFOInterruptLevel (uint32_t base, SCI_TxFIFOLevel *txLevel, SCI_RxFIFOLevel *rxLevel)
static void SCI_getConfig (uint32_t base, uint32_t lspclkHz, uint32_t *baud, uint32_t *config)
static void SCI_enableModule (uint32_t base)
static void SCI_disableModule (uint32_t base)
static void SCI_enableFIFO (uint32_t base)
static void SCI_disableFIFO (uint32_t base)
static bool SCI_isFIFOEnabled (uint32_t base)
static void SCI_resetRxFIFO (uint32_t base)
static void SCI_resetTxFIFO (uint32_t base)
static void SCI_resetChannels (uint32_t base)
static bool SCI_isDataAvailableNonFIFO (uint32_t base)
static bool SCI_isSpaceAvailableNonFIFO (uint32_t base)
static SCI_TxFIFOLevel SCI_getTxFIFOStatus (uint32_t base)
static SCI_RxFIFOLevel SCI_getRxFIFOStatus (uint32_t base)
static bool SCI_isTransmitterBusy (uint32_t base)
static void SCI_writeCharBlockingFIFO (uint32_t base, uint16_t data)
static void SCI_writeCharBlockingNonFIFO (uint32_t base, uint16_t data)
static void SCI_writeCharNonBlocking (uint32_t base, uint16_t data)
static uint16_t SCI_readCharBlockingFIFO (uint32_t base)
static uint16_t SCI_readCharBlockingNonFIFO (uint32_t base)
static uint16_t SCI_readCharNonBlocking (uint32_t base)
static uint16_t SCI_getRxStatus (uint32_t base)
static void SCI_performSoftwareReset (uint32_t base)
static void SCI_enableLoopback (uint32_t base)
static void SCI_disableLoopback (uint32_t base)
static bool SCI_getOverflowStatus (uint32_t base)
static void SCI_clearOverflowStatus (uint32_t base)
void SCI_setConfig (uint32_t base, uint32_t lspclkHz, uint32_t baud, uint32_t config)
void SCI_writeCharArray (uint32_t base, const uint16_t *const array, uint16_t length)
void SCI_readCharArray (uint32_t base, uint16_t *const array, uint16_t length)
void SCI_enableInterrupt (uint32_t base, uint32_t intFlags)
void SCI_disableInterrupt (uint32_t base, uint32_t intFlags)
uint32_t SCI_getInterruptStatus (uint32_t base)
void SCI_clearInterruptStatus (uint32_t base, uint32_t intFlags)
Detailed Description
Macro Definition Documentation
#define SCI_INT_RXERR 0x01U
RXERR interrupt.
Referenced by SCI_clearInterruptStatus(), SCI_disableInterrupt(), SCI_enableInterrupt(), and SCI_getInterruptStatus().
#define SCI_INT_RXRDY_BRKDT 0x02U
RXRDY interrupt.
Referenced by SCI_clearInterruptStatus(), SCI_disableInterrupt(), SCI_enableInterrupt(), and SCI_getInterruptStatus().
#define SCI_INT_TXRDY 0x04U
TXRDY interrupt.
Referenced by SCI_disableInterrupt(), SCI_enableInterrupt(), and SCI_getInterruptStatus().
#define SCI_INT_TXFF 0x08U
TX FIFO level interrupt.
Referenced by SCI_clearInterruptStatus(), SCI_disableInterrupt(), SCI_enableInterrupt(), and SCI_getInterruptStatus().
#define SCI_INT_RXFF 0x10U
RX FIFO level interrupt.
Referenced by SCI_clearInterruptStatus(), SCI_disableInterrupt(), SCI_enableInterrupt(), and SCI_getInterruptStatus().
#define SCI_INT_FE 0x20U
Frame Error.
Referenced by SCI_clearInterruptStatus(), and SCI_getInterruptStatus().
#define SCI_INT_OE 0x40U
Overrun Error.
Referenced by SCI_clearInterruptStatus(), and SCI_getInterruptStatus().
#define SCI_INT_PE 0x80U
Parity Error.
Referenced by SCI_clearInterruptStatus(), and SCI_getInterruptStatus().
#define SCI_CONFIG_WLEN_MASK 0x0007U
Mask for extracting word length.
Referenced by SCI_getConfig(), and SCI_setConfig().
#define SCI_CONFIG_WLEN_8 0x0007U
8 bit data
#define SCI_CONFIG_WLEN_7 0x0006U
7 bit data
#define SCI_CONFIG_WLEN_6 0x0005U
6 bit data
#define SCI_CONFIG_WLEN_5 0x0004U
5 bit data
#define SCI_CONFIG_WLEN_4 0x0003U
4 bit data
#define SCI_CONFIG_WLEN_3 0x0002U
3 bit data
#define SCI_CONFIG_WLEN_2 0x0001U
2 bit data
#define SCI_CONFIG_WLEN_1 0x0000U
1 bit data
#define SCI_CONFIG_STOP_MASK 0x0080U
Mask for extracting stop bits.
Referenced by SCI_getConfig(), and SCI_setConfig().
#define SCI_CONFIG_STOP_ONE 0x0000U
One stop bit.
#define SCI_CONFIG_STOP_TWO 0x0080U
Two stop bits.
#define SCI_CONFIG_PAR_MASK 0x0060U
Parity Mask.
Referenced by SCI_getConfig(), SCI_getParityMode(), SCI_setConfig(), and SCI_setParityMode().
#define SCI_RXSTATUS_WAKE 0x0002U
Receiver wake up detect.
#define SCI_RXSTATUS_PARITY 0x0004U
Parity error.
#define SCI_RXSTATUS_OVERRUN 0x0008U
Overrun error.
#define SCI_RXSTATUS_FRAMING 0x0010U
Framing error.
#define SCI_RXSTATUS_BREAK 0x0020U
Break detect.
#define SCI_RXSTATUS_READY 0x0040U
Receiver ready.
#define SCI_RXSTATUS_ERROR 0x0080U
Receiver error.
Enumeration Type Documentation
enum SCI_ParityType
Values that can be used with SCI_setParityMode() and SCI_getParityMode() to describe the parity of the SCI communication.
Enumerator
SCI_CONFIG_PAR_NONE
No parity.
SCI_CONFIG_PAR_EVEN
Even parity.
SCI_CONFIG_PAR_ODD
Odd parity.
enum SCI_TxFIFOLevel
Values that can be passed to SCI_setFIFOInterruptLevel() as the txLevel parameter and returned by SCI_getFIFOInteruptLevel() and SCI_getTxFIFOStatus().
Enumerator
SCI_FIFO_TX0
Transmit interrupt empty.
SCI_FIFO_TX1
Transmit interrupt 1/16 full.
SCI_FIFO_TX2
Transmit interrupt 2/16 full.
SCI_FIFO_TX3
Transmit interrupt 3/16 full.
SCI_FIFO_TX4
Transmit interrupt 4/16 full.
SCI_FIFO_TX5
Transmit interrupt 5/16 full.
SCI_FIFO_TX6
Transmit interrupt 6/16 full.
SCI_FIFO_TX7
Transmit interrupt 7/16 full.
SCI_FIFO_TX8
Transmit interrupt 8/16 full.
SCI_FIFO_TX9
Transmit interrupt 9/16 full.
SCI_FIFO_TX10
Transmit interrupt 10/16 full.
SCI_FIFO_TX11
Transmit interrupt 11/16 full.
SCI_FIFO_TX12
Transmit interrupt 12/16 full.
SCI_FIFO_TX13
Transmit interrupt 13/16 full.
SCI_FIFO_TX14
Transmit interrupt 14/16 full.
SCI_FIFO_TX15
Transmit interrupt 15/16 full.
SCI_FIFO_TX16
Transmit interrupt full.
enum SCI_RxFIFOLevel
Values that can be passed to SCI_setFIFOInterruptLevel() as the rxLevel parameter and returned by SCI_getFIFOInterruptLevel() and SCI_getRxFIFOStatus().
Enumerator
SCI_FIFO_RX0
Receive interrupt empty.
SCI_FIFO_RX1
Receive interrupt 1/16 full.
SCI_FIFO_RX2
Receive interrupt 2/16 full.
SCI_FIFO_RX3
Receive interrupt 3/16 full.
SCI_FIFO_RX4
Receive interrupt 4/16 full.
SCI_FIFO_RX5
Receive interrupt 5/16 full.
SCI_FIFO_RX6
Receive interrupt 6/16 full.
SCI_FIFO_RX7
Receive interrupt 7/16 full.
SCI_FIFO_RX8
Receive interrupt 8/16 full.
SCI_FIFO_RX9
Receive interrupt 9/16 full.
SCI_FIFO_RX10
Receive interrupt 10/16 full.
SCI_FIFO_RX11
Receive interrupt 11/16 full.
SCI_FIFO_RX12
Receive interrupt 12/16 full.
SCI_FIFO_RX13
Receive interrupt 13/16 full.
SCI_FIFO_RX14
Receive interrupt 14/16 full.
SCI_FIFO_RX15
Receive interrupt 15/16 full.
SCI_FIFO_RX16
Receive interrupt full.
Function Documentation
static void SCI_setParityMode (uint32_t base, SCI_ParityType parity) inline static
Sets the type of parity.
Parameters
base is the base address of the SCI port.
parity specifies the type of parity to use.
Sets the type of parity to use for transmitting and expect when receiving. The parity parameter must be one of the following: SCI_CONFIG_PAR_NONE, SCI_CONFIG_PAR_EVEN, SCI_CONFIG_PAR_ODD.
Returns
None.
References ASSERT, HWREGH, SCI_CONFIG_PAR_MASK, and SCI_O_CCR.
static SCI_ParityType SCI_getParityMode (uint32_t base) inline static
Gets the type of parity currently being used.
Parameters
base is the base address of the SCI port.
This function gets the type of parity used for transmitting data and expected when receiving data.
Returns
Returns the current parity settings, specified as one of the following: SCI_CONFIG_PAR_NONE, SCI_CONFIG_PAR_EVEN, SCI_CONFIG_PAR_ODD.
References ASSERT, HWREGH, SCI_CONFIG_PAR_MASK, and SCI_O_CCR.
static void SCI_lockAutobaud (uint32_t base) inline static
Locks Autobaud.
Parameters
base is the base address of the SCI port.
This function performs an autobaud lock for the SCI.
Returns
None.
References ASSERT, HWREGH, SCI_FFCT_ABD, SCI_FFCT_ABDCLR, SCI_FFCT_CDC, SCI_O_FFCT, SCI_O_HBAUD, and SCI_O_LBAUD.
static void SCI_setFIFOInterruptLevel (uint32_t base, SCI_TxFIFOLevel txLevel, SCI_RxFIFOLevel rxLevel) inline static
Sets the FIFO interrupt level at which interrupts are generated.
Parameters
base is the base address of the SCI port.
txLevel is the transmit FIFO interrupt level, specified as one of the following: SCI_FIFO_TX0, SCI_FIFO_TX1, SCI_FIFO_TX2, . . . or SCI_FIFO_TX15.
rxLevel is the receive FIFO interrupt level, specified as one of the following SCI_FIFO_RX0, SCI_FIFO_RX1, SCI_FIFO_RX2, ... or SCI_FIFO_RX15.
This function sets the FIFO level at which transmit and receive interrupts are generated.
Returns
None.
References ASSERT, HWREGH, SCI_FFRX_RXFFIL_M, SCI_FFTX_TXFFIL_M, SCI_O_FFRX, and SCI_O_FFTX.
static void SCI_getFIFOInterruptLevel (uint32_t base, SCI_TxFIFOLevel * txLevel, SCI_RxFIFOLevel * rxLevel) inline static
Gets the FIFO interrupt level at which interrupts are generated.
Parameters
base is the base address of the SCI port.
txLevel is a pointer to storage for the transmit FIFO interrupt level, returned as one of the following: SCI_FIFO_TX0, SCI_FIFO_TX1, SCI_FIFO_TX2, ... or SCI_FIFO_TX15.
rxLevel is a pointer to storage for the receive FIFO interrupt level, returned as one of the following: SCI_FIFO_RX0, SCI_FIFO_RX1, SCI_FIFO_RX2, ... or SCI_FIFO_RX15.
This function gets the FIFO level at which transmit and receive interrupts are generated.
Returns
None.
References ASSERT, HWREGH, SCI_FFRX_RXFFIL_M, SCI_FFTX_TXFFIL_M, SCI_O_FFRX, and SCI_O_FFTX.
static void SCI_getConfig (uint32_t base, uint32_t lspclkHz, uint32_t * baud, uint32_t * config) inline static
Gets the current configuration of a SCI.
Parameters
base is the base address of the SCI port.
lspclkHz is the rate of the clock supplied to the SCI module. This is the LSPCLK.
baud is a pointer to storage for the baud rate.
config is a pointer to storage for the data format.
The baud rate and data format for the SCI is determined, given an explicitly provided peripheral clock (hence the ExpClk suffix). The returned baud rate is the actual baud rate; it may not be the exact baud rate requested or an ``official'' baud rate. The data format returned in config is enumerated the same as the config parameter of SCI_setConfig().
The peripheral clock is the low speed peripheral clock. This will be the value returned by SysCtl_getLowSeedClock(), or it can be explicitly hard coded if it is constant and known (to save the code/execution overhead of a call to SysCtl_getLowSpeedClock()).
Returns
None.
References ASSERT, HWREGH, SCI_CONFIG_PAR_MASK, SCI_CONFIG_STOP_MASK, SCI_CONFIG_WLEN_MASK, SCI_O_CCR, SCI_O_HBAUD, and SCI_O_LBAUD.
static void SCI_enableModule (uint32_t base) inline static
Enables transmitting and receiving.
Parameters
base is the base address of the SCI port.
Enables SCI by taking SCI out of the software reset. Sets the TXENA, and RXENA bits which enables transmit and receive.
Returns
None.
References ASSERT, HWREGH, SCI_CTL1_RXENA, SCI_CTL1_SWRESET, SCI_CTL1_TXENA, and SCI_O_CTL1.
Referenced by SCI_setConfig().
static void SCI_disableModule (uint32_t base) inline static
Disables transmitting and receiving.
Parameters
base is the base address of the SCI port.
Clears the SCIEN, TXE, and RXE bits. The user should ensure that all the data has been sent before disable the module during transmission.
Returns
None.
References ASSERT, HWREGH, SCI_CTL1_RXENA, SCI_CTL1_TXENA, SCI_FFTX_SCIFFENA, SCI_O_CTL1, and SCI_O_FFTX.
Referenced by SCI_setConfig().
static void SCI_enableFIFO (uint32_t base) inline static
Enables the transmit and receive FIFOs.
Parameters
base is the base address of the SCI port.
This functions enables the transmit and receive FIFOs in the SCI.
Returns
None.
References ASSERT, HWREGH, SCI_FFRX_RXFIFORESET, SCI_FFTX_SCIFFENA, SCI_FFTX_SCIRST, SCI_FFTX_TXFIFORESET, SCI_O_FFRX, and SCI_O_FFTX.
static void SCI_disableFIFO (uint32_t base) inline static
Disables the transmit and receive FIFOs.
Parameters
base is the base address of the SCI port.
This functions disables the transmit and receive FIFOs in the SCI.
Returns
None.
References ASSERT, HWREGH, SCI_FFTX_SCIFFENA, and SCI_O_FFTX.
static bool SCI_isFIFOEnabled (uint32_t base) inline static
Determines if the FIFO enhancement is enabled.
Parameters
base is the base address of the SCI port.
This function returns a flag indicating whether or not the FIFO enhancement is enabled.
Returns
Returns true if the FIFO enhancement is enabled or false if the FIFO enhancement is disabled.
References ASSERT, HWREGH, SCI_FFTX_SCIFFENA, and SCI_O_FFTX.
Referenced by SCI_isTransmitterBusy(), SCI_readCharArray(), and SCI_writeCharArray().
static void SCI_resetRxFIFO (uint32_t base) inline static
Resets the receive FIFO.
Parameters
base is the base address of the SCI port.
This functions resets the receive FIFO of the SCI.
Returns
None.
References ASSERT, HWREGH, SCI_FFRX_RXFIFORESET, and SCI_O_FFRX.
static void SCI_resetTxFIFO (uint32_t base) inline static
Resets the transmit FIFO.
Parameters
base is the base address of the SCI port.
This functions resets the transmit FIFO of the SCI.
Returns
None.
References ASSERT, HWREGH, SCI_FFTX_TXFIFORESET, and SCI_O_FFTX.
static void SCI_resetChannels (uint32_t base) inline static
Resets the SCI Transmit and Receive Channels
Parameters
base is the base address of the SCI port.
This functions resets transmit and receive channels in the SCI.
Returns
None.
References ASSERT, HWREGH, SCI_FFTX_SCIRST, and SCI_O_FFTX.
static bool SCI_isDataAvailableNonFIFO (uint32_t base) inline static
Determines if there are any characters in the receive buffer when the FIFO enhancement is not enabled.
Parameters
base is the base address of the SCI port.
This function returns a flag indicating whether or not there is data available in the receive buffer.
Returns
Returns true if there is data in the receive buffer or false if there is no data in the receive buffer.
References ASSERT, HWREGH, SCI_O_RXST, and SCI_RXST_RXRDY.
Referenced by SCI_readCharArray(), and SCI_readCharBlockingNonFIFO().
static bool SCI_isSpaceAvailableNonFIFO (uint32_t base) inline static
Determines if there is any space in the transmit buffer when the FIFO enhancement is not enabled.
Parameters
base is the base address of the SCI port.
This function returns a flag indicating whether or not there is space available in the transmit buffer when not using the FIFO enhancement.
Returns
Returns true if there is space available in the transmit buffer or false if there is no space available in the transmit buffer.
References ASSERT, HWREGH, SCI_CTL2_TXRDY, and SCI_O_CTL2.
Referenced by SCI_writeCharArray(), and SCI_writeCharBlockingNonFIFO().
static SCI_TxFIFOLevel SCI_getTxFIFOStatus (uint32_t base) inline static
Get the transmit FIFO status
Parameters
base is the base address of the SCI port.
This functions gets the current number of words in the transmit FIFO.
Returns
Returns the current number of words in the transmit FIFO specified as one of the following: SCI_FIFO_TX0, SCI_FIFO_TX1, SCI_FIFO_TX2, SCI_FIFO_TX3 SCI_FIFO_TX4, ..., or SCI_FIFO_TX16
References ASSERT, HWREGH, SCI_FFTX_TXFFST_M, SCI_FFTX_TXFFST_S, and SCI_O_FFTX.
Referenced by SCI_writeCharArray(), and SCI_writeCharBlockingFIFO().
static SCI_RxFIFOLevel SCI_getRxFIFOStatus (uint32_t base) inline static
Get the receive FIFO status
Parameters
base is the base address of the SCI port.
This functions gets the current number of words in the receive FIFO.
Returns
Returns the current number of words in the receive FIFO specified as one of the following: SCI_FIFO_RX0, SCI_FIFO_RX1, SCI_FIFO_RX2, SCI_FIFO_RX3 SCI_FIFO_RX4, ..., or SCI_FIFO_RX16
References ASSERT, HWREGH, SCI_FFRX_RXFFST_M, SCI_FFRX_RXFFST_S, and SCI_O_FFRX.
Referenced by SCI_readCharArray(), and SCI_readCharBlockingFIFO().
static bool SCI_isTransmitterBusy (uint32_t base) inline static
Determines whether the SCI transmitter is busy or not.
Parameters
base is the base address of the SCI port.
Allows the caller to determine whether all transmitted bytes have cleared the transmitter hardware when the FIFO is not enabled. When the FIFO is enabled, this function allows the caller to determine whether there is any data in the FIFO.
Without the FIFO enabled, if false is returned, the transmit buffer and shift registers are empty and the transmitter is not busy. With the FIFO enabled, if false is returned, the FIFO is empty. This does not necessarily mean that the transmitter is not busy. The empty FIFO does not reflect the status of the transmitter shift register. The FIFO may be empty while the transmitter is still transmitting data.
Returns
Returns true if the SCI is transmitting or false if transmissions are complete.
References ASSERT, HWREGH, SCI_CTL2_TXEMPTY, SCI_FFTX_TXFFST_M, SCI_isFIFOEnabled(), SCI_O_CTL2, and SCI_O_FFTX.
static void SCI_writeCharBlockingFIFO (uint32_t base, uint16_t data) inline static
Waits to send a character from the specified port when the FIFO enhancement is enabled.
Parameters
base is the base address of the SCI port.
data is the character to be transmitted.
Sends the character data to the transmit buffer for the specified port. If there is no space available in the transmit FIFO, this function waits until there is space available before returning. data is a uint16_t but only 8 bits are written to the SCI port. SCI only transmits 8 bit characters.
Returns
None.
References ASSERT, HWREGH, SCI_FIFO_TX15, SCI_getTxFIFOStatus(), and SCI_O_TXBUF.
static void SCI_writeCharBlockingNonFIFO (uint32_t base, uint16_t data) inline static
Waits to send a character from the specified port.
Parameters
base is the base address of the SCI port.
data is the character to be transmitted.
Sends the character data to the transmit buffer for the specified port. If there is no space available in the transmit buffer, or the transmit FIFO if it is enabled, this function waits until there is space available before returning. data is a uint16_t but only 8 bits are written to the SCI port. SCI only transmits 8 bit characters.
Returns
None.
References ASSERT, HWREGH, SCI_isSpaceAvailableNonFIFO(), and SCI_O_TXBUF.
static void SCI_writeCharNonBlocking (uint32_t base, uint16_t data) inline static
Sends a character to the specified port.
Parameters
base is the base address of the SCI port.
data is the character to be transmitted.
Writes the character data to the transmit buffer for the specified port. This function does not block and only writes to the transmit buffer. The user should use SCI_isSpaceAvailableNonFIFO() or SCI_getTxFIFOStatus() to determine if the transmit buffer or FIFO have space available. data is a uint16_t but only 8 bits are written to the SCI port. SCI only transmits 8 bit characters.
This function replaces the original SCICharNonBlockingPut() API and performs the same actions. A macro is provided in sci.h to map the original API to this API.
Returns
None.
References ASSERT, HWREGH, and SCI_O_TXBUF.
static uint16_t SCI_readCharBlockingFIFO (uint32_t base) inline static
Waits for a character from the specified port when the FIFO enhancement is enabled.
Parameters
base is the base address of the SCI port.
Gets a character from the receive FIFO for the specified port. If there are no characters available, this function waits until a character is received before returning.
Returns
Returns the character read from the specified port as uint16_t.
References ASSERT, HWREGH, SCI_FIFO_RX0, SCI_getRxFIFOStatus(), SCI_O_RXBUF, and SCI_RXBUF_SAR_M.
static uint16_t SCI_readCharBlockingNonFIFO (uint32_t base) inline static
Waits for a character from the specified port when the FIFO enhancement is not enabled.
Parameters
base is the base address of the SCI port.
Gets a character from the receive buffer for the specified port. If there is no characters available, this function waits until a character is received before returning.
Returns
Returns the character read from the specified port as uint16_t.
References ASSERT, HWREGH, SCI_isDataAvailableNonFIFO(), SCI_O_RXBUF, and SCI_RXBUF_SAR_M.
static uint16_t SCI_readCharNonBlocking (uint32_t base) inline static
Receives a character from the specified port.
Parameters
base is the base address of the SCI port.
Gets a character from the receive buffer for the specified port. This function does not block and only reads the receive buffer. The user should use SCI_isDataAvailableNonFIFO() or SCI_getRxFIFOStatus() to determine if the receive buffer or FIFO have data available.
This function replaces the original SCICharNonBlockingGet() API and performs the same actions. A macro is provided in sci.h to map the original API to this API.
Returns
Returns uin16_t which is read from the receive buffer.
References ASSERT, HWREGH, SCI_O_RXBUF, and SCI_RXBUF_SAR_M.
static uint16_t SCI_getRxStatus (uint32_t base) inline static
Gets current receiver status flags.
Parameters
base is the base address of the SCI port.
This function returns the current receiver status flags. The returned error flags are equivalent to the error bits returned via the previous reading or receiving of a character with the exception that the overrun error is set immediately the overrun occurs rather than when a character is next read.
Returns
Returns a bitwise OR combination of the receiver status flags, SCI_RXSTATUS_WAKE, SCI_RXSTATUS_PARITY, SCI_RXSTATUS_OVERRUN, SCI_RXSTATUS_FRAMING, SCI_RXSTATUS_BREAK, SCI_RXSTATUS_READY, and SCI_RXSTATUS_ERROR.
References ASSERT, HWREGH, and SCI_O_RXST.
static void SCI_performSoftwareReset (uint32_t base) inline static
Performs a software reset of the SCI and Clears all reported receiver status flags.
Parameters
base is the base address of the SCI port.
This function performs a software reset of the SCI port. It affects the operating flags of the SCI, but it neither affects the configuration bits nor restores the reset values.
Returns
None.
References ASSERT, HWREGH, SCI_CTL1_SWRESET, and SCI_O_CTL1.
Referenced by SCI_clearInterruptStatus().
static void SCI_enableLoopback (uint32_t base) inline static
Enables Loop Back Test Mode
Parameters
base is the base address of the SCI port.
Enables the loop back test mode where the Tx pin is internally connected to the Rx pin.
Returns
None.
References ASSERT, HWREGH, SCI_CCR_LOOPBKENA, and SCI_O_CCR.
static void SCI_disableLoopback (uint32_t base) inline static
Disables Loop Back Test Mode
Parameters
base is the base address of the SCI port.
Disables the loop back test mode where the Tx pin is no longer internally connected to the Rx pin.
Returns
None.
References ASSERT, HWREGH, SCI_CCR_LOOPBKENA, and SCI_O_CCR.
static bool SCI_getOverflowStatus (uint32_t base) inline static
Get the receive FIFO Overflow flag status
Parameters
base is the base address of the SCI port.
This functions gets the receive FIFO overflow flag status.
Returns
Returns true if overflow has occurred, else returned false if an overflow hasn't occurred.
References ASSERT, HWREGH, SCI_FFRX_RXFFOVF, and SCI_O_FFRX.
static void SCI_clearOverflowStatus (uint32_t base) inline static
Clear the receive FIFO Overflow flag status
Parameters
base is the base address of the SCI port.
This functions clears the receive FIFO overflow flag status.
Returns
None.
References ASSERT, HWREGH, SCI_FFRX_RXFFOVRCLR, and SCI_O_FFRX.
void SCI_setConfig (uint32_t base, uint32_t lspclkHz, uint32_t baud, uint32_t config)
Sets the configuration of a SCI.
Parameters
base is the base address of the SCI port.
lspclkHz is the rate of the clock supplied to the SCI module. This is the LSPCLK.
baud is the desired baud rate.
config is the data format for the port (number of data bits, number of stop bits, and parity).
This function configures the SCI for operation in the specified data format. The baud rate is provided in the baud parameter and the data format in the config parameter.
The config parameter is the bitwise OR of three values: the number of data bits, the number of stop bits, and the parity. SCI_CONFIG_WLEN_8, SCI_CONFIG_WLEN_7, SCI_CONFIG_WLEN_6, SCI_CONFIG_WLEN_5, SCI_CONFIG_WLEN_4, SCI_CONFIG_WLEN_3, SCI_CONFIG_WLEN_2, and SCI_CONFIG_WLEN_1. Select from eight to one data bits per byte (respectively). SCI_CONFIG_STOP_ONE and SCI_CONFIG_STOP_TWO select one or two stop bits (respectively). SCI_CONFIG_PAR_NONE, SCI_CONFIG_PAR_EVEN, SCI_CONFIG_PAR_ODD, select the parity mode (no parity bit, even parity bit, odd parity bit respectively).
The peripheral clock is the low speed peripheral clock. This will be the value returned by SysCtl_getLowSpeedClock(), or it can be explicitly hard coded if it is constant and known (to save the code/execution overhead of a call to SysCtl_getLowSpeedClock()).
Returns
None.
References ASSERT, HWREGH, SCI_CONFIG_PAR_MASK, SCI_CONFIG_STOP_MASK, SCI_CONFIG_WLEN_MASK, SCI_disableModule(), SCI_enableModule(), SCI_O_CCR, SCI_O_HBAUD, and SCI_O_LBAUD.
void SCI_writeCharArray (uint32_t base, const uint16_t *const array, uint16_t length)
Waits to send an array of characters from the specified port.
Parameters
base is the base address of the SCI port.
array is the address of the array of characters to be transmitted. It is pointer to the array of characters to be transmitted.
length is the length of the array, or number of characters in the array to be transmitted.
Sends the number of characters specified by length, starting at the address array, out of the transmit buffer for the specified port. If there is no space available in the transmit buffer, or the transmit FIFO if it is enabled, this function waits until there is space available and length number of characters are transmitted before returning. array is a pointer to uint16_ts but only the least significant 8 bits are written to the SCI port. SCI only transmits 8 bit characters.
Returns
None.
References ASSERT, HWREGH, SCI_FIFO_TX15, SCI_getTxFIFOStatus(), SCI_isFIFOEnabled(), SCI_isSpaceAvailableNonFIFO(), and SCI_O_TXBUF.
void SCI_readCharArray (uint32_t base, uint16_t *const array, uint16_t length)
Waits to receive an array of characters from the specified port.
Parameters
base is the base address of the SCI port.
array is the address of the array of characters to be received. It is a pointer to the array of characters to be received.
length is the length of the array, or number of characters in the array to be received.
Receives an array of characters from the receive buffer for the specified port, and stores them as an array of characters starting at address array. This function waits until the length number of characters are received before returning.
Returns
None.
References ASSERT, HWREGH, SCI_FIFO_RX0, SCI_getRxFIFOStatus(), SCI_isDataAvailableNonFIFO(), SCI_isFIFOEnabled(), SCI_O_RXBUF, and SCI_RXBUF_SAR_M.
void SCI_enableInterrupt (uint32_t base, uint32_t intFlags)
Enables individual SCI interrupt sources.
Parameters
base is the base address of the SCI port.
intFlags is the bit mask of the interrupt sources to be enabled.
Enables the indicated SCI interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
The intFlags parameter is the bitwise OR of any of the following:
SCI_INT_RXERR - RXERR Interrupt
SCI_INT_RXRDY_BRKDT - RXRDY/BRKDT Interrupt
SCI_INT_TXRDY - TXRDY Interrupt
SCI_INT_TXFF - TX FIFO Level Interrupt
SCI_INT_RXFF - RX FIFO Level Interrupt
SCI_INT_FE - Frame Error
SCI_INT_OE - Overrun Error
SCI_INT_PE - Parity Error
Returns
None.
References ASSERT, HWREGH, SCI_CTL1_RXERRINTENA, SCI_CTL2_RXBKINTENA, SCI_CTL2_TXINTENA, SCI_FFRX_RXFFIENA, SCI_FFTX_TXFFIENA, SCI_INT_RXERR, SCI_INT_RXFF, SCI_INT_RXRDY_BRKDT, SCI_INT_TXFF, SCI_INT_TXRDY, SCI_O_CTL1, SCI_O_CTL2, SCI_O_FFRX, and SCI_O_FFTX.
void SCI_disableInterrupt (uint32_t base, uint32_t intFlags)
Disables individual SCI interrupt sources.
Parameters
base is the base address of the SCI port.
intFlags is the bit mask of the interrupt sources to be disabled.
Disables the indicated SCI interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
The intFlags parameter has the same definition as the intFlags parameter to SCI_enableInterrupt().
Returns
None.
References ASSERT, HWREGH, SCI_CTL1_RXERRINTENA, SCI_CTL2_RXBKINTENA, SCI_CTL2_TXINTENA, SCI_FFRX_RXFFIENA, SCI_FFTX_TXFFIENA, SCI_INT_RXERR, SCI_INT_RXFF, SCI_INT_RXRDY_BRKDT, SCI_INT_TXFF, SCI_INT_TXRDY, SCI_O_CTL1, SCI_O_CTL2, SCI_O_FFRX, and SCI_O_FFTX.
uint32_t SCI_getInterruptStatus (uint32_t base)
Gets the current interrupt status.
Parameters
base is the base address of the SCI port.
Returns
Returns the current interrupt status, enumerated as a bit field of values described in SCI_enableInterrupt().
References ASSERT, HWREGH, SCI_CTL2_TXRDY, SCI_FFRX_RXFFINT, SCI_FFTX_TXFFINT, SCI_INT_FE, SCI_INT_OE, SCI_INT_PE, SCI_INT_RXERR, SCI_INT_RXFF, SCI_INT_RXRDY_BRKDT, SCI_INT_TXFF, SCI_INT_TXRDY, SCI_O_CTL2, SCI_O_FFRX, SCI_O_FFTX, SCI_O_RXST, SCI_RXST_BRKDT, SCI_RXST_FE, SCI_RXST_OE, SCI_RXST_PE, SCI_RXST_RXERROR, and SCI_RXST_RXRDY.
void SCI_clearInterruptStatus (uint32_t base, uint32_t intFlags)
Clears SCI interrupt sources.
Parameters
base is the base address of the SCI port.
intFlags is a bit mask of the interrupt sources to be cleared.
The specified SCI interrupt sources are cleared, so that they no longer assert. This function must be called in the interrupt handler to keep the interrupt from being recognized again immediately upon exit.
The intFlags parameter has the same definition as the intFlags parameter to SCI_enableInterrupt().
Returns
None.
References ASSERT, HWREGH, SCI_FFRX_RXFFINTCLR, SCI_FFTX_TXFFINTCLR, SCI_INT_FE, SCI_INT_OE, SCI_INT_PE, SCI_INT_RXERR, SCI_INT_RXFF, SCI_INT_RXRDY_BRKDT, SCI_INT_TXFF, SCI_O_FFRX, SCI_O_FFTX, and SCI_performSoftwareReset().
Copyright 2018, Texas Instruments Incorporated